ANIMA: animaDDIApplyTransformSerie.cxx File Reference
animaDDIApplyTransformSerie.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <animaTransformSeriesReader.h>
#include <itkNearestNeighborInterpolateImageFunction.h>
#include <animaDDILinearInterpolateImageFunction.h>
#include <animaFiniteStrainDDIResampleImageFilter.h>
Functions
int main (int ac, const char **av)
Function Documentation
int main (int ac, const char ** av)
Definition at line 12 of file animaDDIApplyTransformSerie.cxx.
References anima::CompartmentSize, anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::New(), anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::SetMethod(), and anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::SetNumberOfOutputFascicles().