ANIMA: animaGetDDIComponent.cxx File Reference
animaGetDDIComponent.cxx File Reference
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkImage.h>
#include <itkVectorImage.h>
#include <itkImageRegionIterator.h>
#include <itkImageRegionConstIterator.h>
#include <itkDiffusionTensor3D.h>
#include <vnl/vnl_vector_fixed.h>
#include <animaDDIDistribution.h>
#include <animaHyperbolicFunctions.h>
#include <boost/lexical_cast.hpp>
#include <tclap/CmdLine.h>
Functions
template<class VectorImageType , class ImageType >
ImageType::Pointer getImage (const typename VectorImageType::Pointer &inImage, const std::string &componentType, const unsigned int fascicleNumber)
template<class InputVectorImageType , class OutputVectorImageType >
OutputVectorImageType::Pointer getVectorImage (const typename InputVectorImageType::Pointer &inImage, const unsigned int fascicleNumber)
int main (int argc, char **argv)
std::string removeExtension (const std::string &filename)
template<class ImageType >
void writeImage (const typename ImageType::Pointer &outImage, const std::string &baseFileName, const std::string &componentType, const unsigned int fascicleNumber)
template<class VectorImageType >
void writeVectorImage (const typename VectorImageType::Pointer &outImage, const std::string &baseFileName, const unsigned int fascicleNumber)
Function Documentation
template<class VectorImageType , class ImageType > ImageType::Pointer getImage (const typename VectorImageType::Pointer & inImage, const std::string & componentType, const unsigned int fascicleNumber)
Definition at line 87 of file animaGetDDIComponent.cxx.
References anima::CompartmentSize, and anima::WIndex.
template<class InputVectorImageType , class OutputVectorImageType > OutputVectorImageType::Pointer getVectorImage (const typename InputVectorImageType::Pointer & inImage, const unsigned int fascicleNumber)
Definition at line 26 of file animaGetDDIComponent.cxx.
References anima::AIndex, anima::CompartmentSize, anima::DIndex, anima::KappaIndex, and anima::xi().
int main (int argc, char ** argv)
Image typedef support
Definition at line 195 of file animaGetDDIComponent.cxx.
References anima::CompartmentSize.
std::string removeExtension (const std::string & filename)
Definition at line 18 of file animaGetDDIComponent.cxx.
Referenced by writeImage(), and writeVectorImage().
template<class ImageType > void writeImage (const typename ImageType::Pointer & outImage, const std::string & baseFileName, const std::string & componentType, const unsigned int fascicleNumber)
Definition at line 162 of file animaGetDDIComponent.cxx.
References removeExtension().
template<class VectorImageType > void writeVectorImage (const typename VectorImageType::Pointer & outImage, const std::string & baseFileName, const unsigned int fascicleNumber)
Definition at line 142 of file animaGetDDIComponent.cxx.
References removeExtension().