ANIMA: animaGetScalarMapFromDDI.cxx File Reference
animaGetScalarMapFromDDI.cxx File Reference
#include <cmath>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkTimeProbe.h>
#include <itkImage.h>
#include <itkVectorImage.h>
#include <itkImageRegionIterator.h>
#include <animaHyperbolicFunctions.h>
#include <animaDDIDistribution.h>
#include <tclap/CmdLine.h>
Macros
#define _USE_MATH_DEFINES
Enumerations
enum StringValue {
evNotDefined,
evStringValue1,
evStringValue2,
evStringValue3,
evStringValue4,
evStringValue5,
evStringValue6,
evStringValue7,
evStringValue8,
evStringValue9,
evStringValue10
}
Functions
static void InitializeStringArguments ()
int main (int argc, char **argv)
Variables
static std::map< std::string,
StringValue > s_mapStringValues
Macro Definition Documentation
#define _USE_MATH_DEFINES
Definition at line 1 of file animaGetScalarMapFromDDI.cxx.
Enumeration Type Documentation
enum StringValue
Enumerator
evNotDefined
evStringValue1
evStringValue2
evStringValue3
evStringValue4
evStringValue5
evStringValue6
evStringValue7
evStringValue8
evStringValue9
evStringValue10
Definition at line 18 of file animaGetScalarMapFromDDI.cxx.
Function Documentation
void InitializeStringArguments () static
Definition at line 37 of file animaGetScalarMapFromDDI.cxx.
References evStringValue1, evStringValue10, evStringValue2, evStringValue3, evStringValue4, evStringValue5, evStringValue6, evStringValue7, evStringValue8, and evStringValue9.
Referenced by main().
int main (int argc, char ** argv)
Image typedef support
Definition at line 53 of file animaGetScalarMapFromDDI.cxx.
References anima::AIndex, anima::CompartmentSize, anima::DIndex, evStringValue1, evStringValue10, evStringValue2, evStringValue3, evStringValue4, evStringValue5, evStringValue6, evStringValue7, evStringValue8, evStringValue9, InitializeStringArguments(), anima::jfour(), anima::jtwo(), anima::KappaIndex, anima::WIndex, and anima::xi().
Variable Documentation
std::map<std::string, StringValue> s_mapStringValues static
Definition at line 33 of file animaGetScalarMapFromDDI.cxx.