ANIMA: animaDTINonCentralChiEstimator.cxx File Reference
animaDTINonCentralChiEstimator.cxx File Reference
#include <animaDTINonCentralChiEstimationImageFilter.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
#include <animaGradientFileReader.h>
Functions
double ComputeEulerMascheroniConstant (unsigned int m)
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
double ComputeEulerMascheroniConstant (unsigned int m)
Definition at line 11 of file animaDTINonCentralChiEstimator.cxx.
Referenced by main().
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 21 of file animaDTINonCentralChiEstimator.cxx.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 27 of file animaDTINonCentralChiEstimator.cxx.
References ComputeEulerMascheroniConstant(), eventCallback(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName().