ANIMA: anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage > Class Template Reference
anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage > Class Template Reference
#include <animaTensorSymmetricBlockMatchingRegistrationMethod.h>
Public Types
typedef
Superclass::AffineTransformType AffineTransformType
typedef Superclass::AgregatorType AgregatorType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::ImageIndexType ImageIndexType
typedef Superclass::ImageRegionType ImageRegionType
typedef Superclass::InputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
TensorSymmetricBlockMatchingRegistrationMethod Self
typedef
TensorBlockMatchingBaseRegistrationMethod
< TInputImage > Superclass
typedef
Superclass::SVFTransformType SVFTransformType
typedef
Superclass::ThreadedMatchData ThreadedMatchData
typedef
Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImage::ImageDimension > AffineTransformType
typedef BaseTransformAgregator
< InputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MetricType::TransformType BaseTransformType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::DataObject::Pointer DataObjectPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > DisplacementFieldTransformType
typedef InputImageType::IndexType ImageIndexType
typedef InputImageType::RegionType ImageRegionType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
MetricType::InterpolatorType InterpolatorType
typedef MetricType::Pointer MetricPointer
typedef
anima::BaseTensorImageToImageMetric
< InputImageType,
InputImageType > MetricType
enum OptimizerDefinition {
Exhaustive,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef
MetricType::TransformParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef
TensorBlockMatchingBaseRegistrationMethod Self
enum SimilarityDefinition {
TensorMeanSquares,
TensorCorrelation,
TensorGeneralizedCorrelation,
TensorOrientedGeneralizedCorrelation
}
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > SVFTransformType
enum TransformationDefinition {
Translation,
Rigid,
Affine
}
typedef
TransformOutputType::ConstPointer TransformOutputConstPointer
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< ImageRegionType > & GetFixedBlockRegions ()
std::vector< ImageIndexType > & GetFixedDamIndexes ()
std::vector< ImageRegionType > & GetMovingBlockRegions ()
std::vector< ImageIndexType > & GetMovingDamIndexes ()
virtual const char * GetNameOfClass () const
void SetFixedBlockRegions (std::vector< ImageRegionType > &origins)
void SetFixedDamIndexes (std::vector< ImageIndexType > &damInd)
void SetMovingBlockRegions (std::vector< ImageRegionType > &origins)
void SetMovingDamIndexes (std::vector< ImageIndexType > &damInd)
Public Member Functions inherited from anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual const double & GetAngleMax () const
BaseInputTransformType::Pointer GetBaseTransformPointer (unsigned int i)
std::vector< typename
BaseInputTransformType::Pointer > & GetBaseTransformsPointers ()
std::vector< ImageRegionType > & GetBlockRegions ()
virtual double GetBlockTensorVarianceThreshold ()
std::vector< double > & GetBlockWeights ()
virtual const double & GetFinalRadius () const
virtual InputImageType * GetFixedImage ()
virtual const vnl_matrix
< double > & GetGeometry () const
virtual const bool & GetMaximizeMetric () const
virtual const unsigned int & GetMaximumIterations () const
virtual SimilarityDefinition GetMetricKind () const
virtual const double & GetMinimalTransformError () const
virtual InputImageType * GetMovingImage ()
itk::ModifiedTimeType GetMTime () const
virtual OptimizerDefinition GetOptimizerKind () const
virtual const unsigned int & GetOptimizerMaximumIterations () const
TransformOutputType * GetOutput ()
virtual const double & GetScaleMax () const
virtual const double & GetSearchAngleRadius () const
virtual const double & GetSearchRadius () const
virtual const double & GetSearchScaleRadius () const
virtual const double & GetSearchSkewRadius () const
virtual const double & GetSkewMax () const
virtual const double & GetStepSize () const
const std::string GetStopConditionDescription () const
virtual const double & GetSVFElasticRegSigma () const
virtual TransformationDefinition GetTransformKind () const
virtual const double & GetTranslateMax () const
virtual void Initialize () throw (itk::ExceptionObject)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetAngleMax (double _arg)
void SetBaseTransform (unsigned int i, BaseInputTransformType *trsf)
void SetBlockRegions (std::vector< ImageRegionType > &origins)
virtual void SetBlockTensorVarianceThreshold (double _arg)
virtual void SetFinalRadius (double _arg)
void SetFixedImage (InputImageType *fixedImage)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMetricKind (const SimilarityDefinition _arg)
virtual void SetMinimalTransformError (double _arg)
void SetMovingImage (InputImageType *movingImage)
virtual void SetOptimizerKind (const OptimizerDefinition _arg)
virtual void SetOptimizerMaximumIterations (unsigned int _arg)
virtual void SetScaleMax (double _arg)
virtual void SetSearchAngleRadius (double _arg)
virtual void SetSearchRadius (double _arg)
virtual void SetSearchScaleRadius (double _arg)
virtual void SetSearchSkewRadius (double _arg)
virtual void SetSkewMax (double _arg)
virtual void SetStepSize (double _arg)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetTransformKind (const TransformationDefinition _arg)
virtual void SetTranslateMax (double _arg)
void StartOptimization (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)
TensorSymmetricBlockMatchingRegistrationMethod ()
virtual ~TensorSymmetricBlockMatchingRegistrationMethod ()
Protected Member Functions inherited from anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >
virtual void AdditionalBlockMatchingSetup (MetricPointer &metric, unsigned int blockNum)
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
void BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType *fixedImage, InputImageType *resampledImage)
virtual bool ComposeAddOnWithTransform (TransformType *computedTransform, TransformType *addOn)
void GenerateData ()
virtual void GlobalParametersSetup ()
Setting global parameters that don't need to be changed for each block or iteration.
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &floatingImage)
virtual void SetupBlockParameters (InterpolatorPointer &interpolator, MetricPointer &metric, OptimizerPointer &optimizer, unsigned startBlock, unsigned endBlock)
Setting block related parameters that need to be changed for each block or iteration.
virtual void SetupTransform (TransformPointer &optimizedTransform)
TensorBlockMatchingBaseRegistrationMethod ()
virtual ~TensorBlockMatchingBaseRegistrationMethod ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImage>
class anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >
Definition at line 9 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImage > typedef Superclass::AffineTransformType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::AffineTransformType
Definition at line 24 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::AgregatorType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::AgregatorType
Definition at line 26 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef itk::SmartPointer<const Self> anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::ConstPointer
Definition at line 16 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ImageIndexType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::ImageIndexType
Definition at line 22 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ImageRegionType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::ImageRegionType
Definition at line 23 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::InputImageType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::InputImageType
Definition at line 18 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef itk::SmartPointer<Self> anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::Pointer
Definition at line 15 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef TensorSymmetricBlockMatchingRegistrationMethod anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::Self
Standard class typedefs.
Definition at line 13 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef TensorBlockMatchingBaseRegistrationMethod<TInputImage> anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::Superclass
Definition at line 14 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::SVFTransformType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::SVFTransformType
Definition at line 25 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ThreadedMatchData anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::ThreadedMatchData
Definition at line 21 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::TransformPointer anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::TransformPointer
Definition at line 20 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::TransformType anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::TransformType
Definition at line 19 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::TensorSymmetricBlockMatchingRegistrationMethod () protected
Constructor
Definition at line 17 of file animaTensorSymmetricBlockMatchingRegistrationMethod.hxx.
template<typename TInputImage > virtual anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::~TensorSymmetricBlockMatchingRegistrationMethod () inline protected virtual
Definition at line 50 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
Member Function Documentation
template<typename TInputImage > virtual::itk::LightObject::Pointer anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::CreateAnother (void) const
template<typename TInputImage > std::vector<ImageRegionType>& anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetFixedBlockRegions () inline
Definition at line 36 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > std::vector<ImageIndexType>& anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetFixedDamIndexes () inline
Definition at line 42 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > std::vector<ImageRegionType>& anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetMovingBlockRegions () inline
Definition at line 38 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > std::vector<ImageIndexType>& anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetMovingDamIndexes () inline
Definition at line 45 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > virtual const char* anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >.
template<typename TInputImage > static Pointer anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::New () static
Method for creation through the object factory.
template<typename TInputImage > void anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected virtual
Implements anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >.
Definition at line 24 of file animaTensorSymmetricBlockMatchingRegistrationMethod.hxx.
References anima::GetExponential(), anima::GetLogarithm(), anima::DenseSVFTransformAgregator< NDimensions >::SetDamIndexes(), and anima::BalooSVFTransformAgregator< NDimensions >::SetDamIndexes().
template<typename TInputImage > void anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetFixedBlockRegions (std::vector< ImageRegionType > & origins) inline
Set / Get Block Origins
Definition at line 35 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > void anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetFixedDamIndexes (std::vector< ImageIndexType > & damInd) inline
Set/Get the dam indexes.
Definition at line 41 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > void anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetMovingBlockRegions (std::vector< ImageRegionType > & origins) inline
Definition at line 37 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > void anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetMovingDamIndexes (std::vector< ImageIndexType > & damInd) inline
Definition at line 44 of file animaTensorSymmetricBlockMatchingRegistrationMethod.h.
The documentation for this class was generated from the following files:
animaTensorSymmetricBlockMatchingRegistrationMethod.h
animaTensorSymmetricBlockMatchingRegistrationMethod.hxx