ANIMA: anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
#include <animaNLMeansPatientToGroupComparisonImageFilter.h>
Classes
struct SampleIdentifier
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef vnl_matrix< double > CovarianceType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage
< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image
< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
NLMeansPatientToGroupComparisonImageFilter
< PixelScalarType > Self
typedef
anima::MaskedImageToImageFilter
< InputImageType,
OutputImageType > Superclass
typedef InputImageType::PixelType VectorType
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef RegionSplitterType::Pointer RegionSplitterPointer
typedef
anima::ImageRegionSplitterMask
< MaskImageType > RegionSplitterType
typedef MaskedImageToImageFilter Self
typedef
itk::ImageToImageFilter
< itk::VectorImage
< PixelScalarType, 3 >
, itk::Image< PixelScalarType, 3 > > Superclass
Public Member Functions
void AddDatabaseInput (InputImageType *tmpIm)
itkNewMacro (Self)
itkSetMacro (DatabaseCovarianceDistanceAverage, OutputImagePointer)
itkSetMacro (DatabaseCovarianceDistanceStd, OutputImagePointer)
itkSetMacro (DatabaseMeanDistanceAverage, OutputImagePointer)
itkSetMacro (DatabaseMeanDistanceStd, OutputImagePointer)
itkSetMacro (PatchHalfSize, unsigned int)
itkSetMacro (SearchNeighborhood, unsigned int)
itkSetMacro (SearchStepSize, unsigned int)
itkSetMacro (WeightThreshold, double)
itkSetMacro (MeanThreshold, double)
itkSetMacro (VarianceThreshold, double)
itkSetMacro (BetaParameter, double)
itkTypeMacro (NLMeansPatientToGroupComparisonImageFilter, MaskedImageToImageFilter)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
unsigned int GetActualNumberOfThreads ()
itkGetMacro (ComputationMask, MaskImageType *)
itkGetMacro (ComputationRegion, MaskRegionType)
itkNewMacro (Self)
itkSetMacro (ComputationMask, MaskImagePointer)
itkSetMacro (ComputationRegion, MaskRegionType)
itkTypeMacro (MaskedImageToImageFilter, itk::ImageToImageFilter)
Protected Member Functions
void BeforeThreadedGenerateData (void)
NLMeansPatientToGroupComparisonImageFilter ()
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~NLMeansPatientToGroupComparisonImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
virtual const
itk::ImageRegionSplitterBase * GetImageRegionSplitter (void) const
void InitializeComputationRegionFromMask ()
MaskedImageToImageFilter ()
virtual ~MaskedImageToImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >
Definition at line 14 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Member Typedef Documentation
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ConstPointer
Definition at line 21 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef vnl_matrix<double> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::CovarianceType
Definition at line 35 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef InputImageType::IndexType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImageIndexType
Definition at line 38 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef InputImageType::Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImagePointer
Definition at line 37 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType, 3> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 30 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef Superclass::MaskImageType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::MaskImageType
Definition at line 44 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef OutputImageType::Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 39 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 43 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef itk::Image<PixelScalarType, 3> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageType
Definition at line 31 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Pointer
Definition at line 20 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef NLMeansPatientToGroupComparisonImageFilter<PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 19 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Superclass
Superclass typedefs.
Definition at line 42 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> typedef InputImageType::PixelType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::VectorType
Definition at line 33 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Constructor & Destructor Documentation
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::NLMeansPatientToGroupComparisonImageFilter () inline protected
Definition at line 72 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType> virtual anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::~NLMeansPatientToGroupComparisonImageFilter () inline protected virtual
Definition at line 97 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Member Function Documentation
template<class PixelScalarType> void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::AddDatabaseInput (InputImageType * tmpIm) inline
Definition at line 53 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
template<class PixelScalarType > void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Definition at line 17 of file animaNLMeansPatientToGroupComparisonImageFilter.hxx.
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkNewMacro (Self)
Method for creation through the object factory.
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (DatabaseCovarianceDistanceAverage , OutputImagePointer)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (DatabaseCovarianceDistanceStd , OutputImagePointer)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (DatabaseMeanDistanceAverage , OutputImagePointer)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (DatabaseMeanDistanceStd , OutputImagePointer)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (PatchHalfSize , unsigned int)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (SearchNeighborhood , unsigned int)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (SearchStepSize , unsigned int)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (WeightThreshold , double)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (MeanThreshold , double)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (VarianceThreshold , double)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkSetMacro (BetaParameter , double)
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::itkTypeMacro (NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > , MaskedImageToImageFilter)
Run-time type information (and related methods)
template<class PixelScalarType> void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Definition at line 102 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
References anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::PrintSelf().
template<class PixelScalarType > void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 31 of file animaNLMeansPatientToGroupComparisonImageFilter.hxx.
References anima::computeAverageLocalCovariance(), anima::computePatchMeanAndCovariance(), anima::VectorCovarianceTest(), and anima::VectorMeansTest().
The documentation for this class was generated from the following files:
animaNLMeansPatientToGroupComparisonImageFilter.h
animaNLMeansPatientToGroupComparisonImageFilter.hxx