ANIMA: anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaMaskedImageToImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef RegionSplitterType::Pointer RegionSplitterPointer
typedef
anima::ImageRegionSplitterMask
< MaskImageType > RegionSplitterType
typedef MaskedImageToImageFilter Self
typedef
itk::ImageToImageFilter
< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetActualNumberOfThreads ()
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual const char * GetNameOfClass () const
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void BeforeThreadedGenerateData (void)
virtual void CheckComputationMask ()
virtual const
itk::ImageRegionSplitterBase * GetImageRegionSplitter (void) const
void InitializeComputationRegionFromMask ()
MaskedImageToImageFilter ()
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
virtual ~MaskedImageToImageFilter ()
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
Definition at line 11 of file animaMaskedImageToImageFilter.h.
Member Typedef Documentation
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<const Self> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 19 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef Superclass::InputImageRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Superclass typedefs.
Definition at line 25 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskImagePointer
Definition at line 34 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef itk::Image<unsigned char, 3> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskImageType
Mask typedefs
Definition at line 32 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::RegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskRegionType
Definition at line 33 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef Superclass::OutputImageRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 29 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<Self> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 18 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef RegionSplitterType::Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::RegionSplitterPointer
Definition at line 37 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef anima::ImageRegionSplitterMask<MaskImageType> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::RegionSplitterType
Definition at line 36 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef MaskedImageToImageFilter anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 16 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 17 of file animaMaskedImageToImageFilter.h.
Constructor & Destructor Documentation
template<typename TInputImage, typename TOutputImage> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskedImageToImageFilter () inline protected
Definition at line 51 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> virtual anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::~MaskedImageToImageFilter () inline protected virtual
Definition at line 59 of file animaMaskedImageToImageFilter.h.
Member Function Documentation
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented in anima::DDIModelEstimatorImageFilter< PixelScalarType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >, anima::CramersTestImageFilter< PixelScalarType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< PixelScalarType >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, and anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >.
Definition at line 77 of file animaMaskedImageToImageFilter.hxx.
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::CheckComputationMask () protected virtual
Reimplemented in anima::DDIModelEstimatorImageFilter< PixelScalarType >, anima::CombinedRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< PixelScalarType >, anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, and anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 8 of file animaMaskedImageToImageFilter.hxx.
template<typename TInputImage, typename TOutputImage> virtual::itk::LightObject::Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
template<typename TInputImage, typename TOutputImage> unsigned int anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetActualNumberOfThreads () inline
Definition at line 45 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> virtual MaskImageType* anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetComputationMask () virtual
template<typename TInputImage, typename TOutputImage> virtual MaskRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetComputationRegion () virtual
template<typename TInputImage, typename TOutputImage> virtual const itk::ImageRegionSplitterBase* anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetImageRegionSplitter (void) const inline protected virtual
Definition at line 65 of file animaMaskedImageToImageFilter.h.
template<typename TInputImage, typename TOutputImage> virtual const char* anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::DDIModelEstimatorImageFilter< PixelScalarType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::DTIEstimationImageFilter< PixelScalarType >, anima::CramersTestImageFilter< PixelScalarType >, anima::CombinedRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, and anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >.
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InitializeComputationRegionFromMask () protected
Definition at line 29 of file animaMaskedImageToImageFilter.hxx.
template<typename TInputImage, typename TOutputImage> static Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected virtual
Reimplemented in anima::DDIModelEstimatorImageFilter< PixelScalarType >, anima::CombinedRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >, anima::CramersTestImageFilter< PixelScalarType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< PixelScalarType >, anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, and anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >.
Definition at line 72 of file animaMaskedImageToImageFilter.h.
Referenced by anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::PrintSelf(), anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::PrintSelf(), anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), anima::DTIEstimationImageFilter< PixelScalarType >::PrintSelf(), anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), anima::PatientToGroupComparisonImageFilter< PixelScalarType >::PrintSelf(), anima::CramersTestImageFilter< PixelScalarType >::PrintSelf(), anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::PrintSelf(), anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::PrintSelf(), anima::CombinedRelaxometryEstimationImageFilter< TInputImage, TOutputImage >::PrintSelf(), and anima::DDIModelEstimatorImageFilter< PixelScalarType >::PrintSelf().
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::SetComputationMask (MaskImagePointer _arg) virtual
Set/Get the mask on which to compute STAPLE estimate.
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::SetComputationRegion (MaskRegionType _arg) virtual
The documentation for this class was generated from the following files:
animaMaskedImageToImageFilter.h
animaMaskedImageToImageFilter.hxx