ANIMA: impl_cliprogress::ProgressDisplay Class Reference
impl_cliprogress::ProgressDisplay Class Reference
#include <CliProgress.h>
Public Member Functions
ProgressDisplay (const char *name=0, bool set=true)
void setActivity (std::string)
void setFinished ()
void setGraph (std::string name, float x, float y)
void setImageF (std::string, int, int, const float *)
void setImageG (std::string, int, int, const char *)
void setImageRGB (std::string, int, int, const char *)
void setProgress (std::string name, float cur, float max)
void setStatus (std::string)
Static Public Member Functions
static ProgressDisplay & instance ()
Protected Attributes
std::ostream * m_stream
Static Protected Attributes
static ProgressDisplay * m_instance = 0
Detailed Description
Definition at line 28 of file CliProgress.h.
Constructor & Destructor Documentation
impl_cliprogress::ProgressDisplay::ProgressDisplay (const char * name = 0, bool set = true)
Definition at line 38 of file CliProgress.cxx.
References m_instance, and m_stream.
Referenced by instance().
Member Function Documentation
ProgressDisplay & impl_cliprogress::ProgressDisplay::instance () static
Definition at line 87 of file CliProgress.cxx.
References m_instance, and ProgressDisplay().
Referenced by progressFinished(), setActivity(), setGraph(), setImageF(), setImageG(), setImageRGB(), setProgress(), and setStatus().
void impl_cliprogress::ProgressDisplay::setActivity (std::string str)
Definition at line 118 of file CliProgress.cxx.
References m_stream.
Referenced by setActivity().
void impl_cliprogress::ProgressDisplay::setFinished ()
Definition at line 125 of file CliProgress.cxx.
References m_stream.
Referenced by progressFinished().
void impl_cliprogress::ProgressDisplay::setGraph (std::string name, float x, float y)
Definition at line 110 of file CliProgress.cxx.
References m_stream.
Referenced by setGraph().
void impl_cliprogress::ProgressDisplay::setImageF (std::string name, int width, int height, const float * data)
Definition at line 152 of file CliProgress.cxx.
References impl_cliprogress::encodeblock(), and m_stream.
Referenced by setImageF().
void impl_cliprogress::ProgressDisplay::setImageG (std::string name, int width, int height, const char * data)
Definition at line 134 of file CliProgress.cxx.
References impl_cliprogress::encodeblock(), and m_stream.
Referenced by setImageG().
void impl_cliprogress::ProgressDisplay::setImageRGB (std::string name, int width, int height, const char * data)
Definition at line 171 of file CliProgress.cxx.
References impl_cliprogress::encodeblock(), and m_stream.
Referenced by setImageRGB().
void impl_cliprogress::ProgressDisplay::setProgress (std::string name, float cur, float max)
Definition at line 94 of file CliProgress.cxx.
References m_stream.
Referenced by setProgress().
void impl_cliprogress::ProgressDisplay::setStatus (std::string name)
Definition at line 102 of file CliProgress.cxx.
References m_stream.
Referenced by setStatus().
Member Data Documentation
ProgressDisplay * impl_cliprogress::ProgressDisplay::m_instance = 0 static protected
Definition at line 49 of file CliProgress.h.
Referenced by instance(), and ProgressDisplay().
std::ostream* impl_cliprogress::ProgressDisplay::m_stream protected
Definition at line 48 of file CliProgress.h.
Referenced by ProgressDisplay(), setActivity(), setFinished(), setGraph(), setImageF(), setImageG(), setImageRGB(), setProgress(), and setStatus().
The documentation for this class was generated from the following files:
CliProgress.h
CliProgress.cxx