ANIMA: anima::DTINonCentralChiEstimationImageFilter< PixelScalarType > Class Template Reference
anima::DTINonCentralChiEstimationImageFilter< PixelScalarType > Class Template Reference
#include <animaDTINonCentralChiEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::Image
< PixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef itk::Image
< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage
< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
DTINonCentralChiEstimationImageFilter
< PixelScalarType > Self
typedef
anima::MaskedImageToImageFilter
< InputImageType,
OutputImageType > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef RegionSplitterType::Pointer RegionSplitterPointer
typedef
anima::ImageRegionSplitterMask
< MaskImageType > RegionSplitterType
typedef MaskedImageToImageFilter Self
typedef
itk::ImageToImageFilter
< itk::Image< PixelScalarType, 3 >
, itk::VectorImage
< PixelScalarType, 3 > > Superclass
Public Member Functions
void AddGradientDirection (unsigned int i, std::vector< float > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual InputImageType * GetEffectiveCoilsImage ()
virtual InputImageType * GetLocalVarianceImage ()
virtual const char * GetNameOfClass () const
virtual void SetB0Index (unsigned int _arg)
virtual void SetB0Threshold (double _arg)
virtual void SetBFGSStopThreshold (double _arg)
void SetBValuesList (std::vector< float > bValuesList)
virtual void SetEulerMascheroniConstant (double _arg)
virtual void SetInitialDTIImage (OutputImagePointer _arg)
virtual void SetInitialEstimatedB0Image (InputImagePointer _arg)
void SetInputsFrom4DImage (Image4DType *in4DImage)
virtual void SetMaximumNumberOfBFGSIterations (unsigned int _arg)
virtual void SetMaximumNumberOfIterations (unsigned int _arg)
virtual void SetNumberOfCoils (unsigned int _arg)
virtual void SetOptimizeB0Value (bool _arg)
virtual void SetPValueThreshold (double _arg)
virtual void SetRemoveDegeneratedTensors (bool _arg)
virtual void SetStopThreshold (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetActualNumberOfThreads ()
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData (void)
double ComputeLocalSigma (unsigned int nbCoils, double oldLocalSigma, double b0Value, std::vector< double > &dtiValue, std::vector< double > &dwi)
DTINonCentralChiEstimationImageFilter ()
void GenerateOutputInformation (void)
void InitializeFromData (bool keepMask)
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~DTINonCentralChiEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
virtual const
itk::ImageRegionSplitterBase * GetImageRegionSplitter (void) const
void InitializeComputationRegionFromMask ()
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual ~MaskedImageToImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >
Definition at line 11 of file animaDTINonCentralChiEstimationImageFilter.h.
Member Typedef Documentation
template<class PixelScalarType > typedef itk::SmartPointer<const Self> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::ConstPointer
Definition at line 22 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::Image<PixelScalarType,4> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::Image4DType
Definition at line 18 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef InputImageType::Pointer anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::InputImagePointer
Image typedef support
Definition at line 28 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::InputImageRegionType anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::InputImageRegionType
Superclass typedefs.
Definition at line 35 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::Image<PixelScalarType,3> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::InputImageType
Definition at line 17 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::MaskImageType anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::MaskImageType
Definition at line 37 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef OutputImageType::Pointer anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 32 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::OutputImageRegionType anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 36 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::VectorImage<PixelScalarType,3> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::OutputImageType
Definition at line 19 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::SmartPointer<Self> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::Pointer
Definition at line 21 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef DTINonCentralChiEstimationImageFilter<PixelScalarType> anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 16 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::Superclass
Definition at line 20 of file animaDTINonCentralChiEstimationImageFilter.h.
Constructor & Destructor Documentation
template<class PixelScalarType > anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::DTINonCentralChiEstimationImageFilter () inline protected
Definition at line 69 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > virtual anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::~DTINonCentralChiEstimationImageFilter () inline protected virtual
Definition at line 94 of file animaDTINonCentralChiEstimationImageFilter.h.
Member Function Documentation
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::AddGradientDirection (unsigned int i, std::vector< float > & grad)
Definition at line 23 of file animaDTINonCentralChiEstimationImageFilter.hxx.
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 109 of file animaDTINonCentralChiEstimationImageFilter.hxx.
template<class PixelScalarType > double anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::ComputeLocalSigma (unsigned int nbCoils, double oldLocalSigma, double b0Value, std::vector< double > & dtiValue, std::vector< double > & dwi) protected
Definition at line 538 of file animaDTINonCentralChiEstimationImageFilter.hxx.
References anima::bessel_ratio_i().
template<class PixelScalarType > virtual::itk::LightObject::Pointer anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::CreateAnother (void) const
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::GenerateOutputInformation (void) protected
Definition at line 95 of file animaDTINonCentralChiEstimationImageFilter.hxx.
template<class PixelScalarType > virtual InputImageType* anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::GetEffectiveCoilsImage () virtual
template<class PixelScalarType > virtual InputImageType* anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::GetLocalVarianceImage () virtual
template<class PixelScalarType > virtual const char* anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::InitializeFromData (bool keepMask) protected
Definition at line 214 of file animaDTINonCentralChiEstimationImageFilter.hxx.
template<class PixelScalarType > static Pointer anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 100 of file animaDTINonCentralChiEstimationImageFilter.h.
References anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::PrintSelf().
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetB0Index (unsigned int _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetB0Threshold (double _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetBFGSStopThreshold (double _arg) virtual
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetBValuesList (std::vector< float > bValuesList) inline
Definition at line 43 of file animaDTINonCentralChiEstimationImageFilter.h.
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetEulerMascheroniConstant (double _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetInitialDTIImage (OutputImagePointer _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetInitialEstimatedB0Image (InputImagePointer _arg) virtual
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetInputsFrom4DImage (Image4DType * in4DImage)
Definition at line 36 of file animaDTINonCentralChiEstimationImageFilter.hxx.
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetMaximumNumberOfBFGSIterations (unsigned int _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetMaximumNumberOfIterations (unsigned int _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetNumberOfCoils (unsigned int _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetOptimizeB0Value (bool _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetPValueThreshold (double _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetRemoveDegeneratedTensors (bool _arg) virtual
template<class PixelScalarType > virtual void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::SetStopThreshold (double _arg) virtual
template<class PixelScalarType > void anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 287 of file animaDTINonCentralChiEstimationImageFilter.hxx.
References anima::DTINonCentralChiCostFunction::New().
The documentation for this class was generated from the following files:
animaDTINonCentralChiEstimationImageFilter.h
animaDTINonCentralChiEstimationImageFilter.hxx