ANIMA: anima::DDITestAveragingOnRealValueImageFilter Class Reference
anima::DDITestAveragingOnRealValueImageFilter Class Reference
#include <animaDDITestAveragingOnRealValueImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InputImageType::ConstPointer InputImagePointer
typedef itk::VectorImage
< double, 3 > InputImageType
typedef InputImageType::IndexType InputIndexType
typedef
itk::ImageRegionConstIterator
< InputImageType > InputIteratorType
typedef InputImageType::RegionType InputRegionType
typedef OutputImageType::Pointer OutputImagePointer
typedef itk::VectorImage
< double, 3 > OutputImageType
typedef
itk::ImageRegionIterator
< OutputImageType > OutputIteratorType
typedef InputImageType::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef
DDITestAveragingOnRealValueImageFilter Self
typedef
itk::ImageToImageFilter
< InputImageType,
OutputImageType > SuperClass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DDITestAveragingOnRealValueImageFilter ()
virtual const char * GetNameOfClass () const
virtual void SetMethod (int _arg)
virtual void SetStep (int _arg)
virtual ~DDITestAveragingOnRealValueImageFilter ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void ThreadedGenerateData (const InputRegionType &region, itk::ThreadIdType threadId)
Detailed Description
Definition at line 10 of file animaDDITestAveragingOnRealValueImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::DDITestAveragingOnRealValueImageFilter::ConstPointer
Definition at line 21 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef InputImageType::ConstPointer anima::DDITestAveragingOnRealValueImageFilter::InputImagePointer
Definition at line 27 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::VectorImage<double, 3> anima::DDITestAveragingOnRealValueImageFilter::InputImageType
Definition at line 17 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef InputImageType::IndexType anima::DDITestAveragingOnRealValueImageFilter::InputIndexType
Definition at line 33 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::ImageRegionConstIterator<InputImageType> anima::DDITestAveragingOnRealValueImageFilter::InputIteratorType
Definition at line 36 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef InputImageType::RegionType anima::DDITestAveragingOnRealValueImageFilter::InputRegionType
Definition at line 32 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef OutputImageType::Pointer anima::DDITestAveragingOnRealValueImageFilter::OutputImagePointer
Definition at line 30 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::VectorImage<double, 3> anima::DDITestAveragingOnRealValueImageFilter::OutputImageType
Definition at line 18 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::ImageRegionIterator<OutputImageType> anima::DDITestAveragingOnRealValueImageFilter::OutputIteratorType
Definition at line 37 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef InputImageType::PixelType anima::DDITestAveragingOnRealValueImageFilter::PixelType
Definition at line 34 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::SmartPointer<Self> anima::DDITestAveragingOnRealValueImageFilter::Pointer
Definition at line 20 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef DDITestAveragingOnRealValueImageFilter anima::DDITestAveragingOnRealValueImageFilter::Self
Standard class type def
Definition at line 16 of file animaDDITestAveragingOnRealValueImageFilter.h.
typedef itk::ImageToImageFilter<InputImageType, OutputImageType > anima::DDITestAveragingOnRealValueImageFilter::SuperClass
Definition at line 19 of file animaDDITestAveragingOnRealValueImageFilter.h.
Constructor & Destructor Documentation
anima::DDITestAveragingOnRealValueImageFilter::DDITestAveragingOnRealValueImageFilter () inline
Definition at line 42 of file animaDDITestAveragingOnRealValueImageFilter.h.
virtual anima::DDITestAveragingOnRealValueImageFilter::~DDITestAveragingOnRealValueImageFilter () inline virtual
Definition at line 46 of file animaDDITestAveragingOnRealValueImageFilter.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::DDITestAveragingOnRealValueImageFilter::CreateAnother (void) const
virtual const char* anima::DDITestAveragingOnRealValueImageFilter::GetNameOfClass () const virtual
Run-time type information (and related methods)
static Pointer anima::DDITestAveragingOnRealValueImageFilter::New () static
Method for creation through the object factory.
Referenced by main().
virtual void anima::DDITestAveragingOnRealValueImageFilter::SetMethod (int _arg) virtual
virtual void anima::DDITestAveragingOnRealValueImageFilter::SetStep (int _arg) virtual
void anima::DDITestAveragingOnRealValueImageFilter::ThreadedGenerateData (const InputRegionType & region, itk::ThreadIdType threadId) protected
Definition at line 11 of file animaDDITestAveragingOnRealValueImageFilter.hxx.
References anima::CompartmentSize, anima::ComputeDistanceMatrixBetweenFascicles(), anima::ComputeVoxelWeights(), anima::DDIAveraging(), anima::FreeWaterDDIAveraging(), anima::SpectralClusteringFilter< ScalarType >::GetClassesMembership(), anima::RemoveNullFascicles(), anima::SpectralClusteringFilter< ScalarType >::SetInputData(), anima::SpectralClusteringFilter< ScalarType >::SetNbClass(), anima::SpectralClusteringFilter< ScalarType >::SetVerbose(), anima::SpectralClusteringFilter< ScalarType >::Update(), and anima::WIndex.
The documentation for this class was generated from the following files:
animaDDITestAveragingOnRealValueImageFilter.h
animaDDITestAveragingOnRealValueImageFilter.hxx