ANIMA: anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage > Class Template Reference
anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage > Class Template Reference
#include <animaKissingSymmetricBlockMatchingRegistrationMethod.h>
Public Types
typedef
Superclass::AffineTransformType AffineTransformType
typedef Superclass::AgregatorType AgregatorType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::ImageIndexType ImageIndexType
typedef Superclass::ImageRegionType ImageRegionType
typedef InitializerType::Pointer InitializerPointer
typedef
anima::BlockMatchingInitializer
< InputPixelType,
TInputImage::ImageDimension > InitializerType
typedef Superclass::InputImageType InputImageType
typedef TInputImage::PixelType InputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef
KissingSymmetricBlockMatchingRegistrationMethod Self
typedef
BlockMatchingBaseRegistrationMethod
< TInputImage > Superclass
typedef
Superclass::SVFTransformType SVFTransformType
typedef
Superclass::ThreadedMatchData ThreadedMatchData
typedef
Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BlockMatchingBaseRegistrationMethod< TInputImage >
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImage::ImageDimension > AffineTransformType
typedef BaseTransformAgregator
< InputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MetricType::TransformType BaseTransformType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::DataObject::Pointer DataObjectPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > DisplacementFieldTransformType
typedef InputImageType::IndexType ImageIndexType
typedef InputImageType::RegionType ImageRegionType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
MetricType::InterpolatorType InterpolatorType
typedef MetricType::Pointer MetricPointer
typedef
itk::ImageToImageMetric
< InputImageType,
InputImageType > MetricType
enum OptimizerDefinition {
Exhaustive,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef
MetricType::TransformParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef
BlockMatchingBaseRegistrationMethod Self
enum SimilarityDefinition {
MeanSquares,
Correlation,
SquaredCorrelation
}
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > SVFTransformType
enum TransformationDefinition {
Translation,
Rigid,
Affine
}
typedef
TransformOutputType::ConstPointer TransformOutputConstPointer
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetBlockPercentageKept (double _arg)
virtual void SetBlockScalarVarianceThreshold (double _arg)
virtual void SetBlockSize (unsigned int _arg)
virtual void SetBlockSpacing (unsigned int _arg)
virtual void SetDamDistance (double _arg)
virtual void SetUseTransformationDam (bool _arg)
Public Member Functions inherited from anima::BlockMatchingBaseRegistrationMethod< TInputImage >
void Abort (void)
virtual AgregatorType * GetAgregator ()
virtual const double & GetAngleMax () const
BaseInputTransformType::Pointer GetBaseTransformPointer (unsigned int i)
std::vector< typename
BaseInputTransformType::Pointer > & GetBaseTransformsPointers ()
std::vector< ImageRegionType > & GetBlockRegions ()
std::vector< double > & GetBlockWeights ()
virtual const double & GetFinalRadius () const
virtual InputImageType * GetFixedImage ()
virtual const vnl_matrix
< double > & GetGeometry () const
virtual const bool & GetMaximizeMetric () const
virtual const unsigned int & GetMaximumIterations () const
virtual SimilarityDefinition GetMetricKind () const
virtual const double & GetMinimalTransformError () const
virtual InputImageType * GetMovingImage ()
itk::ModifiedTimeType GetMTime () const
virtual OptimizerDefinition GetOptimizerKind () const
virtual const unsigned int & GetOptimizerMaximumIterations () const
TransformOutputType * GetOutput ()
virtual const double & GetScaleMax () const
virtual const double & GetSearchAngleRadius () const
virtual const double & GetSearchRadius () const
virtual const double & GetSearchScaleRadius () const
virtual const double & GetSearchSkewRadius () const
virtual const double & GetSkewMax () const
virtual const double & GetStepSize () const
const std::string GetStopConditionDescription () const
virtual const double & GetSVFElasticRegSigma () const
virtual TransformationDefinition GetTransformKind () const
virtual const double & GetTranslateMax () const
virtual void Initialize () throw (itk::ExceptionObject)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetAngleMax (double _arg)
void SetBaseTransform (unsigned int i, BaseInputTransformType *trsf)
void SetBlockRegions (std::vector< ImageRegionType > &origins)
virtual void SetFinalRadius (double _arg)
void SetFixedImage (InputImageType *fixedImage)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMetricKind (const SimilarityDefinition _arg)
virtual void SetMinimalTransformError (double _arg)
void SetMovingImage (InputImageType *movingImage)
virtual void SetOptimizerKind (const OptimizerDefinition _arg)
virtual void SetOptimizerMaximumIterations (unsigned int _arg)
virtual void SetScaleMax (double _arg)
virtual void SetSearchAngleRadius (double _arg)
virtual void SetSearchRadius (double _arg)
virtual void SetSearchScaleRadius (double _arg)
virtual void SetSearchSkewRadius (double _arg)
virtual void SetSkewMax (double _arg)
virtual void SetStepSize (double _arg)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetTransformKind (const TransformationDefinition _arg)
virtual void SetTranslateMax (double _arg)
void StartOptimization (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void InitializeBlocksOnImage (InitializerPointer &initPtr, InputImageType *image)
KissingSymmetricBlockMatchingRegistrationMethod ()
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)
virtual ~KissingSymmetricBlockMatchingRegistrationMethod ()
Protected Member Functions inherited from anima::BlockMatchingBaseRegistrationMethod< TInputImage >
virtual void AdditionalBlockMatchingSetup (MetricPointer &metric, unsigned int blockNum)
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
void BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType *fixedImage, InputImageType *resampledImage)
BlockMatchingBaseRegistrationMethod ()
virtual bool ComposeAddOnWithTransform (TransformType *computedTransform, TransformType *addOn)
void GenerateData ()
virtual void GlobalParametersSetup ()
Setting global parameters that don't need to be changed for each block or iteration.
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &floatingImage)
virtual void SetupBlockParameters (InterpolatorPointer &interpolator, MetricPointer &metric, OptimizerPointer &optimizer, unsigned startBlock, unsigned endBlock)
Setting block related parameters that need to be changed for each block or iteration.
virtual void SetupTransform (TransformPointer &optimizedTransform)
virtual ~BlockMatchingBaseRegistrationMethod ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::BlockMatchingBaseRegistrationMethod< TInputImage >
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImage>
class anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >
Definition at line 10 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImage > typedef Superclass::AffineTransformType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::AffineTransformType
Definition at line 25 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::AgregatorType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::AgregatorType
Definition at line 27 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef itk::SmartPointer<const Self> anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::ConstPointer
Definition at line 17 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ImageIndexType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::ImageIndexType
Definition at line 23 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ImageRegionType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::ImageRegionType
Definition at line 24 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef InitializerType::Pointer anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::InitializerPointer
Definition at line 31 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef anima::BlockMatchingInitializer<InputPixelType,TInputImage::ImageDimension> anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::InitializerType
Definition at line 30 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::InputImageType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::InputImageType
Definition at line 19 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef TInputImage::PixelType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::InputPixelType
Definition at line 29 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef itk::SmartPointer<Self> anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::Pointer
Definition at line 16 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef KissingSymmetricBlockMatchingRegistrationMethod anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::Self
Standard class typedefs.
Definition at line 14 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef BlockMatchingBaseRegistrationMethod<TInputImage> anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::Superclass
Definition at line 15 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::SVFTransformType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SVFTransformType
Definition at line 26 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::ThreadedMatchData anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::ThreadedMatchData
Definition at line 22 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::TransformPointer anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::TransformPointer
Definition at line 21 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
template<typename TInputImage > typedef Superclass::TransformType anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::TransformType
Definition at line 20 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::KissingSymmetricBlockMatchingRegistrationMethod () protected
Constructor
Definition at line 17 of file animaKissingSymmetricBlockMatchingRegistrationMethod.hxx.
template<typename TInputImage > virtual anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::~KissingSymmetricBlockMatchingRegistrationMethod () inline protected virtual
Definition at line 49 of file animaKissingSymmetricBlockMatchingRegistrationMethod.h.
Member Function Documentation
template<typename TInputImage > virtual::itk::LightObject::Pointer anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::CreateAnother (void) const
template<typename TInputImage > virtual const char* anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BlockMatchingBaseRegistrationMethod< TInputImage >.
template<typename TInputImage > void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::InitializeBlocksOnImage (InitializerPointer & initPtr, InputImageType * image) protected
Definition at line 30 of file animaKissingSymmetricBlockMatchingRegistrationMethod.hxx.
template<typename TInputImage > static Pointer anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::New () static
Method for creation through the object factory.
template<typename TInputImage > void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected virtual
Implements anima::BlockMatchingBaseRegistrationMethod< TInputImage >.
Definition at line 56 of file animaKissingSymmetricBlockMatchingRegistrationMethod.hxx.
References anima::GetExponential(), anima::GetLogarithm(), anima::DenseSVFTransformAgregator< NDimensions >::SetDamIndexes(), and anima::BalooSVFTransformAgregator< NDimensions >::SetDamIndexes().
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetBlockPercentageKept (double _arg) virtual
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetBlockScalarVarianceThreshold (double _arg) virtual
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetBlockSize (unsigned int _arg) virtual
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetBlockSpacing (unsigned int _arg) virtual
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetDamDistance (double _arg) virtual
template<typename TInputImage > virtual void anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::SetUseTransformationDam (bool _arg) virtual
The documentation for this class was generated from the following files:
animaKissingSymmetricBlockMatchingRegistrationMethod.h
animaKissingSymmetricBlockMatchingRegistrationMethod.hxx