ANIMA: anima::DDIModelEstimatorImageFilter< PixelScalarType > Class Template Reference
anima::DDIModelEstimatorImageFilter< PixelScalarType > Class Template Reference
#include <animaDDIModelEstimatorImageFilter.h>
Classes
class KappaUpperBoundSolverCostFunction
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::VectorImage
< PixelScalarType, 3 > GradientTensorImageType
typedef vnl_vector_fixed
< double, 3 > GradientType
typedef itk::Image
< PixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef itk::Image
< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef itk::VectorImage
< PixelScalarType, 3 > ModelImageType
typedef anima::NLOPTOptimizers OptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage
< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
DDIModelEstimatorImageFilter
< PixelScalarType > Self
typedef
anima::MaskedImageToImageFilter
< InputImageType,
OutputImageType > Superclass
typedef itk::DiffusionTensor3D
< double > TensorPixelType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef RegionSplitterType::Pointer RegionSplitterPointer
typedef
anima::ImageRegionSplitterMask
< MaskImageType > RegionSplitterType
typedef MaskedImageToImageFilter Self
typedef
itk::ImageToImageFilter
< itk::Image< PixelScalarType, 3 >
, itk::VectorImage
< PixelScalarType, 3 > > Superclass
Public Member Functions
void AddGradientDirection (unsigned int i, GradientType &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
InputImageType * GetAICcVolume ()
MaskImageType * GetMaskForDiffComputation ()
virtual const char * GetNameOfClass () const
Image4DType * GetOutputAs4DImage ()
virtual void SetAbsoluteCostChange (double _arg)
virtual void SetB0Threshold (double _arg)
void SetBValuesList (std::vector< double > &mb)
virtual void SetCommonDiff (bool _arg)
virtual void SetCommonEAF (bool _arg)
virtual void SetCommonKappa (bool _arg)
virtual void SetCommonVolFrac (bool _arg)
virtual void SetEAFVal (double _arg)
virtual void SetEstimateDiff (bool _arg)
virtual void SetEstimateEAF (bool _arg)
virtual void SetEstimateFreeDiff (bool _arg)
virtual void SetEstimateKappa (bool _arg)
virtual void SetEstimateVolFrac (bool _arg)
virtual void SetFixedDiffInit (bool _arg)
void SetGradientTensorImage (GradientTensorImageType *image)
virtual void SetInitialImage (typename ModelImageType::Pointer _arg)
virtual void SetMaxEval (unsigned int _arg)
virtual void SetNumberOfCompartments (unsigned int _arg)
virtual void SetNumberOfRandomRestarts (unsigned int _arg)
void SetOptimizer (std::string &opt)
virtual void SetVolFracVal (double _arg)
void SetWeightMap (InputImageType *image)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetActualNumberOfThreads ()
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData (void)
void CheckComputationMask ()
DDIModelEstimatorImageFilter ()
void GenerateOutputInformation (void)
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~DDIModelEstimatorImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual const
itk::ImageRegionSplitterBase * GetImageRegionSplitter (void) const
void InitializeComputationRegionFromMask ()
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual ~MaskedImageToImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::DDIModelEstimatorImageFilter< PixelScalarType >
Definition at line 19 of file animaDDIModelEstimatorImageFilter.h.
Member Typedef Documentation
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::DDIModelEstimatorImageFilter< PixelScalarType >::ConstPointer
Definition at line 32 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DDIModelEstimatorImageFilter< PixelScalarType >::GradientTensorImageType
Definition at line 30 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef vnl_vector_fixed<double,3> anima::DDIModelEstimatorImageFilter< PixelScalarType >::GradientType
Definition at line 49 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::Image<PixelScalarType,4> anima::DDIModelEstimatorImageFilter< PixelScalarType >::Image4DType
Definition at line 28 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef InputImageType::Pointer anima::DDIModelEstimatorImageFilter< PixelScalarType >::InputImagePointer
Image typedef support
Definition at line 38 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef Superclass::InputImageRegionType anima::DDIModelEstimatorImageFilter< PixelScalarType >::InputImageRegionType
Definition at line 46 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::Image<PixelScalarType,3> anima::DDIModelEstimatorImageFilter< PixelScalarType >::InputImageType
Definition at line 25 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef Superclass::MaskImageType anima::DDIModelEstimatorImageFilter< PixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 45 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DDIModelEstimatorImageFilter< PixelScalarType >::ModelImageType
Definition at line 27 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef anima::NLOPTOptimizers anima::DDIModelEstimatorImageFilter< PixelScalarType >::OptimizerType
Definition at line 51 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef OutputImageType::Pointer anima::DDIModelEstimatorImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 42 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::DDIModelEstimatorImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 47 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DDIModelEstimatorImageFilter< PixelScalarType >::OutputImageType
Definition at line 26 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::DDIModelEstimatorImageFilter< PixelScalarType >::Pointer
Definition at line 31 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef DDIModelEstimatorImageFilter<PixelScalarType> anima::DDIModelEstimatorImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 24 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::DDIModelEstimatorImageFilter< PixelScalarType >::Superclass
Definition at line 29 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> typedef itk::DiffusionTensor3D<double> anima::DDIModelEstimatorImageFilter< PixelScalarType >::TensorPixelType
Definition at line 50 of file animaDDIModelEstimatorImageFilter.h.
Constructor & Destructor Documentation
template<class PixelScalarType> anima::DDIModelEstimatorImageFilter< PixelScalarType >::DDIModelEstimatorImageFilter () inline protected
Definition at line 94 of file animaDDIModelEstimatorImageFilter.h.
References anima::CompartmentSize.
template<class PixelScalarType> virtual anima::DDIModelEstimatorImageFilter< PixelScalarType >::~DDIModelEstimatorImageFilter () inline protected virtual
Definition at line 138 of file animaDDIModelEstimatorImageFilter.h.
Member Function Documentation
template<class PixelScalarType > void anima::DDIModelEstimatorImageFilter< PixelScalarType >::AddGradientDirection (unsigned int i, GradientType & grad)
Definition at line 50 of file animaDDIModelEstimatorImageFilter.hxx.
template<class PixelScalarType > void anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 181 of file animaDDIModelEstimatorImageFilter.hxx.
References anima::AIndex, anima::DIndex, anima::GetFascicleFA(), anima::GetVoxelFA(), anima::KappaIndex, anima::DDIModelEstimatorImageFilter< PixelScalarType >::KappaUpperBoundSolverCostFunction::SetWMAxialDiffusivity(), anima::DDIModelEstimatorImageFilter< PixelScalarType >::KappaUpperBoundSolverCostFunction::SetWMRadialDiffusivity(), anima::WIndex, and anima::xi().
template<class PixelScalarType > void anima::DDIModelEstimatorImageFilter< PixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 144 of file animaDDIModelEstimatorImageFilter.hxx.
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::DDIModelEstimatorImageFilter< PixelScalarType >::CreateAnother (void) const
template<class PixelScalarType > void anima::DDIModelEstimatorImageFilter< PixelScalarType >::GenerateOutputInformation (void) protected
Definition at line 63 of file animaDDIModelEstimatorImageFilter.hxx.
template<class PixelScalarType> InputImageType* anima::DDIModelEstimatorImageFilter< PixelScalarType >::GetAICcVolume () inline
Definition at line 89 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> MaskImageType* anima::DDIModelEstimatorImageFilter< PixelScalarType >::GetMaskForDiffComputation () inline
Definition at line 90 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> virtual const char* anima::DDIModelEstimatorImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
template<class PixelScalarType > DDIModelEstimatorImageFilter< PixelScalarType >::Image4DType * anima::DDIModelEstimatorImageFilter< PixelScalarType >::GetOutputAs4DImage ()
Definition at line 77 of file animaDDIModelEstimatorImageFilter.hxx.
template<class PixelScalarType> static Pointer anima::DDIModelEstimatorImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
template<class PixelScalarType> void anima::DDIModelEstimatorImageFilter< PixelScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 146 of file animaDDIModelEstimatorImageFilter.h.
References anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::PrintSelf().
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetAbsoluteCostChange (double _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetB0Threshold (double _arg) virtual
template<class PixelScalarType> void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetBValuesList (std::vector< double > & mb) inline
Definition at line 54 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetCommonDiff (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetCommonEAF (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetCommonKappa (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetCommonVolFrac (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEAFVal (double _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEstimateDiff (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEstimateEAF (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEstimateFreeDiff (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEstimateKappa (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetEstimateVolFrac (bool _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetFixedDiffInit (bool _arg) virtual
template<class PixelScalarType> void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetGradientTensorImage (GradientTensorImageType * image) inline
Definition at line 57 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetInitialImage (typename ModelImageType::Pointer _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetMaxEval (unsigned int _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetNumberOfCompartments (unsigned int _arg) virtual
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetNumberOfRandomRestarts (unsigned int _arg) virtual
template<class PixelScalarType> void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetOptimizer (std::string & opt) inline
Definition at line 61 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType> virtual void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetVolFracVal (double _arg) virtual
template<class PixelScalarType> void anima::DDIModelEstimatorImageFilter< PixelScalarType >::SetWeightMap (InputImageType * image) inline
Definition at line 86 of file animaDDIModelEstimatorImageFilter.h.
template<class PixelScalarType > void anima::DDIModelEstimatorImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 461 of file animaDDIModelEstimatorImageFilter.hxx.
References anima::AIndex, anima::DIndex, anima::KappaIndex, anima::DDICostFunction::New(), anima::TransformSphericalToCartesianCoordinates(), anima::WIndex, and anima::xi().
The documentation for this class was generated from the following files:
animaDDIModelEstimatorImageFilter.h
animaDDIModelEstimatorImageFilter.hxx