ANIMA: anima::DTINonCentralChiCostFunction Class Reference
anima::DTINonCentralChiCostFunction Class Reference
#include <animaDTINonCentralChiCostFunction.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef
DTINonCentralChiCostFunction Self
typedef SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const
virtual MeasureType GetValue (const ParametersType &parameters) const
virtual void SetB0Value (double _arg)
virtual void SetDesignMatrix (vnl_matrix< double > _arg)
virtual void SetNumberOfCoils (unsigned int _arg)
virtual void SetNumberOfParameters (unsigned int _arg)
void SetRawSignal (std::vector< double > rawSignal)
virtual void SetSigma (double _arg)
virtual void SetUseB0Value (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
DTINonCentralChiCostFunction ()
virtual ~DTINonCentralChiCostFunction ()
Detailed Description
Definition at line 10 of file animaDTINonCentralChiCostFunction.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::DTINonCentralChiCostFunction::ConstPointer
Definition at line 18 of file animaDTINonCentralChiCostFunction.h.
typedef Superclass::DerivativeType anima::DTINonCentralChiCostFunction::DerivativeType
Definition at line 26 of file animaDTINonCentralChiCostFunction.h.
typedef Superclass::MeasureType anima::DTINonCentralChiCostFunction::MeasureType
Definition at line 23 of file animaDTINonCentralChiCostFunction.h.
typedef Superclass::ParametersType anima::DTINonCentralChiCostFunction::ParametersType
Definition at line 27 of file animaDTINonCentralChiCostFunction.h.
typedef itk::SmartPointer<Self> anima::DTINonCentralChiCostFunction::Pointer
Definition at line 17 of file animaDTINonCentralChiCostFunction.h.
typedef DTINonCentralChiCostFunction anima::DTINonCentralChiCostFunction::Self
Standard class typedefs.
Definition at line 15 of file animaDTINonCentralChiCostFunction.h.
typedef SingleValuedCostFunction anima::DTINonCentralChiCostFunction::Superclass
Definition at line 16 of file animaDTINonCentralChiCostFunction.h.
Constructor & Destructor Documentation
anima::DTINonCentralChiCostFunction::DTINonCentralChiCostFunction () protected
Definition at line 6 of file animaDTINonCentralChiCostFunction.cxx.
virtual anima::DTINonCentralChiCostFunction::~DTINonCentralChiCostFunction () inline protected virtual
Definition at line 52 of file animaDTINonCentralChiCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::DTINonCentralChiCostFunction::CreateAnother (void) const
void anima::DTINonCentralChiCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 49 of file animaDTINonCentralChiCostFunction.cxx.
References anima::bessel_ratio_i().
virtual const char* anima::DTINonCentralChiCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
unsigned int anima::DTINonCentralChiCostFunction::GetNumberOfParameters () const inline
Definition at line 44 of file animaDTINonCentralChiCostFunction.h.
DTINonCentralChiCostFunction::MeasureType anima::DTINonCentralChiCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 16 of file animaDTINonCentralChiCostFunction.cxx.
References anima::log_bessel_i().
static Pointer anima::DTINonCentralChiCostFunction::New () static
Referenced by anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::ThreadedGenerateData().
virtual void anima::DTINonCentralChiCostFunction::SetB0Value (double _arg) virtual
virtual void anima::DTINonCentralChiCostFunction::SetDesignMatrix (vnl_matrix< double > _arg) virtual
virtual void anima::DTINonCentralChiCostFunction::SetNumberOfCoils (unsigned int _arg) virtual
virtual void anima::DTINonCentralChiCostFunction::SetNumberOfParameters (unsigned int _arg) virtual
void anima::DTINonCentralChiCostFunction::SetRawSignal (std::vector< double > rawSignal) inline
Definition at line 34 of file animaDTINonCentralChiCostFunction.h.
virtual void anima::DTINonCentralChiCostFunction::SetSigma (double _arg) virtual
virtual void anima::DTINonCentralChiCostFunction::SetUseB0Value (bool _arg) virtual
The documentation for this class was generated from the following files:
animaDTINonCentralChiCostFunction.h
animaDTINonCentralChiCostFunction.cxx