ANIMA: anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage > Class Template Reference
anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage > Class Template Reference abstract
#include <animaTensorBlockMatchingBaseRegistrationMethod.h>
Classes
struct ThreadedMatchData
Public Types
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImage::ImageDimension > AffineTransformType
typedef BaseTransformAgregator
< InputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MetricType::TransformType BaseTransformType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::DataObject::Pointer DataObjectPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > DisplacementFieldTransformType
typedef InputImageType::IndexType ImageIndexType
typedef InputImageType::RegionType ImageRegionType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
MetricType::InterpolatorType InterpolatorType
typedef MetricType::Pointer MetricPointer
typedef
anima::BaseTensorImageToImageMetric
< InputImageType,
InputImageType > MetricType
enum OptimizerDefinition {
Exhaustive,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef
MetricType::TransformParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef
TensorBlockMatchingBaseRegistrationMethod Self
enum SimilarityDefinition {
TensorMeanSquares,
TensorCorrelation,
TensorGeneralizedCorrelation,
TensorOrientedGeneralizedCorrelation
}
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > SVFTransformType
enum TransformationDefinition {
Translation,
Rigid,
Affine
}
typedef
TransformOutputType::ConstPointer TransformOutputConstPointer
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual const double & GetAngleMax () const
BaseInputTransformType::Pointer GetBaseTransformPointer (unsigned int i)
std::vector< typename
BaseInputTransformType::Pointer > & GetBaseTransformsPointers ()
std::vector< ImageRegionType > & GetBlockRegions ()
virtual double GetBlockTensorVarianceThreshold ()
std::vector< double > & GetBlockWeights ()
virtual const double & GetFinalRadius () const
virtual InputImageType * GetFixedImage ()
virtual const vnl_matrix
< double > & GetGeometry () const
virtual const bool & GetMaximizeMetric () const
virtual const unsigned int & GetMaximumIterations () const
virtual SimilarityDefinition GetMetricKind () const
virtual const double & GetMinimalTransformError () const
virtual InputImageType * GetMovingImage ()
itk::ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual OptimizerDefinition GetOptimizerKind () const
virtual const unsigned int & GetOptimizerMaximumIterations () const
TransformOutputType * GetOutput ()
virtual const double & GetScaleMax () const
virtual const double & GetSearchAngleRadius () const
virtual const double & GetSearchRadius () const
virtual const double & GetSearchScaleRadius () const
virtual const double & GetSearchSkewRadius () const
virtual const double & GetSkewMax () const
virtual const double & GetStepSize () const
const std::string GetStopConditionDescription () const
virtual const double & GetSVFElasticRegSigma () const
virtual TransformationDefinition GetTransformKind () const
virtual const double & GetTranslateMax () const
virtual void Initialize () throw (itk::ExceptionObject)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetAngleMax (double _arg)
void SetBaseTransform (unsigned int i, BaseInputTransformType *trsf)
void SetBlockRegions (std::vector< ImageRegionType > &origins)
virtual void SetBlockTensorVarianceThreshold (double _arg)
virtual void SetFinalRadius (double _arg)
void SetFixedImage (InputImageType *fixedImage)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMetricKind (const SimilarityDefinition _arg)
virtual void SetMinimalTransformError (double _arg)
void SetMovingImage (InputImageType *movingImage)
virtual void SetOptimizerKind (const OptimizerDefinition _arg)
virtual void SetOptimizerMaximumIterations (unsigned int _arg)
virtual void SetScaleMax (double _arg)
virtual void SetSearchAngleRadius (double _arg)
virtual void SetSearchRadius (double _arg)
virtual void SetSearchScaleRadius (double _arg)
virtual void SetSearchSkewRadius (double _arg)
virtual void SetSkewMax (double _arg)
virtual void SetStepSize (double _arg)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetTransformKind (const TransformationDefinition _arg)
virtual void SetTranslateMax (double _arg)
void StartOptimization (void)
Protected Member Functions
virtual void AdditionalBlockMatchingSetup (MetricPointer &metric, unsigned int blockNum)
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
void BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType *fixedImage, InputImageType *resampledImage)
virtual bool ComposeAddOnWithTransform (TransformType *computedTransform, TransformType *addOn)
void GenerateData ()
virtual void GlobalParametersSetup ()
Setting global parameters that don't need to be changed for each block or iteration.
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)=0
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &floatingImage)
virtual void SetupBlockParameters (InterpolatorPointer &interpolator, MetricPointer &metric, OptimizerPointer &optimizer, unsigned startBlock, unsigned endBlock)
Setting block related parameters that need to be changed for each block or iteration.
virtual void SetupTransform (TransformPointer &optimizedTransform)
TensorBlockMatchingBaseRegistrationMethod ()
virtual ~TensorBlockMatchingBaseRegistrationMethod ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImage>
class anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >
Definition at line 26 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImage> typedef AffineTransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::AffineTransformPointer
Definition at line 71 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::AffineTransform<typename AgregatorType::ScalarType, TInputImage::ImageDimension> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::AffineTransformType
Type of the initialization transform .
Definition at line 70 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef BaseTransformAgregator<InputImageType::ImageDimension> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::AgregatorType
Type of Transform Agregator
Definition at line 55 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseInputTransformType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BaseInputTransformType
Definition at line 56 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseOutputTransformType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BaseOutputTransformType
Definition at line 57 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef BaseTransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BaseTransformPointer
Definition at line 93 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BaseTransformType
Type of the Transformation parameters This is the same type used to represent the search space of the optimization algorithm
Definition at line 92 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<const Self> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ConstPointer
Definition at line 33 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObject::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::DataObjectPointer
Smart Pointer type to a DataObject.
Definition at line 97 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::ProcessObject::DataObjectPointerArraySizeType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::DataObjectPointerArraySizeType
Make a DataObject of the correct type to be used as the specified output.
Definition at line 205 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef DisplacementFieldTransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::DisplacementFieldTransformPointer
Definition at line 63 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef rpi::DisplacementFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::DisplacementFieldTransformType
Definition at line 62 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::IndexType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ImageIndexType
Definition at line 48 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::RegionType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ImageRegionType
Definition at line 47 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::ConstPointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::InputImageConstPointer
Definition at line 45 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::InputImagePointer
Definition at line 46 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TInputImage anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::InputImageType
Type of the input image (both fixed and moving).
Definition at line 41 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InterpolatorType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::InterpolatorPointer
Definition at line 84 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::InterpolatorType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::InterpolatorType
Type of the Interpolator.
Definition at line 83 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::MetricPointer
Definition at line 52 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef anima::BaseTensorImageToImageMetric<InputImageType, InputImageType> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::MetricType
Type of the metric.
Definition at line 51 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef OptimizerType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::OptimizerPointer
Definition at line 88 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SingleValuedNonLinearOptimizer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::OptimizerType
Type of the optimizer.
Definition at line 87 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformParametersType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ParametersType
Definition at line 94 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<Self> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::Pointer
Definition at line 32 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::PointType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::PointType
Type of points for Setting block origins
Definition at line 74 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TensorBlockMatchingBaseRegistrationMethod anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::Self
Standard class typedefs.
Definition at line 30 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::ProcessObject anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::Superclass
Definition at line 31 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef SVFTransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SVFTransformPointer
Definition at line 61 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::StationaryVelocityFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SVFTransformType
RPI specific types
Definition at line 60 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::ConstPointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputConstPointer
Definition at line 80 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputPointer
Definition at line 79 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObjectDecorator< TransformType > anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputType
Type for the output: Using Decorator pattern for enabling the Transform to be passed in the data pipeline
Definition at line 78 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformPointer
Definition at line 67 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseOutputTransformType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformType
Type of the Transform .
Definition at line 66 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
Member Enumeration Documentation
template<typename TInputImage> enum anima::TensorBlockMatchingBaseRegistrationMethod::OptimizerDefinition
Enumerator
Exhaustive
Bobyqa
Definition at line 37 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> enum anima::TensorBlockMatchingBaseRegistrationMethod::SimilarityDefinition
Enumerator
TensorMeanSquares
TensorCorrelation
TensorGeneralizedCorrelation
TensorOrientedGeneralizedCorrelation
Definition at line 38 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> enum anima::TensorBlockMatchingBaseRegistrationMethod::TransformationDefinition
Enumerator
Translation
Rigid
Affine
Definition at line 36 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TensorBlockMatchingBaseRegistrationMethod () protected
Constructor
Definition at line 35 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::~TensorBlockMatchingBaseRegistrationMethod () inline protected virtual
Definition at line 219 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
Member Function Documentation
template<typename TInputImage> void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::Abort (void) inline
Definition at line 215 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::AdditionalBlockMatchingSetup (MetricPointer & metric, unsigned int blockNum) protected virtual
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
Definition at line 707 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References TensorCorrelation, TensorGeneralizedCorrelation, and TensorOrientedGeneralizedCorrelation.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType * fixedImage, InputImageType * resampledImage) protected
Definition at line 729 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References Bobyqa, Exhaustive, and TensorMeanSquares.
Referenced by anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatching().
template<typename TInputImage > bool anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ComposeAddOnWithTransform (TransformType * computedTransform, TransformType * addOn) protected virtual
Definition at line 328 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References anima::composeSVF().
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GenerateData (void) protected
Method invoked by the pipeline in order to trigger the computation of the registration.
Definition at line 838 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual AgregatorType* anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetAgregator () virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetAngleMax () const virtual
template<typename TInputImage > TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BaseInputTransformType::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetBaseTransformPointer (unsigned int i)
Definition at line 97 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> std::vector<typename BaseInputTransformType::Pointer>& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetBaseTransformsPointers () inline
Definition at line 118 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> std::vector<ImageRegionType>& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockRegions () inline
Definition at line 115 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> virtual double anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockTensorVarianceThreshold () virtual
template<typename TInputImage> std::vector<double>& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockWeights () inline
Definition at line 117 of file animaTensorBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetFinalRadius () const virtual
template<typename TInputImage> virtual InputImageType* anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetFixedImage () virtual
template<typename TInputImage> virtual const vnl_matrix<double>& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetGeometry () const virtual
template<typename TInputImage> virtual const bool& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMaximizeMetric () const virtual
template<typename TInputImage> virtual const unsigned int& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMaximumIterations () const virtual
template<typename TInputImage> virtual SimilarityDefinition anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMetricKind () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMinimalTransformError () const virtual
template<typename TInputImage> virtual InputImageType* anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMovingImage () virtual
template<typename TInputImage > itk::ModifiedTimeType anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetMTime () const
Method to return the latest modified time of this object or any of its cached ivars
Definition at line 71 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const char* anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented in anima::TensorKissingSymmetricBlockMatchingRegistrationMethod< TInputImage >, anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >, and anima::TensorAsymmetricBlockMatchingRegistrationMethod< TInputImage >.
template<typename TInputImage> virtual OptimizerDefinition anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetOptimizerKind () const virtual
template<typename TInputImage> virtual const unsigned int& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetOptimizerMaximumIterations () const virtual
template<typename TInputImage > TensorBlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputType * anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetOutput ()
Returns the transform resulting from the registration process
Get Output
Definition at line 865 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetScaleMax () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchAngleRadius () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchRadius () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchScaleRadius () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchSkewRadius () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSkewMax () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetStepSize () const virtual
template<typename TInputImage > const std::string anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetStopConditionDescription () const
Definition at line 932 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetSVFElasticRegSigma () const virtual
template<typename TInputImage> virtual TransformationDefinition anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetTransformKind () const virtual
template<typename TInputImage> virtual const double& anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GetTranslateMax () const virtual
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::GlobalParametersSetup () protected virtual
Setting global parameters that don't need to be changed for each block or iteration.
Definition at line 401 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Rigid, TensorMeanSquares, and Translation.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::Initialize () throw (itk::ExceptionObject) virtual
Initialize by setting the interconnects between the components.
Initialize by setting the interconnects between components.
Definition at line 120 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > itk::DataObject::Pointer anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::MakeOutput (DataObjectPointerArraySizeType idx) virtual
Definition at line 873 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected pure virtual
Implemented in anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >, anima::TensorKissingSymmetricBlockMatchingRegistrationMethod< TInputImage >, and anima::TensorAsymmetricBlockMatchingRegistrationMethod< TInputImage >.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected virtual
PrintSelf
Definition at line 812 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References Bobyqa, Rigid, and Translation.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ResampleImages (TransformType * currentTransform, InputImagePointer & refImage, InputImagePointer & floatingImage) protected
Definition at line 257 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References anima::GetSVFExponential().
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetAgregator (AgregatorType * _arg) virtual
Set/Get Method for the Agregator
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetAngleMax (double _arg) virtual
Set/Get the upper bound on angles for bobyqa
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetBaseTransform (unsigned int i, BaseInputTransformType * trsf)
Definition at line 108 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetBlockRegions (std::vector< ImageRegionType > & origins)
Set / Get Block Origins
Definition at line 171 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetBlockTensorVarianceThreshold (double _arg) virtual
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetFinalRadius (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetFixedImage (InputImageType * fixedImage)
Set/Get the Fixed image.
Definition at line 889 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetInitialTransform (TransformPointer _arg) virtual
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetMaximumIterations (unsigned int _arg) virtual
Set/Get the maximum number of iterations
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetMetricKind (const SimilarityDefinition _arg) virtual
Set/Get the Metric.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetMinimalTransformError (double _arg) virtual
Set/Get the minimal error over consecutive transformations
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetMovingImage (InputImageType * movingImage)
Set/Get the Moving image.
Definition at line 916 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetOptimizerKind (const OptimizerDefinition _arg) virtual
Set/Get the Optimizer.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetOptimizerMaximumIterations (unsigned int _arg) virtual
Set/Get the maximum number of iterations per block if optimizer called
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetScaleMax (double _arg) virtual
Set/Get the upper bound on scales for bobyqa
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchAngleRadius (double _arg) virtual
Set/Get the search radius specific for angle search (rho start for bobyqa on rigid part)
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchRadius (double _arg) virtual
Set/Get the search radius (exhaustive search window, rho start for bobyqa)
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchScaleRadius (double _arg) virtual
Set/Get the search radius specific for scale search (rho start for bobyqa on affine part)
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchSkewRadius (double _arg) virtual
Set/Get the search radius specific for skew search (rho start for bobyqa on affine part)
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSkewMax (double _arg) virtual
Set/Get the upper bound on skews for bobyqa
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetStepSize (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetSVFElasticRegSigma (double _arg) virtual
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetTransformKind (const TransformationDefinition _arg) virtual
Set/Get the Transform.
template<typename TInputImage> virtual void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetTranslateMax (double _arg) virtual
Set/Get the upper bound on translations for bobyqa
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetupBlockParameters (InterpolatorPointer & interpolator, MetricPointer & metric, OptimizerPointer & optimizer, unsigned startBlock, unsigned endBlock) protected virtual
Setting block related parameters that need to be changed for each block or iteration.
Definition at line 459 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Bobyqa, Exhaustive, Rigid, TensorCorrelation, TensorGeneralizedCorrelation, TensorMeanSquares, TensorOrientedGeneralizedCorrelation, and Translation.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::SetupTransform (TransformPointer & optimizedTransform) protected virtual
Definition at line 139 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > void anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::StartOptimization (void)
Starts the Registration Process
Definition at line 187 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Rigid, and Translation.
template<typename TInputImage > ITK_THREAD_RETURN_TYPE anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatching (void * arg) static protected
Do the matching for a batch of regions (splited according to the thread id + nb threads)
Threaded block match
Definition at line 387 of file animaTensorBlockMatchingBaseRegistrationMethod.hxx.
References anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::BlockMatch, anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::BlockMatch(), anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::fixedImage, and anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::movingImage.
The documentation for this class was generated from the following files:
animaTensorBlockMatchingBaseRegistrationMethod.h
animaTensorBlockMatchingBaseRegistrationMethod.hxx