ANIMA: anima::DistortionCorrectionRegistrationMethod< TInputImage > Class Template Reference
anima::DistortionCorrectionRegistrationMethod< TInputImage > Class Template Reference
#include <animaDistortionCorrectionRegistrationMethod.h>
Classes
struct ThreadedMatchData
Public Types
enum AgregatorDefinition {
Baloo = 0,
MEstimate
}
typedef BaseTransformAgregator
< InputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MetricType::TransformType BaseTransformType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::DataObject::Pointer DataObjectPointer
typedef
ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > DisplacementFieldTransformType
typedef InputImageType::IndexType ImageIndexType
typedef InputImageType::RegionType ImageRegionType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
MetricType::InterpolatorType InterpolatorType
typedef MetricType::Pointer MetricPointer
typedef
itk::ImageToImageMetric
< InputImageType,
InputImageType > MetricType
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef
MetricType::TransformParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef
DistortionCorrectionRegistrationMethod Self
enum SimilarityDefinition {
Correlation = 0,
SquaredCorrelation,
MeanSquares
}
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > SVFTransformType
enum TransformationDefinition {
Direction = 0,
DirectionScale,
DirectionScaleSkew
}
typedef
TransformOutputType::ConstPointer TransformOutputConstPointer
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef
DisplacementFieldTransformType::Pointer TransformPointer
typedef
DisplacementFieldTransformType TransformType
Public Member Functions
void Abort (void)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual AgregatorType * GetAgregator ()
virtual const InputImageType * GetBackwardImage () const
virtual const double & GetFinalRadius () const
virtual const InputImageType * GetForwardImage () const
virtual const ParametersType & GetLastTransformParameters () const
virtual const unsigned & GetMaximumIterations () const
virtual SimilarityDefinition GetMetricKind () const
itk::ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const unsigned & GetOptimizerMaximumIterations () const
TransformOutputType * GetOutput ()
virtual const double & GetScaleMax () const
virtual const double & GetSearchRadius () const
virtual const double & GetSearchScaleRadius () const
virtual const double & GetSearchSkewRadius () const
virtual const double & GetSkewMax () const
virtual const double & GetStepSize () const
const std::string GetStopConditionDescription () const
virtual const double & GetSVFElasticRegSigma () const
virtual TransformationDefinition GetTransformationKind () const
virtual const double & GetTranslateMax () const
virtual const bool & GetWeightedAgregation () const
virtual void Initialize () throw (itk::ExceptionObject)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetAgregatorType (AgregatorDefinition _arg)
void SetBackwardImage (InputImageType *backwardImage)
virtual void SetBlockPercentageKept (double _arg)
virtual void SetBlockScalarVarianceThreshold (double _arg)
virtual void SetBlockSize (unsigned int _arg)
virtual void SetBlockSpacing (unsigned int _arg)
virtual void SetCurrentTransform (TransformPointer _arg)
virtual void SetDamDistance (double _arg)
virtual void SetFinalRadius (double _arg)
void SetForwardImage (InputImageType *forwardImage)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned _arg)
virtual void SetMetricKind (const SimilarityDefinition _arg)
virtual void SetOptimizerMaximumIterations (unsigned _arg)
virtual void SetScaleMax (double _arg)
virtual void SetSearchRadius (double _arg)
virtual void SetSearchScaleRadius (double _arg)
virtual void SetSearchSkewRadius (double _arg)
virtual void SetSkewMax (double _arg)
virtual void SetStepSize (double _arg)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetTransformationKind (const TransformationDefinition _arg)
virtual void SetTransformDirection (unsigned int _arg)
virtual void SetTranslateMax (double _arg)
virtual void SetUseTransformationDam (bool _arg)
virtual void SetWeightedAgregation (bool _arg)
void StartOptimization (void)
virtual void WeightedAgregationOff ()
virtual void WeightedAgregationOn ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType *fixedImage, InputImageType *movingImage)
double ComputeDirectionFilterBlockWeightUpdate (InputImageType *fixedImage, const ImageRegionType &region)
DistortionCorrectionRegistrationMethod ()
void GenerateData ()
void GlobalParametersSetup ()
void InitializeBlocksOnImage (InputImageType *image)
void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, SVFTransformType *addOn)
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &floatingImage)
virtual void SetLastTransformParameters (ParametersType _arg)
void setUpParameters (InterpolatorPointer &interpolator, MetricPointer &metric, OptimizerPointer &optimizer, unsigned startBlock, unsigned endBlock)
virtual ~DistortionCorrectionRegistrationMethod ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImage>
class anima::DistortionCorrectionRegistrationMethod< TInputImage >
Definition at line 23 of file animaDistortionCorrectionRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImage> typedef BaseTransformAgregator<InputImageType::ImageDimension> anima::DistortionCorrectionRegistrationMethod< TInputImage >::AgregatorType
Type of Transform Agregator
Definition at line 55 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseInputTransformType anima::DistortionCorrectionRegistrationMethod< TInputImage >::BaseInputTransformType
Definition at line 56 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseOutputTransformType anima::DistortionCorrectionRegistrationMethod< TInputImage >::BaseOutputTransformType
Definition at line 57 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef BaseTransformType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::BaseTransformPointer
Definition at line 89 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformType anima::DistortionCorrectionRegistrationMethod< TInputImage >::BaseTransformType
Type of the Transformation parameters This is the same type used to represent the search space of the optimization algorithm
Definition at line 88 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<const Self> anima::DistortionCorrectionRegistrationMethod< TInputImage >::ConstPointer
Definition at line 30 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObject::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::DataObjectPointer
Smart Pointer type to a DataObject.
Definition at line 93 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef ProcessObject::DataObjectPointerArraySizeType anima::DistortionCorrectionRegistrationMethod< TInputImage >::DataObjectPointerArraySizeType
Make a DataObject of the correct type to be used as the specified output.
Definition at line 191 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef DisplacementFieldTransformType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::DisplacementFieldTransformPointer
Definition at line 63 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef rpi::DisplacementFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::DistortionCorrectionRegistrationMethod< TInputImage >::DisplacementFieldTransformType
Definition at line 62 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::IndexType anima::DistortionCorrectionRegistrationMethod< TInputImage >::ImageIndexType
Definition at line 47 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::RegionType anima::DistortionCorrectionRegistrationMethod< TInputImage >::ImageRegionType
Definition at line 46 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::ConstPointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::InputImageConstPointer
Definition at line 44 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::InputImagePointer
Definition at line 45 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef TInputImage anima::DistortionCorrectionRegistrationMethod< TInputImage >::InputImageType
Type of the input image (both fixed and moving).
Definition at line 40 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InterpolatorType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::InterpolatorPointer
Definition at line 80 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::InterpolatorType anima::DistortionCorrectionRegistrationMethod< TInputImage >::InterpolatorType
Type of the Interpolator.
Definition at line 79 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::MetricPointer
Definition at line 52 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::ImageToImageMetric<InputImageType,InputImageType> anima::DistortionCorrectionRegistrationMethod< TInputImage >::MetricType
Type of the metric.
Definition at line 50 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef OptimizerType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::OptimizerPointer
Definition at line 84 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::SingleValuedNonLinearOptimizer anima::DistortionCorrectionRegistrationMethod< TInputImage >::OptimizerType
Type of the optimizer.
Definition at line 83 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformParametersType anima::DistortionCorrectionRegistrationMethod< TInputImage >::ParametersType
Definition at line 90 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<Self> anima::DistortionCorrectionRegistrationMethod< TInputImage >::Pointer
Definition at line 29 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::PointType anima::DistortionCorrectionRegistrationMethod< TInputImage >::PointType
Type of points for Setting block origins
Definition at line 70 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef DistortionCorrectionRegistrationMethod anima::DistortionCorrectionRegistrationMethod< TInputImage >::Self
Standard class typedefs.
Definition at line 27 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::ProcessObject anima::DistortionCorrectionRegistrationMethod< TInputImage >::Superclass
Definition at line 28 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef SVFTransformType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::SVFTransformPointer
Definition at line 61 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::StationaryVelocityFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::DistortionCorrectionRegistrationMethod< TInputImage >::SVFTransformType
RPI specific types
Definition at line 60 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::ConstPointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::TransformOutputConstPointer
Definition at line 76 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::TransformOutputPointer
Definition at line 75 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObjectDecorator< TransformType > anima::DistortionCorrectionRegistrationMethod< TInputImage >::TransformOutputType
Type for the output: Using Decorator pattern for enabling the Transform to be passed in the data pipeline
Definition at line 74 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef DisplacementFieldTransformType::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::TransformPointer
Definition at line 67 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> typedef DisplacementFieldTransformType anima::DistortionCorrectionRegistrationMethod< TInputImage >::TransformType
Type of the Transform .
Definition at line 66 of file animaDistortionCorrectionRegistrationMethod.h.
Member Enumeration Documentation
template<typename TInputImage> enum anima::DistortionCorrectionRegistrationMethod::AgregatorDefinition
Enumerator
Baloo
MEstimate
Definition at line 33 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> enum anima::DistortionCorrectionRegistrationMethod::SimilarityDefinition
Enumerator
Correlation
SquaredCorrelation
MeanSquares
Definition at line 32 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage> enum anima::DistortionCorrectionRegistrationMethod::TransformationDefinition
Enumerator
Direction
DirectionScale
DirectionScaleSkew
Definition at line 34 of file animaDistortionCorrectionRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::DistortionCorrectionRegistrationMethod< TInputImage >::DistortionCorrectionRegistrationMethod () protected
Constructor
Definition at line 78 of file animaDistortionCorrectionRegistrationMethod.hxx.
References DirectionScaleSkew, and SquaredCorrelation.
template<typename TInputImage> virtual anima::DistortionCorrectionRegistrationMethod< TInputImage >::~DistortionCorrectionRegistrationMethod () inline protected virtual
Definition at line 205 of file animaDistortionCorrectionRegistrationMethod.h.
Member Function Documentation
template<typename TInputImage> void anima::DistortionCorrectionRegistrationMethod< TInputImage >::Abort (void) inline
Definition at line 201 of file animaDistortionCorrectionRegistrationMethod.h.
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType * fixedImage, InputImageType * movingImage) protected
Definition at line 717 of file animaDistortionCorrectionRegistrationMethod.hxx.
References MeanSquares, and CommandIterationUpdate::New().
Referenced by anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatching().
template<typename TInputImage > double anima::DistortionCorrectionRegistrationMethod< TInputImage >::ComputeDirectionFilterBlockWeightUpdate (InputImageType * fixedImage, const ImageRegionType & region) protected
Definition at line 792 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual::itk::LightObject::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::CreateAnother (void) const
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::GenerateData (void) protected
Method invoked by the pipeline in order to trigger the computation of the registration.
Definition at line 886 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual AgregatorType* anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetAgregator () virtual
template<typename TInputImage> virtual const InputImageType* anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetBackwardImage () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetFinalRadius () const virtual
template<typename TInputImage> virtual const InputImageType* anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetForwardImage () const virtual
template<typename TInputImage> virtual const ParametersType& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetLastTransformParameters () const virtual
Get the last transformation parameters visited by the optimizer.
template<typename TInputImage> virtual const unsigned& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetMaximumIterations () const virtual
template<typename TInputImage> virtual SimilarityDefinition anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetMetricKind () const virtual
template<typename TInputImage > itk::ModifiedTimeType anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetMTime () const
Method to return the latest modified time of this object or any of its cached ivars
Definition at line 124 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual const char* anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<typename TInputImage> virtual const unsigned& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetOptimizerMaximumIterations () const virtual
template<typename TInputImage > DistortionCorrectionRegistrationMethod< TInputImage >::TransformOutputType * anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetOutput ()
Returns the transform resulting from the registration process
Get Output
Definition at line 915 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetScaleMax () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetSearchRadius () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetSearchScaleRadius () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetSearchSkewRadius () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetSkewMax () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetStepSize () const virtual
template<typename TInputImage > const std::string anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetStopConditionDescription () const
Definition at line 971 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetSVFElasticRegSigma () const virtual
template<typename TInputImage> virtual TransformationDefinition anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetTransformationKind () const virtual
template<typename TInputImage> virtual const double& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetTranslateMax () const virtual
template<typename TInputImage> virtual const bool& anima::DistortionCorrectionRegistrationMethod< TInputImage >::GetWeightedAgregation () const virtual
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::GlobalParametersSetup () protected
Definition at line 531 of file animaDistortionCorrectionRegistrationMethod.hxx.
References Direction, DirectionScale, DirectionScaleSkew, MeanSquares, and anima::DirectionScaleSkewTransform< TScalarType >::SetIdentity().
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::Initialize () throw (itk::ExceptionObject) virtual
Initialize by setting the interconnects between the components.
Initialize by setting the interconnects between components.
Definition at line 154 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::InitializeBlocksOnImage (InputImageType * image) protected
Definition at line 382 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage > itk::DataObject::Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::MakeOutput (DataObjectPointerArraySizeType idx) virtual
Definition at line 923 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> static Pointer anima::DistortionCorrectionRegistrationMethod< TInputImage >::New () static
Method for creation through the object factory.
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, SVFTransformType * addOn) protected
Definition at line 416 of file animaDistortionCorrectionRegistrationMethod.hxx.
References Baloo, anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::BlockMatch, anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::fixedImage, and anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::movingImage.
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
PrintSelf
Definition at line 860 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::ResampleImages (TransformType * currentTransform, InputImagePointer & refImage, InputImagePointer & floatingImage) protected
Definition at line 255 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetAgregator (AgregatorType * _arg) virtual
Set/Get Method for the Agregator
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetAgregatorType (AgregatorDefinition _arg) virtual
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetBackwardImage (InputImageType * backwardImage)
Set/Get the Fixed/backward image.
Definition at line 939 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetBlockPercentageKept (double _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetBlockScalarVarianceThreshold (double _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetBlockSize (unsigned int _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetBlockSpacing (unsigned int _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetCurrentTransform (TransformPointer _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetDamDistance (double _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetFinalRadius (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetForwardImage (InputImageType * forwardImage)
Set/Get the Moving/forward image.
Definition at line 955 of file animaDistortionCorrectionRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetInitialTransform (TransformPointer _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetLastTransformParameters (ParametersType _arg) protected virtual
Provides derived classes with the ability to set this private var
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetMaximumIterations (unsigned _arg) virtual
Set/Get the maximum number of iterations
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetMetricKind (const SimilarityDefinition _arg) virtual
Set/Get the Metric.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetOptimizerMaximumIterations (unsigned _arg) virtual
Set/Get the maximum number of iterations per block if optimizer called
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetScaleMax (double _arg) virtual
Set/Get the upper bound on scales for bobyqa
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetSearchRadius (double _arg) virtual
Set/Get the search radius (rho start for bobyqa)
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetSearchScaleRadius (double _arg) virtual
Set/Get the search radius specific for scale search (rho start for bobyqa)
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetSearchSkewRadius (double _arg) virtual
Set/Get the search radius specific for skew search (rho start for bobyqa)
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetSkewMax (double _arg) virtual
Set/Get the upper bound on skews for bobyqa
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetStepSize (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetSVFElasticRegSigma (double _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetTransformationKind (const TransformationDefinition _arg) virtual
Set/Get the transformation type for blocks.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetTransformDirection (unsigned int _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetTranslateMax (double _arg) virtual
Set/Get the upper bound on translations for bobyqa
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::setUpParameters (InterpolatorPointer & interpolator, MetricPointer & metric, OptimizerPointer & optimizer, unsigned startBlock, unsigned endBlock) protected
Definition at line 563 of file animaDistortionCorrectionRegistrationMethod.hxx.
References Direction, DirectionScale, DirectionScaleSkew, MeanSquares, anima::DirectionScaleSkewTransform< TScalarType >::SetIdentity(), and SquaredCorrelation.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetUseTransformationDam (bool _arg) virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::SetWeightedAgregation (bool _arg) virtual
Boolean to choose Weighted or non-Weighted Agregation
template<typename TInputImage > void anima::DistortionCorrectionRegistrationMethod< TInputImage >::StartOptimization (void)
Starts the Registration Process
Definition at line 177 of file animaDistortionCorrectionRegistrationMethod.hxx.
References anima::composeDistortionCorrections(), and anima::GetSVFExponential().
template<typename TInputImage > ITK_THREAD_RETURN_TYPE anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatching (void * arg) static protected
Do the matching for a batch of regions (splited according to the thread id + nb threads)
Threaded block match
Definition at line 517 of file animaDistortionCorrectionRegistrationMethod.hxx.
References anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::BlockMatch, anima::DistortionCorrectionRegistrationMethod< TInputImage >::BlockMatch(), anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::fixedImage, and anima::DistortionCorrectionRegistrationMethod< TInputImage >::ThreadedMatchData::movingImage.
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::WeightedAgregationOff () virtual
template<typename TInputImage> virtual void anima::DistortionCorrectionRegistrationMethod< TInputImage >::WeightedAgregationOn () virtual
The documentation for this class was generated from the following files:
animaDistortionCorrectionRegistrationMethod.h
animaDistortionCorrectionRegistrationMethod.hxx