ANIMA: anima::CombinedRelaxometryCostFunction Class Reference
anima::CombinedRelaxometryCostFunction Class Reference
#include <animaCombinedRelaxometryCostFunction.h>
Public Types
typedef std::vector
< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector
< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
enum OptimizedValueType {
M0 = 0,
B1,
T2,
T1
}
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef
CombinedRelaxometryCostFunction Self
typedef
itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const
virtual MeasureType GetValue (const ParametersType &parameters) const
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetB1Value (double _arg)
virtual void SetKValue (double _arg)
virtual void SetM0Value (double _arg)
virtual void SetOptimizedValue (OptimizedValueType _arg)
void SetT1FlipAngles (std::vector< double > &flipAngles)
void SetT1RelaxometrySignals (std::vector< double > &relaxoSignals)
virtual void SetT1Value (double _arg)
virtual void SetT2EchoSpacing (double _arg)
virtual void SetT2ExcitationFlipAngle (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2RelaxometrySignals (std::vector< double > &relaxoSignals)
virtual void SetT2Value (double _arg)
virtual void SetTRValue (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
CombinedRelaxometryCostFunction ()
virtual ~CombinedRelaxometryCostFunction ()
Detailed Description
Definition at line 9 of file animaCombinedRelaxometryCostFunction.h.
Member Typedef Documentation
typedef std::vector< std::complex <double> > anima::CombinedRelaxometryCostFunction::ComplexVectorType
Definition at line 27 of file animaCombinedRelaxometryCostFunction.h.
typedef itk::SmartPointer<const Self> anima::CombinedRelaxometryCostFunction::ConstPointer
Definition at line 17 of file animaCombinedRelaxometryCostFunction.h.
typedef Superclass::DerivativeType anima::CombinedRelaxometryCostFunction::DerivativeType
Definition at line 25 of file animaCombinedRelaxometryCostFunction.h.
typedef std::vector<ComplexVectorType> anima::CombinedRelaxometryCostFunction::MatrixType
Definition at line 28 of file animaCombinedRelaxometryCostFunction.h.
typedef Superclass::MeasureType anima::CombinedRelaxometryCostFunction::MeasureType
Definition at line 22 of file animaCombinedRelaxometryCostFunction.h.
typedef Superclass::ParametersType anima::CombinedRelaxometryCostFunction::ParametersType
Definition at line 26 of file animaCombinedRelaxometryCostFunction.h.
typedef itk::SmartPointer<Self> anima::CombinedRelaxometryCostFunction::Pointer
Definition at line 16 of file animaCombinedRelaxometryCostFunction.h.
typedef CombinedRelaxometryCostFunction anima::CombinedRelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaCombinedRelaxometryCostFunction.h.
typedef itk::SingleValuedCostFunction anima::CombinedRelaxometryCostFunction::Superclass
Definition at line 15 of file animaCombinedRelaxometryCostFunction.h.
Member Enumeration Documentation
enum anima::CombinedRelaxometryCostFunction::OptimizedValueType
Enumerator
M0
B1
T2
T1
Definition at line 51 of file animaCombinedRelaxometryCostFunction.h.
Constructor & Destructor Documentation
anima::CombinedRelaxometryCostFunction::CombinedRelaxometryCostFunction () inline protected
Definition at line 67 of file animaCombinedRelaxometryCostFunction.h.
virtual anima::CombinedRelaxometryCostFunction::~CombinedRelaxometryCostFunction () inline protected virtual
Definition at line 83 of file animaCombinedRelaxometryCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::CombinedRelaxometryCostFunction::CreateAnother (void) const
virtual void anima::CombinedRelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const inline virtual
Definition at line 31 of file animaCombinedRelaxometryCostFunction.h.
virtual const char* anima::CombinedRelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
unsigned int anima::CombinedRelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 61 of file animaCombinedRelaxometryCostFunction.h.
CombinedRelaxometryCostFunction::MeasureType anima::CombinedRelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 8 of file animaCombinedRelaxometryCostFunction.cxx.
References B1, anima::EPGSignalSimulator::GetValue(), M0, anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), anima::EPGSignalSimulator::SetNumberOfEchoes(), T1, and T2.
static Pointer anima::CombinedRelaxometryCostFunction::New () static
virtual void anima::CombinedRelaxometryCostFunction::SetB1OnExcitationAngle (bool _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetB1Value (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetKValue (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetM0Value (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetOptimizedValue (OptimizedValueType _arg) virtual
void anima::CombinedRelaxometryCostFunction::SetT1FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 39 of file animaCombinedRelaxometryCostFunction.h.
void anima::CombinedRelaxometryCostFunction::SetT1RelaxometrySignals (std::vector< double > & relaxoSignals) inline
Definition at line 36 of file animaCombinedRelaxometryCostFunction.h.
virtual void anima::CombinedRelaxometryCostFunction::SetT1Value (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetT2EchoSpacing (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetT2ExcitationFlipAngle (double _arg) virtual
void anima::CombinedRelaxometryCostFunction::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 40 of file animaCombinedRelaxometryCostFunction.h.
void anima::CombinedRelaxometryCostFunction::SetT2RelaxometrySignals (std::vector< double > & relaxoSignals) inline
Definition at line 37 of file animaCombinedRelaxometryCostFunction.h.
virtual void anima::CombinedRelaxometryCostFunction::SetT2Value (double _arg) virtual
virtual void anima::CombinedRelaxometryCostFunction::SetTRValue (double _arg) virtual
The documentation for this class was generated from the following files:
animaCombinedRelaxometryCostFunction.h
animaCombinedRelaxometryCostFunction.cxx