ANIMA: anima::DDIAverageImagesImageFilter Class Reference
anima::DDIAverageImagesImageFilter Class Reference
#include <animaDDIAverageImagesImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InputImageType::ConstPointer InputImagePointer
typedef itk::VectorImage
< double, 3 > InputImageType
typedef InputImageType::IndexType InputIndexType
typedef
itk::ImageRegionConstIterator
< InputImageType > InputIteratorType
typedef InputImageType::RegionType InputRegionType
typedef OutputImageType::Pointer OutputImagePointer
typedef itk::VectorImage
< double, 3 > OutputImageType
typedef
itk::ImageRegionIterator
< OutputImageType > OutputIteratorType
typedef InputImageType::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef DDIAverageImagesImageFilter Self
typedef
itk::ImageToImageFilter
< InputImageType,
OutputImageType > SuperClass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DDIAverageImagesImageFilter ()
virtual const char * GetNameOfClass () const
virtual void SetMethod (int _arg)
virtual void SetNumberOfOutputFascicles (int _arg)
virtual ~DDIAverageImagesImageFilter ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void ThreadedGenerateData (const InputRegionType &region, itk::ThreadIdType threadId)
Detailed Description
Definition at line 13 of file animaDDIAverageImagesImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::DDIAverageImagesImageFilter::ConstPointer
Definition at line 25 of file animaDDIAverageImagesImageFilter.h.
typedef InputImageType::ConstPointer anima::DDIAverageImagesImageFilter::InputImagePointer
Definition at line 31 of file animaDDIAverageImagesImageFilter.h.
typedef itk::VectorImage<double, 3> anima::DDIAverageImagesImageFilter::InputImageType
Definition at line 21 of file animaDDIAverageImagesImageFilter.h.
typedef InputImageType::IndexType anima::DDIAverageImagesImageFilter::InputIndexType
Definition at line 37 of file animaDDIAverageImagesImageFilter.h.
typedef itk::ImageRegionConstIterator<InputImageType> anima::DDIAverageImagesImageFilter::InputIteratorType
Definition at line 40 of file animaDDIAverageImagesImageFilter.h.
typedef InputImageType::RegionType anima::DDIAverageImagesImageFilter::InputRegionType
Definition at line 36 of file animaDDIAverageImagesImageFilter.h.
typedef OutputImageType::Pointer anima::DDIAverageImagesImageFilter::OutputImagePointer
Definition at line 34 of file animaDDIAverageImagesImageFilter.h.
typedef itk::VectorImage<double, 3> anima::DDIAverageImagesImageFilter::OutputImageType
Definition at line 22 of file animaDDIAverageImagesImageFilter.h.
typedef itk::ImageRegionIterator<OutputImageType> anima::DDIAverageImagesImageFilter::OutputIteratorType
Definition at line 41 of file animaDDIAverageImagesImageFilter.h.
typedef InputImageType::PixelType anima::DDIAverageImagesImageFilter::PixelType
Definition at line 38 of file animaDDIAverageImagesImageFilter.h.
typedef itk::SmartPointer<Self> anima::DDIAverageImagesImageFilter::Pointer
Definition at line 24 of file animaDDIAverageImagesImageFilter.h.
typedef DDIAverageImagesImageFilter anima::DDIAverageImagesImageFilter::Self
Standard class type def
Definition at line 20 of file animaDDIAverageImagesImageFilter.h.
typedef itk::ImageToImageFilter<InputImageType, OutputImageType > anima::DDIAverageImagesImageFilter::SuperClass
Definition at line 23 of file animaDDIAverageImagesImageFilter.h.
Constructor & Destructor Documentation
anima::DDIAverageImagesImageFilter::DDIAverageImagesImageFilter () inline
Definition at line 46 of file animaDDIAverageImagesImageFilter.h.
virtual anima::DDIAverageImagesImageFilter::~DDIAverageImagesImageFilter () inline virtual
Definition at line 52 of file animaDDIAverageImagesImageFilter.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::DDIAverageImagesImageFilter::CreateAnother (void) const
virtual const char* anima::DDIAverageImagesImageFilter::GetNameOfClass () const virtual
Run-time type information (and related methods)
static Pointer anima::DDIAverageImagesImageFilter::New () static
Method for creation through the object factory.
Referenced by main().
virtual void anima::DDIAverageImagesImageFilter::SetMethod (int _arg) virtual
virtual void anima::DDIAverageImagesImageFilter::SetNumberOfOutputFascicles (int _arg) virtual
void anima::DDIAverageImagesImageFilter::ThreadedGenerateData (const InputRegionType & region, itk::ThreadIdType threadId) protected
Definition at line 6 of file animaDDIAverageImagesImageFilter.hxx.
References anima::CompartmentSize, anima::ComputeDistanceMatrixBetweenFascicles(), anima::DDIAveraging(), anima::FreeWaterDDIAveraging(), anima::SpectralClusteringFilter< ScalarType >::GetClassesMembership(), anima::RemoveNullFascicles(), anima::SpectralClusteringFilter< ScalarType >::SetInputData(), anima::SpectralClusteringFilter< ScalarType >::SetNbClass(), anima::SpectralClusteringFilter< ScalarType >::SetVerbose(), anima::SpectralClusteringFilter< ScalarType >::Update(), and anima::WIndex.
The documentation for this class was generated from the following files:
animaDDIAverageImagesImageFilter.h
animaDDIAverageImagesImageFilter.hxx