ANIMA: GenericArguments Class Reference
GenericArguments Class Reference abstract
#include <Arguments.h>
Public Types
enum ArgumentsKind {
InputArgument,
OutputArgument,
Comment
}
Public Member Functions
virtual void _output_xml_ (const char *name, std::ostream &)=0
void fromString (std::string)
GenericArguments ()
GenericArguments (int, const char **argv, int _count)
bool & getXml ()
std::string toString ()
std::string toXML ()
void usage (const char *)
virtual ~GenericArguments ()
Static Public Member Functions
static GenericArguments * getCommandLineArguments (GenericArguments *dat=0)
Public Attributes
int count
std::string exename
bool parsed
GenericArgumentArg< bool > Xml
Protected Member Functions
bool & getRef0 ()
Static Protected Member Functions
static enum ArgumentsKind AKind0 ()
static const char * ArgName0 ()
static const bool DefaultValue0 ()
static const bool hasDefault0 (bool flag=false)
static const char * MDetail0 ()
static const char * MName0 (bool _long=false)
Detailed Description
This is the parent class that shall be used when constructing a new argument class
Definition at line 588 of file Arguments.h.
Member Enumeration Documentation
enum GenericArguments::ArgumentsKind
Enumerator
InputArgument
OutputArgument
Comment
Definition at line 593 of file Arguments.h.
Constructor & Destructor Documentation
GenericArguments::GenericArguments () inline
Definition at line 599 of file Arguments.h.
GenericArguments::GenericArguments (int , const char ** argv, int _count) inline
Definition at line 600 of file Arguments.h.
References getCommandLineArguments().
virtual GenericArguments::~GenericArguments () inline virtual
Definition at line 602 of file Arguments.h.
References progressFinished().
Member Function Documentation
virtual void GenericArguments::_output_xml_ (const char * name, std::ostream &) pure virtual
Referenced by toXML().
static enum ArgumentsKind GenericArguments::AKind0 () inline static protected
Definition at line 629 of file Arguments.h.
References InputArgument.
static const char* GenericArguments::ArgName0 () inline static protected
Definition at line 627 of file Arguments.h.
static const bool GenericArguments::DefaultValue0 () inline static protected
Definition at line 625 of file Arguments.h.
void GenericArguments::fromString (std::string) inline
Definition at line 614 of file Arguments.h.
static GenericArguments* GenericArguments::getCommandLineArguments (GenericArguments * dat = 0) inline static
Definition at line 633 of file Arguments.h.
Referenced by GenericArguments().
bool& GenericArguments::getRef0 () inline protected
Definition at line 622 of file Arguments.h.
References GenericArgumentArg< Type >::arg, and Xml.
bool& GenericArguments::getXml () inline
Definition at line 618 of file Arguments.h.
References GenericArgumentArg< Type >::arg, and Xml.
static const bool GenericArguments::hasDefault0 (bool flag = false) inline static protected
Definition at line 624 of file Arguments.h.
static const char* GenericArguments::MDetail0 () inline static protected
Definition at line 628 of file Arguments.h.
static const char* GenericArguments::MName0 (bool _long = false) inline static protected
Definition at line 626 of file Arguments.h.
std::string GenericArguments::toString () inline
Definition at line 612 of file Arguments.h.
std::string GenericArguments::toXML () inline
Definition at line 620 of file Arguments.h.
References _output_xml_(), and exename.
void GenericArguments::usage (const char *) inline
Definition at line 608 of file Arguments.h.
Referenced by main().
Member Data Documentation
int GenericArguments::count
Definition at line 597 of file Arguments.h.
std::string GenericArguments::exename
Definition at line 594 of file Arguments.h.
Referenced by toXML().
bool GenericArguments::parsed
Definition at line 595 of file Arguments.h.
Referenced by main().
GenericArgumentArg<bool> GenericArguments::Xml
Definition at line 617 of file Arguments.h.
Referenced by getRef0(), and getXml().
The documentation for this class was generated from the following file:
Arguments.h