ANIMA: anima::DDICostFunction Class Reference
anima::DDICostFunction Class Reference
#include <ddiCostFunction.h>
Classes
struct DTData
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef vnl_vector_fixed
< double, 3 > GradientType
typedef vnl_matrix< double > MatrixType
typedef Superclass::MeasureType MeasureType
typedef
itk::VariableLengthVector
< float > ModelPixelType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef DDICostFunction Self
typedef
itk::SingleValuedCostFunction Superclass
typedef itk::DiffusionTensor3D
< double > TensorPixelType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void FixedGeometryInitialization (ParametersType &p)
virtual double GetB0Value () const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfCommonParameters () const
virtual unsigned int GetNumberOfFascicleSpecificParameters () const
virtual unsigned int GetNumberOfParameters () const
virtual double GetSigmaSq () const
virtual MeasureType GetValue (const ParametersType &parameters) const
void Initialize ()
void RandomGeometryInitialization (ParametersType &p)
void RandomOrientationInitializationFromDTI (ParametersType &p)
void Setbvalue (std::vector< double > &value)
virtual void SetCommonDiff (bool _arg)
virtual void SetCommonEAF (bool _arg)
virtual void SetCommonKappa (bool _arg)
virtual void SetCommonVolFrac (bool _arg)
virtual void SetCSFDiffusivity (double _arg)
virtual void SetEAFVal (double _arg)
virtual void SetEstimateDiff (bool _arg)
virtual void SetEstimateEAF (bool _arg)
virtual void SetEstimateFreeDiff (bool _arg)
virtual void SetEstimateKappa (bool _arg)
virtual void SetEstimateVolFrac (bool _arg)
void Setgradients (std::vector< GradientType > &value)
void SetInitialModel (ModelPixelType &model)
virtual void SetKappaLowerBound (double _arg)
virtual void SetKappaUpperBound (double _arg)
virtual void SetNbFibres (unsigned int _arg)
void SetOrientationsFromSimplerMCM (ParametersType &p)
virtual void SetParallelDiffusivity (double _arg)
virtual void SetPerpendicularDiffusivity (double _arg)
virtual void SetS0 (double _arg)
void SetSi (std::vector< double > &value)
virtual void SetTTKTensor (bool _arg)
virtual void SetVolFracVal (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
DDICostFunction ()
virtual ~DDICostFunction ()
Detailed Description
Definition at line 14 of file ddiCostFunction.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::DDICostFunction::ConstPointer
Definition at line 22 of file ddiCostFunction.h.
typedef Superclass::DerivativeType anima::DDICostFunction::DerivativeType
Definition at line 30 of file ddiCostFunction.h.
typedef vnl_vector_fixed<double,3> anima::DDICostFunction::GradientType
Definition at line 33 of file ddiCostFunction.h.
typedef vnl_matrix<double> anima::DDICostFunction::MatrixType
Definition at line 36 of file ddiCostFunction.h.
typedef Superclass::MeasureType anima::DDICostFunction::MeasureType
Definition at line 27 of file ddiCostFunction.h.
typedef itk::VariableLengthVector<float> anima::DDICostFunction::ModelPixelType
Definition at line 35 of file ddiCostFunction.h.
typedef Superclass::ParametersType anima::DDICostFunction::ParametersType
Definition at line 31 of file ddiCostFunction.h.
typedef itk::SmartPointer<Self> anima::DDICostFunction::Pointer
Definition at line 21 of file ddiCostFunction.h.
typedef DDICostFunction anima::DDICostFunction::Self
Standard class typedefs.
Definition at line 19 of file ddiCostFunction.h.
typedef itk::SingleValuedCostFunction anima::DDICostFunction::Superclass
Definition at line 20 of file ddiCostFunction.h.
typedef itk::DiffusionTensor3D<double> anima::DDICostFunction::TensorPixelType
Definition at line 34 of file ddiCostFunction.h.
Constructor & Destructor Documentation
anima::DDICostFunction::DDICostFunction () protected
Definition at line 26 of file ddiCostFunction.cxx.
virtual anima::DDICostFunction::~DDICostFunction () inline protected virtual
Definition at line 118 of file ddiCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::DDICostFunction::CreateAnother (void) const
void anima::DDICostFunction::FixedGeometryInitialization (ParametersType & p)
Definition at line 199 of file ddiCostFunction.cxx.
References anima::xi().
virtual double anima::DDICostFunction::GetB0Value () const inline virtual
Definition at line 101 of file ddiCostFunction.h.
void anima::DDICostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 433 of file ddiCostFunction.cxx.
virtual const char* anima::DDICostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
virtual unsigned int anima::DDICostFunction::GetNumberOfCommonParameters () const inline virtual
Definition at line 96 of file ddiCostFunction.h.
virtual unsigned int anima::DDICostFunction::GetNumberOfFascicleSpecificParameters () const inline virtual
Definition at line 91 of file ddiCostFunction.h.
virtual unsigned int anima::DDICostFunction::GetNumberOfParameters () const inline virtual
Definition at line 86 of file ddiCostFunction.h.
virtual double anima::DDICostFunction::GetSigmaSq () const inline virtual
Definition at line 106 of file ddiCostFunction.h.
DDICostFunction::MeasureType anima::DDICostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 315 of file ddiCostFunction.cxx.
References anima::ComputeMixtureSymmetricCDF(), anima::TransformSphericalToCartesianCoordinates(), and anima::xi().
void anima::DDICostFunction::Initialize ()
Definition at line 65 of file ddiCostFunction.cxx.
static Pointer anima::DDICostFunction::New () static
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::ThreadedGenerateData().
void anima::DDICostFunction::RandomGeometryInitialization (ParametersType & p)
Definition at line 265 of file ddiCostFunction.cxx.
References anima::SampleFromUniformDistribution(), and anima::xi().
void anima::DDICostFunction::RandomOrientationInitializationFromDTI (ParametersType & p)
Definition at line 160 of file ddiCostFunction.cxx.
References anima::DDICostFunction::DTData::e1, anima::DDICostFunction::DTData::e2, anima::DDICostFunction::DTData::linCoef, anima::DDICostFunction::DTData::planCoef, anima::SampleFromUniformDistribution(), and anima::TransformCartesianToSphericalCoordinates().
void anima::DDICostFunction::Setbvalue (std::vector< double > & value) inline
Definition at line 55 of file ddiCostFunction.h.
virtual void anima::DDICostFunction::SetCommonDiff (bool _arg) virtual
virtual void anima::DDICostFunction::SetCommonEAF (bool _arg) virtual
virtual void anima::DDICostFunction::SetCommonKappa (bool _arg) virtual
virtual void anima::DDICostFunction::SetCommonVolFrac (bool _arg) virtual
virtual void anima::DDICostFunction::SetCSFDiffusivity (double _arg) virtual
virtual void anima::DDICostFunction::SetEAFVal (double _arg) virtual
virtual void anima::DDICostFunction::SetEstimateDiff (bool _arg) virtual
virtual void anima::DDICostFunction::SetEstimateEAF (bool _arg) virtual
virtual void anima::DDICostFunction::SetEstimateFreeDiff (bool _arg) virtual
virtual void anima::DDICostFunction::SetEstimateKappa (bool _arg) virtual
virtual void anima::DDICostFunction::SetEstimateVolFrac (bool _arg) virtual
void anima::DDICostFunction::Setgradients (std::vector< GradientType > & value) inline
Definition at line 54 of file ddiCostFunction.h.
void anima::DDICostFunction::SetInitialModel (ModelPixelType & model) inline
Definition at line 57 of file ddiCostFunction.h.
virtual void anima::DDICostFunction::SetKappaLowerBound (double _arg) virtual
virtual void anima::DDICostFunction::SetKappaUpperBound (double _arg) virtual
virtual void anima::DDICostFunction::SetNbFibres (unsigned int _arg) virtual
void anima::DDICostFunction::SetOrientationsFromSimplerMCM (ParametersType & p)
Definition at line 249 of file ddiCostFunction.cxx.
References anima::CompartmentSize, and anima::TransformCartesianToSphericalCoordinates().
virtual void anima::DDICostFunction::SetParallelDiffusivity (double _arg) virtual
virtual void anima::DDICostFunction::SetPerpendicularDiffusivity (double _arg) virtual
virtual void anima::DDICostFunction::SetS0 (double _arg) virtual
void anima::DDICostFunction::SetSi (std::vector< double > & value) inline
Definition at line 53 of file ddiCostFunction.h.
virtual void anima::DDICostFunction::SetTTKTensor (bool _arg) virtual
virtual void anima::DDICostFunction::SetVolFracVal (double _arg) virtual
The documentation for this class was generated from the following files:
ddiCostFunction.h
ddiCostFunction.cxx