ANIMA: anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep > Class Template Reference
anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep > Class Template Reference
#include <animaDDILinearInterpolateImageFunction.h>
Classes
struct pair_decreasing_comparator
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::ContinuousIndexType ContinuousIndexType
typedef Superclass::IndexType IndexType
typedef Superclass::IndexValueType IndexValueType
typedef Superclass::InputImageType InputImageType
typedef Superclass::OutputType OutputType
typedef TInputImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::RealType RealType
typedef
DDILinearInterpolateImageFunction Self
typedef
itk::InterpolateImageFunction
< TInputImage, TCoordRep > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputType EvaluateAtContinuousIndex (const ContinuousIndexType &index) const
virtual const char * GetNameOfClass () const
virtual void SetWeightThreshold (double _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = Superclass::ImageDimension
Protected Member Functions
DDILinearInterpolateImageFunction ()
virtual bool IsInsideBuffer (const ContinuousIndexType &index) const
bool isZero (const PixelType &value) const
void PrintSelf (std::ostream &os, itk::Indent indent) const
virtual ~DDILinearInterpolateImageFunction ()
Detailed Description
template<class TInputImage, class TCoordRep = double>
class anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >
Definition at line 10 of file animaDDILinearInterpolateImageFunction.h.
Member Typedef Documentation
template<class TInputImage, class TCoordRep = double> typedef itk::SmartPointer<const Self> anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::ConstPointer
Definition at line 18 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::ContinuousIndexType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::ContinuousIndexType
ContinuousIndex typedef support.
Definition at line 40 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::IndexType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::IndexType
Index typedef support.
Definition at line 36 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::IndexValueType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::IndexValueType
Definition at line 37 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::InputImageType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::InputImageType
InputImageType typedef support.
Definition at line 25 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::OutputType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::OutputType
Definition at line 42 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef TInputImage::PixelType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::PixelType
Definition at line 29 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef itk::SmartPointer<Self> anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::Pointer
Definition at line 17 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef Superclass::RealType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::RealType
Definition at line 30 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef DDILinearInterpolateImageFunction anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::Self
Standard class typedefs.
Definition at line 15 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> typedef itk::InterpolateImageFunction<TInputImage,TCoordRep> anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::Superclass
Definition at line 16 of file animaDDILinearInterpolateImageFunction.h.
Constructor & Destructor Documentation
template<class TInputImage , class TCoordRep > anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::DDILinearInterpolateImageFunction () protected
Constructor
Definition at line 24 of file animaDDILinearInterpolateImageFunction.hxx.
template<class TInputImage, class TCoordRep = double> virtual anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::~DDILinearInterpolateImageFunction () inline protected virtual
Definition at line 58 of file animaDDILinearInterpolateImageFunction.h.
Member Function Documentation
template<class TInputImage, class TCoordRep = double> virtual::itk::LightObject::Pointer anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::CreateAnother (void) const
template<class TInputImage , class TCoordRep > DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::OutputType anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex (const ContinuousIndexType & index) const virtual
Evaluate the function at a ContinuousIndex position
Returns the linearly interpolated image intensity at a specified point position. No bounds checking is done. The point is assumed to lie within the image buffer.
ImageFunction::IsInsideBuffer() can be used to check bounds before calling the method.
Evaluate at image index position
Definition at line 48 of file animaDDILinearInterpolateImageFunction.hxx.
References anima::AIndex, anima::ComputeScalarProduct(), anima::DIndex, anima::KappaIndex, anima::ModularityClusteringFilter< DataType >::SetInputData(), anima::WIndex, and anima::xi().
template<class TInputImage, class TCoordRep = double> virtual const char* anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage, class TCoordRep = double> virtual bool anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::IsInsideBuffer (const ContinuousIndexType & index) const inline protected virtual
Definition at line 61 of file animaDDILinearInterpolateImageFunction.h.
References anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::ImageDimension.
template<class TInputImage, class TCoordRep = double> bool anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero (const PixelType & value) const inline protected
Definition at line 75 of file animaDDILinearInterpolateImageFunction.h.
template<class TInputImage, class TCoordRep = double> static Pointer anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::New () static
Method for creation through the object factory.
Referenced by anima::DDIProbabilisticTractographyImageFilter::DDIProbabilisticTractographyImageFilter(), and main().
template<class TInputImage , class TCoordRep > void anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
PrintSelf
Definition at line 35 of file animaDDILinearInterpolateImageFunction.hxx.
template<class TInputImage, class TCoordRep = double> virtual void anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::SetWeightThreshold (double _arg) virtual
Member Data Documentation
template<class TInputImage, class TCoordRep = double> const unsigned int anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::ImageDimension = Superclass::ImageDimension static
Dimension underlying input image.
Definition at line 33 of file animaDDILinearInterpolateImageFunction.h.
Referenced by anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::IsInsideBuffer().
The documentation for this class was generated from the following files:
animaDDILinearInterpolateImageFunction.h
animaDDILinearInterpolateImageFunction.hxx