ANIMA: anima::BlockMatchingBaseRegistrationMethod< TInputImage > Class Template Reference
anima::BlockMatchingBaseRegistrationMethod< TInputImage > Class Template Reference abstract
#include <animaBlockMatchingBaseRegistrationMethod.h>
Classes
struct ThreadedMatchData
Public Types
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImage::ImageDimension > AffineTransformType
typedef BaseTransformAgregator
< InputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MetricType::TransformType BaseTransformType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::DataObject::Pointer DataObjectPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > DisplacementFieldTransformType
typedef InputImageType::IndexType ImageIndexType
typedef InputImageType::RegionType ImageRegionType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
MetricType::InterpolatorType InterpolatorType
typedef MetricType::Pointer MetricPointer
typedef
itk::ImageToImageMetric
< InputImageType,
InputImageType > MetricType
enum OptimizerDefinition {
Exhaustive,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef
MetricType::TransformParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef
BlockMatchingBaseRegistrationMethod Self
enum SimilarityDefinition {
MeanSquares,
Correlation,
SquaredCorrelation
}
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< typename
AgregatorType::ScalarType,
InputImageType::ImageDimension > SVFTransformType
enum TransformationDefinition {
Translation,
Rigid,
Affine
}
typedef
TransformOutputType::ConstPointer TransformOutputConstPointer
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual const double & GetAngleMax () const
BaseInputTransformType::Pointer GetBaseTransformPointer (unsigned int i)
std::vector< typename
BaseInputTransformType::Pointer > & GetBaseTransformsPointers ()
std::vector< ImageRegionType > & GetBlockRegions ()
virtual double GetBlockScalarVarianceThreshold ()
std::vector< double > & GetBlockWeights ()
virtual const double & GetFinalRadius () const
virtual InputImageType * GetFixedImage ()
virtual const vnl_matrix
< double > & GetGeometry () const
virtual const bool & GetMaximizeMetric () const
virtual const unsigned int & GetMaximumIterations () const
virtual SimilarityDefinition GetMetricKind () const
virtual const double & GetMinimalTransformError () const
virtual InputImageType * GetMovingImage ()
itk::ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual OptimizerDefinition GetOptimizerKind () const
virtual const unsigned int & GetOptimizerMaximumIterations () const
TransformOutputType * GetOutput ()
virtual const double & GetScaleMax () const
virtual const double & GetSearchAngleRadius () const
virtual const double & GetSearchRadius () const
virtual const double & GetSearchScaleRadius () const
virtual const double & GetSearchSkewRadius () const
virtual const double & GetSkewMax () const
virtual const double & GetStepSize () const
const std::string GetStopConditionDescription () const
virtual const double & GetSVFElasticRegSigma () const
virtual TransformationDefinition GetTransformKind () const
virtual const double & GetTranslateMax () const
virtual void Initialize () throw (itk::ExceptionObject)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetAngleMax (double _arg)
void SetBaseTransform (unsigned int i, BaseInputTransformType *trsf)
void SetBlockRegions (std::vector< ImageRegionType > &origins)
virtual void SetBlockScalarVarianceThreshold (double _arg)
virtual void SetFinalRadius (double _arg)
void SetFixedImage (InputImageType *fixedImage)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMetricKind (const SimilarityDefinition _arg)
virtual void SetMinimalTransformError (double _arg)
void SetMovingImage (InputImageType *movingImage)
virtual void SetOptimizerKind (const OptimizerDefinition _arg)
virtual void SetOptimizerMaximumIterations (unsigned int _arg)
virtual void SetScaleMax (double _arg)
virtual void SetSearchAngleRadius (double _arg)
virtual void SetSearchRadius (double _arg)
virtual void SetSearchScaleRadius (double _arg)
virtual void SetSearchSkewRadius (double _arg)
virtual void SetSkewMax (double _arg)
virtual void SetStepSize (double _arg)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetTransformKind (const TransformationDefinition _arg)
virtual void SetTranslateMax (double _arg)
void StartOptimization (void)
Protected Member Functions
virtual void AdditionalBlockMatchingSetup (MetricPointer &metric, unsigned int blockNum)
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
void BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType *fixedImage, InputImageType *resampledImage)
BlockMatchingBaseRegistrationMethod ()
virtual bool ComposeAddOnWithTransform (TransformType *computedTransform, TransformType *addOn)
void GenerateData ()
virtual void GlobalParametersSetup ()
Setting global parameters that don't need to be changed for each block or iteration.
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)=0
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &floatingImage)
virtual void SetupBlockParameters (InterpolatorPointer &interpolator, MetricPointer &metric, OptimizerPointer &optimizer, unsigned startBlock, unsigned endBlock)
Setting block related parameters that need to be changed for each block or iteration.
virtual void SetupTransform (TransformPointer &optimizedTransform)
virtual ~BlockMatchingBaseRegistrationMethod ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImage>
class anima::BlockMatchingBaseRegistrationMethod< TInputImage >
Definition at line 26 of file animaBlockMatchingBaseRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImage> typedef AffineTransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::AffineTransformPointer
Definition at line 72 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::AffineTransform<typename AgregatorType::ScalarType, TInputImage::ImageDimension> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::AffineTransformType
Type of the initialization transform .
Definition at line 71 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef BaseTransformAgregator<InputImageType::ImageDimension> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::AgregatorType
Type of Transform Agregator
Definition at line 56 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseInputTransformType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BaseInputTransformType
Definition at line 57 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseOutputTransformType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BaseOutputTransformType
Definition at line 58 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef BaseTransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BaseTransformPointer
Definition at line 94 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BaseTransformType
Type of the Transformation parameters This is the same type used to represent the search space of the optimization algorithm
Definition at line 93 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<const Self> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ConstPointer
Definition at line 33 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObject::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::DataObjectPointer
Smart Pointer type to a DataObject.
Definition at line 98 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::ProcessObject::DataObjectPointerArraySizeType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::DataObjectPointerArraySizeType
Make a DataObject of the correct type to be used as the specified output.
Definition at line 206 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef DisplacementFieldTransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::DisplacementFieldTransformPointer
Definition at line 64 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef rpi::DisplacementFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::DisplacementFieldTransformType
Definition at line 63 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::IndexType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ImageIndexType
Definition at line 48 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::RegionType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ImageRegionType
Definition at line 47 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::ConstPointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::InputImageConstPointer
Definition at line 45 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::InputImagePointer
Definition at line 46 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TInputImage anima::BlockMatchingBaseRegistrationMethod< TInputImage >::InputImageType
Type of the input image (both fixed and moving).
Definition at line 41 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InterpolatorType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::InterpolatorPointer
Definition at line 85 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::InterpolatorType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::InterpolatorType
Type of the Interpolator.
Definition at line 84 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::MetricPointer
Definition at line 53 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::ImageToImageMetric<InputImageType, InputImageType> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::MetricType
Type of the metric.
Definition at line 51 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef OptimizerType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::OptimizerPointer
Definition at line 89 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SingleValuedNonLinearOptimizer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::OptimizerType
Type of the optimizer.
Definition at line 88 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef MetricType::TransformParametersType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ParametersType
Definition at line 95 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::SmartPointer<Self> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::Pointer
Definition at line 32 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef InputImageType::PointType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::PointType
Type of points for Setting block origins
Definition at line 75 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef BlockMatchingBaseRegistrationMethod anima::BlockMatchingBaseRegistrationMethod< TInputImage >::Self
Standard class typedefs.
Definition at line 30 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::ProcessObject anima::BlockMatchingBaseRegistrationMethod< TInputImage >::Superclass
Definition at line 31 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef SVFTransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SVFTransformPointer
Definition at line 62 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::StationaryVelocityFieldTransform<typename AgregatorType::ScalarType, InputImageType::ImageDimension> anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SVFTransformType
RPI specific types
Definition at line 61 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::ConstPointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputConstPointer
Definition at line 81 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformOutputType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputPointer
Definition at line 80 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef itk::DataObjectDecorator< TransformType > anima::BlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputType
Type for the output: Using Decorator pattern for enabling the Transform to be passed in the data pipeline
Definition at line 79 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef TransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::TransformPointer
Definition at line 68 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> typedef AgregatorType::BaseOutputTransformType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::TransformType
Type of the Transform .
Definition at line 67 of file animaBlockMatchingBaseRegistrationMethod.h.
Member Enumeration Documentation
template<typename TInputImage> enum anima::BlockMatchingBaseRegistrationMethod::OptimizerDefinition
Enumerator
Exhaustive
Bobyqa
Definition at line 37 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> enum anima::BlockMatchingBaseRegistrationMethod::SimilarityDefinition
Enumerator
MeanSquares
Correlation
SquaredCorrelation
Definition at line 38 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> enum anima::BlockMatchingBaseRegistrationMethod::TransformationDefinition
Enumerator
Translation
Rigid
Affine
Definition at line 36 of file animaBlockMatchingBaseRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BlockMatchingBaseRegistrationMethod () protected
Constructor
Definition at line 37 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual anima::BlockMatchingBaseRegistrationMethod< TInputImage >::~BlockMatchingBaseRegistrationMethod () inline protected virtual
Definition at line 220 of file animaBlockMatchingBaseRegistrationMethod.h.
Member Function Documentation
template<typename TInputImage> void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::Abort () inline
Definition at line 216 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::AdditionalBlockMatchingSetup (MetricPointer & metric, unsigned int blockNum) protected virtual
Block matching specific setup depending on metrics and symmetric approaches, avoids to re-implement the whole block match procedure in sub-classes.
Definition at line 703 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References MeanSquares.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BlockMatch (unsigned threadId, unsigned NbThreads, InputImageType * fixedImage, InputImageType * resampledImage) protected
Definition at line 712 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References Bobyqa, Exhaustive, and MeanSquares.
Referenced by anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatching().
template<typename TInputImage > bool anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ComposeAddOnWithTransform (TransformType * computedTransform, TransformType * addOn) protected virtual
Definition at line 333 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References anima::composeSVF().
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GenerateData (void) protected
Method invoked by the pipeline in order to trigger the computation of the registration.
Definition at line 820 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual AgregatorType* anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetAgregator () virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetAngleMax () const virtual
template<typename TInputImage > BlockMatchingBaseRegistrationMethod< TInputImage >::BaseInputTransformType::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetBaseTransformPointer (unsigned int i)
Definition at line 99 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> std::vector<typename BaseInputTransformType::Pointer>& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetBaseTransformsPointers () inline
Definition at line 119 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> std::vector<ImageRegionType>& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockRegions () inline
Definition at line 116 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> virtual double anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockScalarVarianceThreshold () virtual
template<typename TInputImage> std::vector<double>& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetBlockWeights () inline
Definition at line 118 of file animaBlockMatchingBaseRegistrationMethod.h.
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetFinalRadius () const virtual
template<typename TInputImage> virtual InputImageType* anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetFixedImage () virtual
template<typename TInputImage> virtual const vnl_matrix<double>& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetGeometry () const virtual
template<typename TInputImage> virtual const bool& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMaximizeMetric () const virtual
template<typename TInputImage> virtual const unsigned int& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMaximumIterations () const virtual
template<typename TInputImage> virtual SimilarityDefinition anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMetricKind () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMinimalTransformError () const virtual
template<typename TInputImage> virtual InputImageType* anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMovingImage () virtual
template<typename TInputImage > itk::ModifiedTimeType anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetMTime () const
Method to return the latest modified time of this object or any of its cached ivars
Definition at line 73 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const char* anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented in anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >, anima::SymmetricBlockMatchingRegistrationMethod< TInputImage >, and anima::AsymmetricBlockMatchingRegistrationMethod< TInputImage >.
template<typename TInputImage> virtual OptimizerDefinition anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetOptimizerKind () const virtual
template<typename TInputImage> virtual const unsigned int& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetOptimizerMaximumIterations () const virtual
template<typename TInputImage > BlockMatchingBaseRegistrationMethod< TInputImage >::TransformOutputType * anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetOutput ()
Returns the transform resulting from the registration process
Get Output
Definition at line 847 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetScaleMax () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchAngleRadius () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchRadius () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchScaleRadius () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSearchSkewRadius () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSkewMax () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetStepSize () const virtual
template<typename TInputImage > const std::string anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetStopConditionDescription () const
Definition at line 914 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetSVFElasticRegSigma () const virtual
template<typename TInputImage> virtual TransformationDefinition anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetTransformKind () const virtual
template<typename TInputImage> virtual const double& anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GetTranslateMax () const virtual
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::GlobalParametersSetup () protected virtual
Setting global parameters that don't need to be changed for each block or iteration.
Definition at line 406 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Correlation, MeanSquares, Rigid, SquaredCorrelation, and Translation.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::Initialize () throw (itk::ExceptionObject) virtual
Initialize by setting the interconnects between the components.
Initialize by setting the interconnects between components.
Definition at line 122 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > itk::DataObject::Pointer anima::BlockMatchingBaseRegistrationMethod< TInputImage >::MakeOutput (DataObjectPointerArraySizeType idx) virtual
Definition at line 855 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected pure virtual
Implemented in anima::SymmetricBlockMatchingRegistrationMethod< TInputImage >, anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >, and anima::AsymmetricBlockMatchingRegistrationMethod< TInputImage >.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected virtual
PrintSelf
Definition at line 795 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References Bobyqa, Rigid, and Translation.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ResampleImages (TransformType * currentTransform, InputImagePointer & refImage, InputImagePointer & floatingImage) protected
Definition at line 261 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References anima::GetSVFExponential().
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetAgregator (AgregatorType * _arg) virtual
Set/Get Method for the Agregator
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetAngleMax (double _arg) virtual
Set/Get the upper bound on angles for bobyqa
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetBaseTransform (unsigned int i, BaseInputTransformType * trsf)
Definition at line 110 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetBlockRegions (std::vector< ImageRegionType > & origins)
Set / Get Block Origins
Definition at line 173 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetBlockScalarVarianceThreshold (double _arg) virtual
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetFinalRadius (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetFixedImage (InputImageType * fixedImage)
Set/Get the Fixed image.
Definition at line 871 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetInitialTransform (TransformPointer _arg) virtual
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetMaximumIterations (unsigned int _arg) virtual
Set/Get the maximum number of iterations
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetMetricKind (const SimilarityDefinition _arg) virtual
Set/Get the Metric.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetMinimalTransformError (double _arg) virtual
Set/Get the minimal error over consecutive transformations
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetMovingImage (InputImageType * movingImage)
Set/Get the Moving image.
Definition at line 898 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetOptimizerKind (const OptimizerDefinition _arg) virtual
Set/Get the Optimizer.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetOptimizerMaximumIterations (unsigned int _arg) virtual
Set/Get the maximum number of iterations per block if optimizer called
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetScaleMax (double _arg) virtual
Set/Get the upper bound on scales for bobyqa
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchAngleRadius (double _arg) virtual
Set/Get the search radius specific for angle search (rho start for bobyqa on rigid part)
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchRadius (double _arg) virtual
Set/Get the search radius (exhaustive search window, rho start for bobyqa)
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchScaleRadius (double _arg) virtual
Set/Get the search radius specific for scale search (rho start for bobyqa on affine part)
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSearchSkewRadius (double _arg) virtual
Set/Get the search radius specific for skew search (rho start for bobyqa on affine part)
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSkewMax (double _arg) virtual
Set/Get the upper bound on skews for bobyqa
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetStepSize (double _arg) virtual
Set/Get the final radius (rho end for bobyqa)
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetSVFElasticRegSigma (double _arg) virtual
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetTransformKind (const TransformationDefinition _arg) virtual
Set/Get the Transform.
template<typename TInputImage> virtual void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetTranslateMax (double _arg) virtual
Set/Get the upper bound on translations for bobyqa
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetupBlockParameters (InterpolatorPointer & interpolator, MetricPointer & metric, OptimizerPointer & optimizer, unsigned startBlock, unsigned endBlock) protected virtual
Setting block related parameters that need to be changed for each block or iteration.
Definition at line 465 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Bobyqa, Correlation, Exhaustive, MeanSquares, Rigid, SquaredCorrelation, and Translation.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::SetupTransform (TransformPointer & optimizedTransform) protected virtual
Definition at line 141 of file animaBlockMatchingBaseRegistrationMethod.hxx.
template<typename TInputImage > void anima::BlockMatchingBaseRegistrationMethod< TInputImage >::StartOptimization (void)
Starts the Registration Process
Definition at line 189 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References Affine, Rigid, and Translation.
template<typename TInputImage > ITK_THREAD_RETURN_TYPE anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatching (void * arg) static protected
Do the matching for a batch of regions (splited according to the thread id + nb threads)
Threaded block match
Definition at line 392 of file animaBlockMatchingBaseRegistrationMethod.hxx.
References anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::BlockMatch, anima::BlockMatchingBaseRegistrationMethod< TInputImage >::BlockMatch(), anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::fixedImage, and anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ThreadedMatchData::movingImage.
The documentation for this class was generated from the following files:
animaBlockMatchingBaseRegistrationMethod.h
animaBlockMatchingBaseRegistrationMethod.hxx