ANIMA: anima::LowMemoryCramersTestBridge Class Reference
anima::LowMemoryCramersTestBridge Class Reference
#include <animaLowMemCramersTestBridge.h>
Public Types
typedef
anima::ImageDataSplitter
< InputImageType > ImageSplitterType
typedef
anima::CramersTestImageFilter
< double >::TInputImage InputImageType
typedef
anima::CramersTestImageFilter
< double > MainFilterType
typedef
anima::ImageDataSplitter
< MaskImageType > MaskImageSplitterType
typedef
MainFilterType::MaskImageType MaskImageType
typedef
anima::CramersTestImageFilter
< double >::TOutputImage OutputImageType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryCramersTestBridge ()
void SetComputationMask (std::string &cMask)
void SetIndexesFromFiles (std::string firstFile, std::string secondFile)
void SetInputFileNames (std::string &fileList)
void SetNbSamples (unsigned int nbS)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int &nbT)
void SetOutlierMaskFileNames (std::string &fileList)
void SetOutputPrefix (std::string &pref)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryCramersTestBridge ()
Detailed Description
Definition at line 9 of file animaLowMemCramersTestBridge.h.
Member Typedef Documentation
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryCramersTestBridge::ImageSplitterType
Definition at line 14 of file animaLowMemCramersTestBridge.h.
typedef anima::CramersTestImageFilter<double>::TInputImage anima::LowMemoryCramersTestBridge::InputImageType
Definition at line 12 of file animaLowMemCramersTestBridge.h.
typedef anima::CramersTestImageFilter<double> anima::LowMemoryCramersTestBridge::MainFilterType
Definition at line 15 of file animaLowMemCramersTestBridge.h.
typedef anima::ImageDataSplitter< MaskImageType > anima::LowMemoryCramersTestBridge::MaskImageSplitterType
Definition at line 17 of file animaLowMemCramersTestBridge.h.
typedef MainFilterType::MaskImageType anima::LowMemoryCramersTestBridge::MaskImageType
Definition at line 16 of file animaLowMemCramersTestBridge.h.
typedef anima::CramersTestImageFilter<double>::TOutputImage anima::LowMemoryCramersTestBridge::OutputImageType
Definition at line 13 of file animaLowMemCramersTestBridge.h.
Constructor & Destructor Documentation
anima::LowMemoryCramersTestBridge::LowMemoryCramersTestBridge ()
Definition at line 8 of file animaLowMemCramersTestBridge.cxx.
anima::LowMemoryCramersTestBridge::~LowMemoryCramersTestBridge ()
Definition at line 23 of file animaLowMemCramersTestBridge.cxx.
Member Function Documentation
void anima::LowMemoryCramersTestBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 225 of file animaLowMemCramersTestBridge.cxx.
Referenced by Update().
std::string anima::LowMemoryCramersTestBridge::GetNameOfClass () inline
Definition at line 22 of file animaLowMemCramersTestBridge.h.
void anima::LowMemoryCramersTestBridge::SetComputationMask (std::string & cMask)
Definition at line 45 of file animaLowMemCramersTestBridge.cxx.
Referenced by main().
void anima::LowMemoryCramersTestBridge::SetIndexesFromFiles (std::string firstFile, std::string secondFile)
Definition at line 54 of file animaLowMemCramersTestBridge.cxx.
void anima::LowMemoryCramersTestBridge::SetInputFileNames (std::string & fileList)
Definition at line 32 of file animaLowMemCramersTestBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
void anima::LowMemoryCramersTestBridge::SetNbSamples (unsigned int nbS) inline
Definition at line 32 of file animaLowMemCramersTestBridge.h.
void anima::LowMemoryCramersTestBridge::SetNbSplits (unsigned int nbSplits) inline
Definition at line 30 of file animaLowMemCramersTestBridge.h.
void anima::LowMemoryCramersTestBridge::SetNumberOfThreads (unsigned int & nbT) inline
Definition at line 31 of file animaLowMemCramersTestBridge.h.
void anima::LowMemoryCramersTestBridge::SetOutlierMaskFileNames (std::string & fileList)
Definition at line 37 of file animaLowMemCramersTestBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
void anima::LowMemoryCramersTestBridge::SetOutputPrefix (std::string & pref) inline
Definition at line 28 of file animaLowMemCramersTestBridge.h.
void anima::LowMemoryCramersTestBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 99 of file animaLowMemCramersTestBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetComputationMask(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
The documentation for this class was generated from the following files:
animaLowMemCramersTestBridge.h
animaLowMemCramersTestBridge.cxx