ANIMA: anima::FuzzyCMeansFilter< ScalarType > Class Template Reference
anima::FuzzyCMeansFilter< ScalarType > Class Template Reference
#include <animaFuzzyCMeansFilter.h>
Public Types
typedef std::vector< VectorType > DataHolderType
typedef
itk::VariableLengthVector
< ScalarType > VectorType
Public Member Functions
void ComputeCentroids ()
bool endConditionReached (DataHolderType &oldMemberships)
FuzzyCMeansFilter ()
VectorType GetCentroid (unsigned int i)
VectorType GetClassesMembership (unsigned int i)
void InitializeClassesMemberships (DataHolderType &classM)
void InitializeCMeansFromData ()
void ResetClassesMemberships ()
void SetFlagSpectralClustering (bool flag)
void SetInputData (DataHolderType &data)
void SetMaxIterations (unsigned int mIt)
void SetMValue (double mV)
void SetNbClass (unsigned int nbC)
void SetPseudoSphericalDistance (bool spher)
void SetRelStopCriterion (double rC)
void SetVerbose (bool verb)
void Update ()
void UpdateMemberships ()
virtual ~FuzzyCMeansFilter ()
Detailed Description
template<class ScalarType>
class anima::FuzzyCMeansFilter< ScalarType >
Provides an implementation of fuzzy c-means, as proposed in J. C. Bezdek (1981): "Pattern Recognition with Fuzzy Objective Function Algoritms", Plenum Press, New York. It contains flags for interfacing it with spectral clustering, and to compute spherical distances rather than Euclidean distances.
Definition at line 16 of file animaFuzzyCMeansFilter.h.
Member Typedef Documentation
template<class ScalarType> typedef std::vector< VectorType > anima::FuzzyCMeansFilter< ScalarType >::DataHolderType
Definition at line 20 of file animaFuzzyCMeansFilter.h.
template<class ScalarType> typedef itk::VariableLengthVector<ScalarType> anima::FuzzyCMeansFilter< ScalarType >::VectorType
Definition at line 19 of file animaFuzzyCMeansFilter.h.
Constructor & Destructor Documentation
template<class ScalarType > anima::FuzzyCMeansFilter< ScalarType >::FuzzyCMeansFilter ()
Definition at line 12 of file animaFuzzyCMeansFilter.hxx.
template<class ScalarType > anima::FuzzyCMeansFilter< ScalarType >::~FuzzyCMeansFilter () virtual
Definition at line 33 of file animaFuzzyCMeansFilter.hxx.
Member Function Documentation
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::ComputeCentroids ()
Definition at line 85 of file animaFuzzyCMeansFilter.hxx.
References anima::ComputeSphericalCentroid().
template<class ScalarType > bool anima::FuzzyCMeansFilter< ScalarType >::endConditionReached (DataHolderType & oldMemberships)
Definition at line 179 of file animaFuzzyCMeansFilter.hxx.
template<class ScalarType> VectorType anima::FuzzyCMeansFilter< ScalarType >::GetCentroid (unsigned int i) inline
Definition at line 45 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> VectorType anima::FuzzyCMeansFilter< ScalarType >::GetClassesMembership (unsigned int i) inline
Definition at line 46 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::InitializeClassesMemberships (DataHolderType & classM)
Definition at line 293 of file animaFuzzyCMeansFilter.hxx.
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::InitializeCMeansFromData ()
Definition at line 201 of file animaFuzzyCMeansFilter.hxx.
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::ResetClassesMemberships () inline
Definition at line 38 of file animaFuzzyCMeansFilter.h.
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetFlagSpectralClustering (bool flag) inline
Definition at line 27 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::SetInputData (DataHolderType & data)
Definition at line 43 of file animaFuzzyCMeansFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetMaxIterations (unsigned int mIt) inline
Definition at line 28 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetMValue (double mV) inline
Definition at line 30 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetNbClass (unsigned int nbC) inline
Definition at line 26 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetPseudoSphericalDistance (bool spher) inline
Definition at line 31 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetRelStopCriterion (double rC) inline
Definition at line 29 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType> void anima::FuzzyCMeansFilter< ScalarType >::SetVerbose (bool verb) inline
Definition at line 41 of file animaFuzzyCMeansFilter.h.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::Update ()
Definition at line 56 of file animaFuzzyCMeansFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::Update().
template<class ScalarType > void anima::FuzzyCMeansFilter< ScalarType >::UpdateMemberships ()
Definition at line 136 of file animaFuzzyCMeansFilter.hxx.
The documentation for this class was generated from the following files:
animaFuzzyCMeansFilter.h
animaFuzzyCMeansFilter.hxx