ANIMA: CliProgress.h File Reference
CliProgress.h File Reference
#include "AnimaParsingExport.h"
Classes
class impl_cliprogress::ProgressDisplay
Namespaces
impl_cliprogress
Functions
ANIMAPARSING_EXPORT void progressFinished ()
ANIMAPARSING_EXPORT void setActivity (std::string)
ANIMAPARSING_EXPORT void setGraph (std::string name, float x, float y)
ANIMAPARSING_EXPORT void setImageF (std::string, int, int, const float *)
ANIMAPARSING_EXPORT void setImageG (std::string, int, int, const char *)
ANIMAPARSING_EXPORT void setImageRGB (std::string, int, int, const char *)
ANIMAPARSING_EXPORT void setProgress (std::string name, float cur, float max)
ANIMAPARSING_EXPORT void setStatus (std::string)
Function Documentation
ANIMAPARSING_EXPORT void progressFinished ()
Definition at line 220 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setFinished().
Referenced by GenericArguments::~GenericArguments().
ANIMAPARSING_EXPORT void setActivity (std::string)
Definition at line 215 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setActivity().
ANIMAPARSING_EXPORT void setGraph (std::string name, float x, float y)
Definition at line 209 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setGraph().
ANIMAPARSING_EXPORT void setImageF (std::string , int , int , const float *)
Definition at line 232 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageF().
ANIMAPARSING_EXPORT void setImageG (std::string , int , int , const char *)
Definition at line 226 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageG().
ANIMAPARSING_EXPORT void setImageRGB (std::string , int , int , const char *)
Definition at line 237 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageRGB().
ANIMAPARSING_EXPORT void setProgress (std::string name, float cur, float max)
Definition at line 197 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setProgress().
ANIMAPARSING_EXPORT void setStatus (std::string)
Definition at line 203 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setStatus().