ANIMA: CliProgress.cxx File Reference
CliProgress.cxx File Reference
#include <cstring>
#include <string>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <stdlib.h>
#include "CliProgress.h"
Namespaces
impl_cliprogress
Functions
void impl_cliprogress::encodeblock (const unsigned char in[3], unsigned char out[4], int len)
void progressFinished ()
void setActivity (std::string a)
void setGraph (std::string name, float x, float y)
void setImageF (std::string name, int width, int height, const float *data)
void setImageG (std::string name, int width, int height, const char *data)
void setImageRGB (std::string name, int width, int height, const char *data)
void setProgress (std::string name, float cur, float max)
void setStatus (std::string name)
Function Documentation
void progressFinished ()
Definition at line 220 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setFinished().
Referenced by GenericArguments::~GenericArguments().
void setActivity (std::string a)
Definition at line 215 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setActivity().
void setGraph (std::string name, float x, float y)
Definition at line 209 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setGraph().
void setImageF (std::string name, int width, int height, const float * data)
Definition at line 232 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageF().
void setImageG (std::string name, int width, int height, const char * data)
Definition at line 226 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageG().
void setImageRGB (std::string name, int width, int height, const char * data)
Definition at line 237 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setImageRGB().
void setProgress (std::string name, float cur, float max)
Definition at line 197 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setProgress().
void setStatus (std::string name)
Definition at line 203 of file CliProgress.cxx.
References impl_cliprogress::ProgressDisplay::instance(), and impl_cliprogress::ProgressDisplay::setStatus().