ANIMA: anima Namespace Reference
anima Namespace Reference
Classes
class AsymmetricBlockMatchingRegistrationMethod
class BackgroundNoiseVarianceEstimationImageFilter
class BalooSVFTransformAgregator
class BaseProbabilisticTractographyImageFilter
class BaseTransformAgregator
class BlockMatchingBaseRegistrationMethod
class BlockMatchingInitializer
class BobyqaOptimizer
BOBYQA Optimizer.
class Bootstrap4DVolumeImageFilter
class CombinedRelaxometryCostFunction
class CombinedRelaxometryEstimationImageFilter
class CramersTestImageFilter
class DDICostFunction
class DDILinearInterpolateImageFunction
class DDIModelAveragingImageFilter
class DDIModelEstimatorImageFilter
class DDIProbabilisticTractographyImageFilter
class DenseSVFTransformAgregator
class DTIEstimationImageFilter
class DTIExtrapolateImageFilter
class DTINonCentralChiCostFunction
class DTINonCentralChiEstimationImageFilter
class DTIProbabilisticTractographyImageFilter
class DTIScalarMapsImageFilter
Applies an variance filter to an image.
class dtiTractographyImageFilter
class DWISimulatorFromDTIImageFilter
class EPGSignalSimulator
struct errors_pair_comparator
class ExpTensorImageFilter
class FastCorrelationImageToImageMetric
class FasterLinearInterpolateImageFunction
class FDRCorrectImageFilter
class FibersWriter
class FiniteStrainDDIResampleImageFilter
class FiniteStrainTensorResampleImageFilter
class FuzzyCMeansFilter
Provides an implementation of fuzzy c-means, as proposed in J. C. Bezdek (1981): "Pattern Recognition with Fuzzy Objective Function Algoritms", Plenum Press, New York. It contains flags for interfacing it with spectral clustering, and to compute spherical distances rather than Euclidean distances.
class GaussianNoiseGeneratorImageFilter
class GeneralizedFAImageFilter
class GradientFileReader
class GradientFreeImageToImageMetric
class ImageDataSplitter
class ImageRegionSplitterMask
class InhomogeneousAOSLineDiffusionImageFilter
class InhomogeneousDiffusionImageFilter
class KissingSymmetricBlockMatchingRegistrationMethod
class KMeansFilter
class LocalPatchCovarianceDistanceImageFilter
class LocalPatchMeanDistanceImageFilter
class LogRigid3DTransform
class LogTensorImageFilter
class LowMemoryCramersTestBridge
class LowMemoryLocalPatchCovarianceDistanceBridge
class LowMemoryLocalPatchMeanDistanceBridge
class LowMemoryNLMeansPatientToGroupComparisonBridge
class LowMemoryPatientToGroupComparisonBridge
class LowMemoryPatientToGroupODFComparisonBridge
class LSWTransformAgregator
class LTSWTransformAgregator
class MaskedImageToImageFilter
class MatrixLoggerFilter
Class to compute many log-vectors in a multi-threaded way.
class MeanAndVarianceImagesFilter
class MEstimateSVFImageFilter
class MEstTransformAgregator
class ModularityClusteringFilter
class NewuoaOptimizer
Newuoa Optimizer.
class NLMeansPatientToGroupComparisonImageFilter
class NLOPTOptimizers
Implements an ITK wrapper for the NLOPT library.
class NonCentralChiNoiseGeneratorImageFilter
class NonLocalMeansImageFilter
class NonLocalMeansTemporalImageFilter
class ODFEstimatorImageFilter
class ODFMaximaCostFunction
class ODFProbabilisticTractographyImageFilter
class ODFSphericalHarmonicBasis
class OrientedModelBaseResampleImageFilter
struct pair_decreasing_comparator
class PatientToGroupComparisonImageFilter
Implements patient to group comparison as in http://dx.doi.org/10.1007/978-3-540-85988-8_116.
class PatientToGroupODFComparisonImageFilter
class PickLesionSeedImageFilter
class PseudoResidualsNoiseImageFilter
class PyramidalBlockMatchingBridge
class PyramidalDenseSVFMatchingBridge
class PyramidalDenseTensorSVFMatchingBridge
class PyramidalSymmetryBridge
class PyramidalSymmetryConstrainedRegistrationBridge
class PyramidImageFilter
class QMRISampleCreationImageFilter
class RecursiveLineYvvGaussianImageFilter
class ResampleImageFilter
class SampleImageFromDistributionImageFilter
class SimuBlochCoherentGRE
class SimuBlochGRE
class SimuBlochIRGRE
class SimuBlochIRSE
class SimuBlochSE
class SimuBlochSPGRE
class SmoothingRecursiveYvvGaussianImageFilter
class SPANClusteringFilter
class SpectralClusteringFilter
Provides an implementation of spectral clustering, as proposed in A.Y. Ng, M.I. Jordan and Y. Weiss. "On Spectral Clustering: Analysis and an Algorithm." Advances in Neural Information Processing Systems 14. 2001.
class SphericalHarmonic
class SplitAffine3DTransform
class StimulatedSpinEchoImageFilter
class SymmetricBlockMatchingRegistrationMethod
class SymmetryConstrainedTransform
class SymmetryPlaneTransform
class T1RelaxometryEstimationImageFilter
class T1SERelaxometryCostFunction
class T1SERelaxometryEstimationImageFilter
class T2EPGRelaxometryCostFunction
class T2EPGRelaxometryEstimationImageFilter
class T2RelaxometryEstimationImageFilter
class TensorAsymmetricBlockMatchingRegistrationMethod
class TensorBlockMatchingBaseRegistrationMethod
class TensorCorrelationImageToImageMetric
class TensorGeneralizedCorrelationImageToImageMetric
class TensorKissingSymmetricBlockMatchingRegistrationMethod
class TensorMeanSquaresImageToImageMetric
class TensorSymmetricBlockMatchingRegistrationMethod
class TransformSeriesReader
class VarianceImageFilter
Applies an averaging filter to an image.
class VectorModelLinearInterpolateImageFunction
class VoxelExhaustiveOptimizer
Typedefs
typedef itk::Matrix< double, 3, 3 > MatrixType
Enumerations
enum Indexes {
XDirIndex = 0,
YDirIndex = 1,
ZDirIndex = 2,
KappaIndex = 3,
DIndex = 4,
AIndex = 5,
WIndex = 6
}
A DDI compartment values are ordered this way.
Functions
double a0r_support (const double &x, unsigned int N)
Support function for besserl_ratio_i.
double ak_support (const double &x, unsigned int N, unsigned int k)
Support function for besserl_ratio_i.
double bessel_ratio_i (const double &x, unsigned int N, unsigned int approx_order=10)
Computes the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
void BHCorrection (std::vector< double > &pvalues)
In place correction of p-values according to Benjamini Hochberg FDR method.
void build_histogram (int myhist[], int cleaned_voxel_values[], int dummy_counter)
void clean_data (itk::Image< unsigned short, 3 >::Pointer image_ref, int &counter_brain_voxels_ref)
template<class ScalarType , unsigned int NDimensions>
void composeSVF (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *baseTrsf, itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *addonTrsf)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeAffineLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class T1 , class T2 >
double ComputeAngle (const std::vector< T1 > &v1, const std::vector< T2 > &v2)
template<class ScalarType >
ANIMASTATISTICS_EXPORT double ComputeAsymmetricPDF (const std::vector< ScalarType > &w, const std::vector< ScalarType > &mu, const ScalarType &kappa, const ScalarType &d, const ScalarType &nu, const ScalarType &step, std::vector< ScalarType > &integrand)
template<class ScalarType >
double ComputeAsymmetricPDF (const std::vector< ScalarType > &w, const std::vector< ScalarType > &mu, const ScalarType &kappa, const ScalarType &d, const ScalarType &nu, const ScalarType &step, std::vector< ScalarType > &integrand)
template<class T1 , class T2 , unsigned int Dimension>
void computeAverageLocalCovariance (vnl_matrix< T2 > &resVariance, const itk::VectorImage< T1, Dimension > *inputImage, itk::Image< unsigned char, Dimension > *maskImage, const itk::ImageRegion< Dimension > &averagingRegion, int localNeighborhood)
Noise estimation for a patch of a vector image.
template<class VectorType >
void ComputeCrossProduct (const VectorType &v1, const VectorType &v2, const unsigned int NDimension, VectorType &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const itk::Vector< ScalarType, NDimension > &v1, const itk::Vector< ScalarType, NDimension > &v2, itk::Vector< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const itk::VariableLengthVector< ScalarType > &v1, const itk::VariableLengthVector< ScalarType > &v2, itk::VariableLengthVector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const itk::Point< ScalarType, NDimension > &v1, const itk::Point< ScalarType, NDimension > &v2, itk::Point< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const vnl_vector< ScalarType > &v1, const vnl_vector< ScalarType > &v2, vnl_vector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const vnl_vector_fixed< ScalarType, NDimension > &v1, const vnl_vector_fixed< ScalarType, NDimension > &v2, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const std::vector< ScalarType > &v1, const std::vector< ScalarType > &v2, std::vector< ScalarType > &resVec)
template<class VectorType , class ScalarType , class Vector3DType >
ANIMASTATISTICS_EXPORT double ComputeDDICdf (const VectorType &modelValue, const ScalarType &b, const Vector3DType &grad, unsigned int NDimension)
template<class ScalarType , class Vector3DType >
ANIMASTATISTICS_EXPORT double ComputeDDICdf (const itk::VariableLengthVector< ScalarType > &modelValue, const ScalarType &b, const Vector3DType &grad)
template<class VectorType , class ScalarType , class Vector3DType >
double ComputeDDICdf (const VectorType &modelValue, const ScalarType &b, const Vector3DType &grad, unsigned int NDimension)
template<class ScalarType , class Vector3DType >
double ComputeDDICdf (const itk::VariableLengthVector< ScalarType > &modelValue, const ScalarType &b, const Vector3DType &grad)
template<class VectorType , class ScalarType >
ANIMASTATISTICS_EXPORT double ComputeDDIPdf (const VectorType &direction, const std::vector< ScalarType > &modelValue)
template<class VectorType , class ScalarType >
double ComputeDDIPdf (const VectorType &direction, const std::vector< ScalarType > &modelValue)
template<class VectorType >
double ComputeDirectedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeEuclideanDistance (const VectorType &x1, const VectorType &x2, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const itk::Vector< ScalarType, NDimension > &x1, const itk::Vector< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const itk::VariableLengthVector< ScalarType > &x1, const itk::VariableLengthVector< ScalarType > &x2)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const itk::Point< ScalarType, NDimension > &x1, const itk::Point< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const vnl_vector< ScalarType > &x1, const vnl_vector< ScalarType > &x2)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const vnl_vector_fixed< ScalarType, NDimension > &x1, const vnl_vector_fixed< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const std::vector< ScalarType > &x1, const std::vector< ScalarType > &x2)
template<class VectorType >
double ComputeHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeLogEuclideanAverage (std::vector< vnl_matrix< TInput > > &inputTransforms, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class T1 , class T2 , class VectorType >
ANIMASTATISTICS_EXPORT double ComputeMixtureSymmetricCDF (const unsigned int &NbComponents, const T2 *Directions, const T1 *Kappa, const T1 *Lambda, const T1 *Nu, const T1 *W, const T1 &b, const VectorType &grad)
template<class T1 , class T2 , class VectorType >
double ComputeMixtureSymmetricCDF (const unsigned int &NbComponents, const T2 *Directions, const T1 *Kappa, const T1 *Lambda, const T1 *Nu, const T1 *W, const T1 &b, const VectorType &grad)
template<class VectorType >
double ComputeModifiedDirectedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeModifiedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeNorm (const VectorType &v)
template<class T1 , class T2 >
double ComputeOrientationAngle (const std::vector< T1 > &v1, const std::vector< T2 > &v2)
template<class ScalarType , unsigned int NDimension>
double ComputeOrientationAngle (const itk::Vector< ScalarType, NDimension > &v1, const itk::Vector< ScalarType, NDimension > &v2)
template<class T1 , class T2 , unsigned int Dimension>
unsigned int computePatchMeanAndCovariance (const itk::VectorImage< T1, Dimension > *inputImage, const itk::ImageRegion< Dimension > &patchRegion, itk::VariableLengthVector< T2 > &patchMean, vnl_matrix< T2 > &patchCov)
Computes the average and covariance matrix from a patch of a vector image.
template<class VectorType >
double ComputePointToSetDistance (const VectorType &x, const std::vector< VectorType > &s)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeRigidLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class TInput , class TOutput >
vnl_matrix< TOutput > computeRotationFromQuaternion (vnl_vector< TInput > eigenVector)
template<class VectorType >
double ComputeScalarProduct (const VectorType &v1, const VectorType &v2, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const itk::Vector< ScalarType, NDimension > &v1, const itk::Vector< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const itk::VariableLengthVector< ScalarType > &v1, const itk::VariableLengthVector< ScalarType > &v2)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const itk::Point< ScalarType, NDimension > &v1, const itk::Point< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const vnl_vector< ScalarType > &v1, const vnl_vector< ScalarType > &v2)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const vnl_vector_fixed< ScalarType, NDimension > &v1, const vnl_vector_fixed< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const std::vector< ScalarType > &v1, const std::vector< ScalarType > &v2)
template<class VectorType , class DataHolderType >
VectorType ComputeSphericalCentroid (DataHolderType &dataPoints, VectorType &initPoint, VectorType &weights, double tol=1e-4)
template<class T1 , class VectorType >
ANIMASTATISTICS_EXPORT double ComputeSymmetricCDF (const VectorType &direction, const T1 &kappa, const T1 &lambda, const T1 &nu, const T1 &bvalue, const VectorType &gradient)
template<class T1 , class VectorType >
double ComputeSymmetricCDF (const VectorType &direction, const T1 &kappa, const T1 &lambda, const T1 &nu, const T1 &bvalue, const VectorType &gradient)
template<class VectorType , class ScalarType >
ANIMASTATISTICS_EXPORT double ComputeSymmetricPDF (const VectorType &w, const VectorType &mu, const ScalarType &kappa, const ScalarType &d, const ScalarType &nu, const ScalarType &step, std::vector< ScalarType > &integrand)
template<class VectorType , class ScalarType >
double ComputeSymmetricPDF (const VectorType &w, const VectorType &mu, const ScalarType &kappa, const ScalarType &d, const ScalarType &nu, const ScalarType &step, std::vector< ScalarType > &integrand)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeTranslationLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class VectorType , class ScalarType >
double ComputeVMFPdf (const VectorType &v, const VectorType &meanDirection, const ScalarType &kappa)
void EstimateLocalODFRotationMatrix (vnl_matrix< double > &resVal, unsigned int l, double alpha, double beta, double gamma)
double EvaluateDawsonFunction (double x)
compute Dawson(x) = sqrt(pi)/2 * exp(-x^2) * erfi(x)
double EvaluateDawsonFunctionNR (double x)
Numerical recipes implementation of Dawson integral.
template<class VectorType , class ScalarType >
double EvaluateWatsonPDF (const VectorType &v, const VectorType &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const vnl_vector_fixed< ScalarType, 3 > &v, const vnl_vector_fixed< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const itk::Point< ScalarType, 3 > &v, const itk::Point< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const itk::Vector< ScalarType, 3 > &v, const itk::Vector< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
double EvaluateWImFunction (double x)
double EvaluateWImY100Function (double y100, double x)
template<class VectorType >
VectorType exp_map (VectorType &p, VectorType &x)
template<class VectorType >
double ExponentialSum (const VectorType &x, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const itk::Vector< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const itk::VariableLengthVector< ScalarType > &x)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const itk::Point< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const vnl_vector< ScalarType > &x)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const vnl_vector_fixed< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const std::vector< ScalarType > &x)
template<typename PixelRawType , unsigned int ImageDimension>
void ExtractRotationFromMatrixTransform (itk::MatrixOffsetTransformBase< PixelRawType, ImageDimension, ImageDimension > *trsf, vnl_matrix< double > &rotationMatrix, vnl_matrix< double > &tmpMat)
template<class ScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom>
void filterInputs (itk::Image< ScalarType, NDimensions > *weights, typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::Pointer &output, std::vector< itk::Vector< ScalarType, NDegreesOfFreedom > > &curTrsfs, std::vector< typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::IndexType > &posIndexes, BalooSVFTransformAgregator< NDimensions > *filterPtr)
void find_max_index (int array[], int count, int &index)
double gammaHalfMinusN (unsigned int n)
double gammaHalfPlusN (unsigned int n)
double GetDValue (unsigned int l, int m, int mp, double angle)
void GetEulerAnglesFromJacobianMatrix (vnl_matrix< double > &J, std::vector< double > &resVal)
template<class T >
vnl_matrix< T > GetExponential (const vnl_matrix< T > &m, const int numApprox=1)
Computation of the matrix exponential. Algo: classical scaling and squaring, as in Matlab. See Higham, SIAM Matr. Anal., 2004.
template<class VectorType >
ANIMASTATISTICS_EXPORT double GetFascicleFA (const VectorType &modelValue, const unsigned int m)
template<class VectorType >
double GetFascicleFA (const VectorType &modelValue, const unsigned int m)
template<class T >
vnl_matrix< T > GetLogarithm (const vnl_matrix< T > &m, const double precision=0.00000000001, const int numApprox=1)
Computation of the matrix logarithm. Algo: inverse scaling and squaring, variant proposed by Cheng et al., SIAM Matrix Anal., 2001.
template<class T >
vnl_matrix< T > GetPadeLogarithm (const vnl_matrix< double > &m, const int numApprox)
Final part of the computation of the log. Estimates the log with a Pade approximation for a matrix m such that |m-Id| <= 0.5.
template<class T >
vnl_matrix< T > GetPadeLogarithm (const vnl_matrix< T > &m, const int numApprox)
template<class VectorType >
MatrixType GetRotationMatrixFromVectors (const VectorType &first_direction, const VectorType &second_direction, const unsigned int dimension)
template<class ScalarType >
MatrixType GetRotationMatrixFromVectors (const std::vector< ScalarType > &first_direction, const std::vector< ScalarType > &second_direction)
template<class ScalarType >
MatrixType GetRotationMatrixFromVectors (const itk::Point< ScalarType > &first_direction, const itk::Point< ScalarType > &second_direction)
template<class ScalarType , unsigned int NDimension>
MatrixType GetRotationMatrixFromVectors (const itk::Vector< ScalarType, NDimension > &first_direction, const itk::Vector< ScalarType, NDimension > &second_direction)
template<class T >
vnl_matrix< T > GetSquareRoot (const vnl_matrix< T > &m, const double precision, vnl_matrix< T > &resultM)
Gets the square root of matrix m.
template<class ScalarType , unsigned int NDimensions>
void GetSVFExponential (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *baseTrsf, rpi::DisplacementFieldTransform< ScalarType, NDimensions > *resultTransform, bool invert)
template<class T >
void GetTensorExponential (const vnl_matrix< T > &log_tensor, vnl_matrix< T > &tensor)
template<class T1 , class T2 >
void GetTensorFromVectorRepresentation (const itk::VariableLengthVector< T1 > &vector, vnl_matrix< T2 > &tensor, unsigned int tensDim=0, bool scale=false)
template<class T >
void GetTensorLogarithm (const vnl_matrix< T > &tensor, vnl_matrix< T > &log_tensor)
template<class T >
void GetTensorPower (const vnl_matrix< T > &tensor, vnl_matrix< T > &outputTensor, double powerValue)
template<class T1 , class T2 >
void GetVectorRepresentation (const vnl_matrix< T1 > &tensor, itk::VariableLengthVector< T2 > &vector, unsigned int vecDim=0, bool scale=false)
template<class VectorType >
ANIMASTATISTICS_EXPORT double GetVoxelFA (const VectorType &modelValue)
template<class VectorType >
double GetVoxelFA (const VectorType &modelValue)
template<class VectorType >
ANIMASTATISTICS_EXPORT double GetWhiteMatterFA (const VectorType &modelValue, unsigned int NDimension)
template<class ScalarType >
double GetWhiteMatterFA (const itk::VariableLengthVector< ScalarType > &modelValue)
template<class VectorType >
double GetWhiteMatterFA (const VectorType &modelValue, unsigned int NDimension)
std::vector< std::vector
< double > > InitializeSampleDirections (unsigned int nbTheta, unsigned int nbPhi, std::string sampleDirFileName)
template<class T >
ANIMASPECIALFUNCTIONS_EXPORT double jfour (const T &k)
template<class T >
double jfour (const T &k)
template<class T >
ANIMASPECIALFUNCTIONS_EXPORT double jtwo (const T &k)
template<class T >
double jtwo (const T &k)
double legendre_first_derivative (int L, int M, double value)
double legendre_second_derivative (int L, int M, double value)
double log_bessel_i (unsigned int order, const double &x)
Computes the log of modified Bessel function of the first kind: I_{N} (N >= 0)
double log_bessel_orderDerivative_i (const double &x, unsigned int order, double emc, unsigned int approx_order=50)
Computes the derivative of the log of modified Bessel function of the first kind w.r.t. its order (emc is the Euler-Mascheroni constant)
template<class VectorType >
VectorType log_map (VectorType &p, VectorType &x)
template<class VectorType >
void Normalize (const VectorType &v, const unsigned int NDimension, VectorType &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const itk::Vector< ScalarType, NDimension > &v, itk::Vector< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const itk::VariableLengthVector< ScalarType > &v, itk::VariableLengthVector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const itk::Point< ScalarType, NDimension > &v, itk::Point< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const vnl_vector< ScalarType > &v, vnl_vector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const vnl_vector_fixed< ScalarType, NDimension > &v, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const std::vector< ScalarType > &v, std::vector< ScalarType > &resVec)
void normalize_hist (itk::Image< unsigned short, 3 >::Pointer image, int cleaned_voxel_values[], itk::Image< unsigned short, 3 >::IndexType *coordinates, int dummy_counter, int mu_i_index, int mu_s_index)
int nyul_standardization (std::string inputFilename_ref, std::string inputFilename)
template<class T1 >
double ovlScore (vnl_diag_matrix< T1 > &eigsX, vnl_matrix< T1 > &eigVecsX, vnl_diag_matrix< T1 > &eigsY, vnl_matrix< T1 > &eigVecsY)
template<class TInput , class TOutput , unsigned int NDimensions>
void pairingToQuaternion (itk::Vector< TInput, NDimensions > inputPoint, itk::Vector< TInput, NDimensions > inputTransformedPoint, vnl_matrix< TOutput > &outputMatrix)
template<class T1 , class T2 , class T3 >
void ProjectOnOrthogonalPlane (const std::vector< T1 > &v, const std::vector< T2 > &normalVec, std::vector< T3 > &resVec)
double psi_function (unsigned int n, double emc)
template<class ImageType >
itk::SmartPointer< ImageType > read (std::string filename)
template<class T1 , class T2 >
void RecomposeTensor (vnl_diag_matrix< T1 > &eigs, vnl_matrix< T1 > &eigVecs, vnl_matrix< T2 > &resMatrix)
Recompose tensor from values extracted using SymmetricEigenAnalysis (vnl_symmetric_eigensystem transposes all this)
template<class VectorType >
void Revert (const VectorType &v, const unsigned int vSize, VectorType &resVec)
template<class ScalarType >
void Revert (const std::vector< ScalarType > &v, std::vector< ScalarType > &resVec)
template<class ScalarType >
void Revert (const itk::Point< ScalarType > &v, itk::Point< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Revert (const vnl_vector_fixed< ScalarType, NDimension > &v, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class T1 , class T2 , class T3 , class T4 >
void RotateAroundAxis (const std::vector< T1 > &v, const T2 &phi, const std::vector< T3 > &normalVec, std::vector< T4 > &resVec)
template<class Vector3DType , class ScalarType >
void RotateAroundAxis (const Vector3DType &v, const ScalarType &phi, const Vector3DType &normalVec, Vector3DType &resVec)
template<class T1 , class T2 >
void RotateSymmetricMatrix (vnl_matrix< T1 > &tensor, vnl_matrix< T2 > &rotationMatrix, vnl_matrix< T2 > &rotated_tensor)
template<class ScalarType >
double safe_log (const ScalarType x)
template<class T >
unsigned int SampleFromBernoulliDistribution (const T &p, boost::mt19937 &generator)
template<class T >
double SampleFromGaussianDistribution (const T &mean, const T &std, boost::mt19937 &generator)
template<class VectorType , class ScalarType >
void SampleFromMultivariateGaussianDistribution (const VectorType &mean, const vnl_matrix< ScalarType > &mat, VectorType &resVec, boost::mt19937 &generator, bool isMatCovariance=true)
template<class T >
double SampleFromUniformDistribution (const T &a, const T &b, boost::mt19937 &generator)
template<class VectorType , class ScalarType >
void SampleFromVMFDistribution (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, boost::mt19937 &generator)
template<class VectorType , class ScalarType >
void SampleFromVMFDistributionNumericallyStable (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, boost::mt19937 &generator)
template<class ScalarType , class VectorType >
void SampleFromWatsonDistribution (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, unsigned int DataDimension, boost::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const vnl_vector_fixed< ScalarType, DataDimension > &meanDirection, vnl_vector_fixed< ScalarType, DataDimension > &resVec, boost::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const itk::Point< ScalarType, DataDimension > &meanDirection, itk::Point< ScalarType, DataDimension > &resVec, boost::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const itk::Vector< ScalarType, DataDimension > &meanDirection, itk::Vector< ScalarType, DataDimension > &resVec, boost::mt19937 &generator)
template<class T >
double ShOverId (const T &x)
template<class T >
ANIMASPECIALFUNCTIONS_EXPORT double ShOverId (const T &x)
template<class T1 , class T2 , class T3 >
ANIMASPECIALFUNCTIONS_EXPORT double ShRatio (const T1 &k, const T2 &alpha, const T3 &beta)
template<class T1 , class T2 , class T3 >
double ShRatio (const T1 &k, const T2 &alpha, const T3 &beta)
template<class T >
double SinOverId (const T &x)
template<class T >
ANIMASPECIALFUNCTIONS_EXPORT double SinOverId (const T &x)
template<class VectorType >
void TransformCartesianToSphericalCoordinates (const VectorType &v, VectorType &resVec)
template<class VectorType >
void TransformSphericalToCartesianCoordinates (const VectorType &v, VectorType &resVec)
template<class T >
double VectorCovarianceTest (vnl_matrix< T > &logRefPatchCov, vnl_matrix< T > &movingPatchCov)
Test if covariance matrices are different (returns distance)
template<class T >
double VectorMeansTest (itk::VariableLengthVector< T > &refPatchMean, itk::VariableLengthVector< T > &movingPatchMean, const unsigned int &refPatchNumElts, const unsigned int &movingPatchNumElts, vnl_matrix< T > &refPatchCov, vnl_matrix< T > &movingPatchCov)
Test if vector means are different (returns distance)
template<class ScalarType , unsigned int Dimension>
double VMFDistance (const itk::Point< ScalarType, Dimension > &muFirst, const double &kappaFirst, const itk::Point< ScalarType, Dimension > &muSec, const double &kappaSec)
template<class OutputImageType >
void write (std::string filename, OutputImageType *img)
template<class T >
ANIMASPECIALFUNCTIONS_EXPORT double xi (const T &k)
template<class T >
double xi (const T &k)
Variables
static const unsigned int CompartmentSize = 7
A DDI compartment is composed of six components.
const double zeroWeight = 0
Typedef Documentation
typedef itk::Matrix<double,3,3> anima::MatrixType
Definition at line 8 of file animaMatrixOperations.h.
Enumeration Type Documentation
enum anima::Indexes
A DDI compartment values are ordered this way.
Enumerator
XDirIndex
YDirIndex
ZDirIndex
KappaIndex
DIndex
AIndex
WIndex
Definition at line 45 of file animaDDIDistribution.h.
Function Documentation
ANIMASPECIALFUNCTIONS_EXPORT double anima::a0r_support (const double & x, unsigned int N)
Support function for besserl_ratio_i.
Definition at line 103 of file animaBesselFunctions.cxx.
Referenced by bessel_ratio_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::ak_support (const double & x, unsigned int N, unsigned int k)
Support function for besserl_ratio_i.
Definition at line 108 of file animaBesselFunctions.cxx.
Referenced by bessel_ratio_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::bessel_ratio_i (const double & x, unsigned int N, unsigned int approx_order)
Computes the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
Definition at line 51 of file animaBesselFunctions.cxx.
References a0r_support(), and ak_support().
Referenced by anima::DTINonCentralChiEstimationImageFilter< PixelScalarType >::ComputeLocalSigma(), anima::DTINonCentralChiCostFunction::GetDerivative(), and log_bessel_i().
ANIMASTATISTICS_EXPORT void anima::BHCorrection (std::vector< double > & pvalues)
In place correction of p-values according to Benjamini Hochberg FDR method.
Definition at line 7 of file animaFDRCorrection.cxx.
Referenced by anima::FDRCorrectImageFilter< PixelScalarType >::GenerateData(), and anima::BackgroundNoiseVarianceEstimationImageFilter< TInputImage >::UpdateOutputFromPValues().
void anima::build_histogram (int myhist[], int cleaned_voxel_values[], int dummy_counter)
Definition at line 46 of file animaNyulStandardization.cpp.
References MAX_VALUE.
Referenced by nyul_standardization().
void anima::clean_data (itk::Image< unsigned short, 3 >::Pointer image_ref, int & counter_brain_voxels_ref)
Definition at line 82 of file animaNyulStandardization.cpp.
References MAX_BACKGROUND_VALUE, MAX_VALUE, and MIN_NOISE_VALUE.
Referenced by nyul_standardization().
template<class ScalarType , unsigned int NDimensions> void anima::composeSVF (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * baseTrsf, itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * addonTrsf)
Definition at line 10 of file animaVelocityUtils.hxx.
Referenced by anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ComposeAddOnWithTransform(), and anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ComposeAddOnWithTransform().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeAffineLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 174 of file animaLinearTransformEstimationTools.hxx.
template<class T1 , class T2 > double anima::ComputeAngle (const std::vector< T1 > & v1, const std::vector< T2 > & v2)
Definition at line 380 of file animaVectorOperations.hxx.
References ComputeNorm(), and ComputeScalarProduct().
template<class ScalarType > ANIMASTATISTICS_EXPORT double anima::ComputeAsymmetricPDF (const std::vector< ScalarType > & w, const std::vector< ScalarType > & mu, const ScalarType & kappa, const ScalarType & d, const ScalarType & nu, const ScalarType & step, std::vector< ScalarType > & integrand)
Definition at line 16 of file animaDDIDistribution.hxx.
References ComputeNorm(), ComputeScalarProduct(), and log_bessel_i().
template<class ScalarType > double anima::ComputeAsymmetricPDF (const std::vector< ScalarType > & w, const std::vector< ScalarType > & mu, const ScalarType & kappa, const ScalarType & d, const ScalarType & nu, const ScalarType & step, std::vector< ScalarType > & integrand)
Definition at line 16 of file animaDDIDistribution.hxx.
References ComputeNorm(), ComputeScalarProduct(), and log_bessel_i().
template<class T1 , class T2 , unsigned int Dimension> void anima::computeAverageLocalCovariance (vnl_matrix< T2 > & resVariance, const itk::VectorImage< T1, Dimension > * inputImage, itk::Image< unsigned char, Dimension > * maskImage, const itk::ImageRegion< Dimension > & averagingRegion, int localNeighborhood)
Noise estimation for a patch of a vector image.
Definition at line 65 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class VectorType > void anima::ComputeCrossProduct (const VectorType & v1, const VectorType & v2, const unsigned int NDimension, VectorType & resVec)
Definition at line 261 of file animaVectorOperations.hxx.
Referenced by ComputeCrossProduct().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const itk::Vector< ScalarType, NDimension > & v1, const itk::Vector< ScalarType, NDimension > & v2, itk::Vector< ScalarType, NDimension > & resVec)
Definition at line 271 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const itk::VariableLengthVector< ScalarType > & v1, const itk::VariableLengthVector< ScalarType > & v2, itk::VariableLengthVector< ScalarType > & resVec)
Definition at line 276 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const itk::Point< ScalarType, NDimension > & v1, const itk::Point< ScalarType, NDimension > & v2, itk::Point< ScalarType, NDimension > & resVec)
Definition at line 287 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const vnl_vector< ScalarType > & v1, const vnl_vector< ScalarType > & v2, vnl_vector< ScalarType > & resVec)
Definition at line 292 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const vnl_vector_fixed< ScalarType, NDimension > & v1, const vnl_vector_fixed< ScalarType, NDimension > & v2, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 303 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const std::vector< ScalarType > & v1, const std::vector< ScalarType > & v2, std::vector< ScalarType > & resVec)
Definition at line 308 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class VectorType , class ScalarType , class Vector3DType > ANIMASTATISTICS_EXPORT double anima::ComputeDDICdf (const VectorType & modelValue, const ScalarType & b, const Vector3DType & grad, unsigned int NDimension)
Definition at line 248 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, ComputeScalarProduct(), ComputeSymmetricCDF(), DIndex, KappaIndex, and WIndex.
Referenced by ComputeDDICdf(), and anima::DDIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate().
template<class ScalarType , class Vector3DType > ANIMASTATISTICS_EXPORT double anima::ComputeDDICdf (const itk::VariableLengthVector< ScalarType > & modelValue, const ScalarType & b, const Vector3DType & grad)
Definition at line 292 of file animaDDIDistribution.hxx.
References ComputeDDICdf().
template<class VectorType , class ScalarType , class Vector3DType > double anima::ComputeDDICdf (const VectorType & modelValue, const ScalarType & b, const Vector3DType & grad, unsigned int NDimension)
Definition at line 248 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, ComputeScalarProduct(), ComputeSymmetricCDF(), DIndex, KappaIndex, and WIndex.
Referenced by ComputeDDICdf(), and anima::DDIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate().
template<class ScalarType , class Vector3DType > double anima::ComputeDDICdf (const itk::VariableLengthVector< ScalarType > & modelValue, const ScalarType & b, const Vector3DType & grad)
Definition at line 292 of file animaDDIDistribution.hxx.
References ComputeDDICdf().
template<class VectorType , class ScalarType > ANIMASTATISTICS_EXPORT double anima::ComputeDDIPdf (const VectorType & direction, const std::vector< ScalarType > & modelValue)
Definition at line 163 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, ComputeSymmetricPDF(), KappaIndex, WIndex, XDirIndex, YDirIndex, and ZDirIndex.
template<class VectorType , class ScalarType > double anima::ComputeDDIPdf (const VectorType & direction, const std::vector< ScalarType > & modelValue)
Definition at line 163 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, ComputeSymmetricPDF(), KappaIndex, WIndex, XDirIndex, YDirIndex, and ZDirIndex.
template<class VectorType > double anima::ComputeDirectedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 96 of file animaVectorOperations.hxx.
References ComputePointToSetDistance().
Referenced by ComputeHausdorffDistance().
template<class VectorType > double anima::ComputeEuclideanDistance (const VectorType & x1, const VectorType & x2, const unsigned int NDimension)
Definition at line 18 of file animaVectorOperations.hxx.
Referenced by ComputeEuclideanDistance(), ComputePointToSetDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const itk::Vector< ScalarType, NDimension > & x1, const itk::Vector< ScalarType, NDimension > & x2)
Definition at line 30 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const itk::VariableLengthVector< ScalarType > & x1, const itk::VariableLengthVector< ScalarType > & x2)
Definition at line 35 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const itk::Point< ScalarType, NDimension > & x1, const itk::Point< ScalarType, NDimension > & x2)
Definition at line 45 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const vnl_vector< ScalarType > & x1, const vnl_vector< ScalarType > & x2)
Definition at line 50 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const vnl_vector_fixed< ScalarType, NDimension > & x1, const vnl_vector_fixed< ScalarType, NDimension > & x2)
Definition at line 61 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const std::vector< ScalarType > & x1, const std::vector< ScalarType > & x2)
Definition at line 66 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class VectorType > double anima::ComputeHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 114 of file animaVectorOperations.hxx.
References ComputeDirectedHausdorffDistance().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeLogEuclideanAverage (std::vector< vnl_matrix< TInput > > & inputTransforms, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 139 of file animaLinearTransformEstimationTools.hxx.
References GetExponential().
template<class T1 , class T2 , class VectorType > ANIMASTATISTICS_EXPORT double anima::ComputeMixtureSymmetricCDF (const unsigned int & NbComponents, const T2 * Directions, const T1 * Kappa, const T1 * Lambda, const T1 * Nu, const T1 * W, const T1 & b, const VectorType & grad)
Definition at line 298 of file animaDDIDistribution.hxx.
References ComputeScalarProduct(), ComputeSymmetricCDF(), and SinOverId().
Referenced by anima::DDICostFunction::GetValue().
template<class T1 , class T2 , class VectorType > double anima::ComputeMixtureSymmetricCDF (const unsigned int & NbComponents, const T2 * Directions, const T1 * Kappa, const T1 * Lambda, const T1 * Nu, const T1 * W, const T1 & b, const VectorType & grad)
Definition at line 298 of file animaDDIDistribution.hxx.
References ComputeScalarProduct(), ComputeSymmetricCDF(), and SinOverId().
Referenced by anima::DDICostFunction::GetValue().
template<class VectorType > double anima::ComputeModifiedDirectedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 123 of file animaVectorOperations.hxx.
References ComputePointToSetDistance().
Referenced by ComputeModifiedHausdorffDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class VectorType > double anima::ComputeModifiedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 136 of file animaVectorOperations.hxx.
References ComputeModifiedDirectedHausdorffDistance().
template<class VectorType > double anima::ComputeNorm (const VectorType & v)
Definition at line 321 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
Referenced by anima::DTIEstimationImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), ComputeAngle(), ComputeAsymmetricPDF(), anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::ComputeModelEstimation(), ComputeOrientationAngle(), ComputeSymmetricPDF(), ComputeVMFPdf(), anima::PickLesionSeedImageFilter< TInputImage, TOutputImage >::GenerateData(), Normalize(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), TransformCartesianToSphericalCoordinates(), and anima::GradientFileReader< GradientType, BValueScalarType >::Update().
template<class T1 , class T2 > double anima::ComputeOrientationAngle (const std::vector< T1 > & v1, const std::vector< T2 > & v2)
Definition at line 395 of file animaVectorOperations.hxx.
References ComputeNorm(), and ComputeScalarProduct().
Referenced by anima::dtiTractographyImageFilter::ComputeFiber(), and anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima().
template<class ScalarType , unsigned int NDimension> double anima::ComputeOrientationAngle (const itk::Vector< ScalarType, NDimension > & v1, const itk::Vector< ScalarType, NDimension > & v2)
Definition at line 408 of file animaVectorOperations.hxx.
References ComputeNorm(), and ComputeScalarProduct().
template<class T1 , class T2 , unsigned int Dimension> unsigned int anima::computePatchMeanAndCovariance (const itk::VectorImage< T1, Dimension > * inputImage, const itk::ImageRegion< Dimension > & patchRegion, itk::VariableLengthVector< T2 > & patchMean, vnl_matrix< T2 > & patchCov)
Computes the average and covariance matrix from a patch of a vector image.
Definition at line 10 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData(), anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class VectorType > double anima::ComputePointToSetDistance (const VectorType & x, const std::vector< VectorType > & s)
Definition at line 78 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
Referenced by ComputeDirectedHausdorffDistance(), ComputeModifiedDirectedHausdorffDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeRigidLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 74 of file animaLinearTransformEstimationTools.hxx.
References pairingToQuaternion().
template<class TInput , class TOutput > vnl_matrix< TOutput > anima::computeRotationFromQuaternion (vnl_vector< TInput > eigenVector)
Definition at line 239 of file animaLinearTransformEstimationTools.hxx.
template<class VectorType > double anima::ComputeScalarProduct (const VectorType & v1, const VectorType & v2, const unsigned int NDimension)
Definition at line 203 of file animaVectorOperations.hxx.
Referenced by anima::DTIEstimationImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), ComputeAngle(), ComputeAsymmetricPDF(), ComputeDDICdf(), anima::dtiTractographyImageFilter::ComputeFiber(), anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), ComputeMixtureSymmetricCDF(), ComputeNorm(), ComputeOrientationAngle(), ComputeScalarProduct(), ComputeSymmetricCDF(), ComputeSymmetricPDF(), ComputeVMFPdf(), anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex(), EvaluateWatsonPDF(), anima::ODFProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::DTIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::DDIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), ProjectOnOrthogonalPlane(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DDIModelAveragingImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const itk::Vector< ScalarType, NDimension > & v1, const itk::Vector< ScalarType, NDimension > & v2)
Definition at line 213 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const itk::VariableLengthVector< ScalarType > & v1, const itk::VariableLengthVector< ScalarType > & v2)
Definition at line 218 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const itk::Point< ScalarType, NDimension > & v1, const itk::Point< ScalarType, NDimension > & v2)
Definition at line 228 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const vnl_vector< ScalarType > & v1, const vnl_vector< ScalarType > & v2)
Definition at line 233 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const vnl_vector_fixed< ScalarType, NDimension > & v1, const vnl_vector_fixed< ScalarType, NDimension > & v2)
Definition at line 243 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const std::vector< ScalarType > & v1, const std::vector< ScalarType > & v2)
Definition at line 248 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class VectorType , class DataHolderType > VectorType anima::ComputeSphericalCentroid (DataHolderType & dataPoints, VectorType & initPoint, VectorType & weights, double tol = 1e-4)
Definition at line 48 of file animaLogExpMapsUnitSphere.hxx.
References exp_map(), and log_map().
Referenced by anima::FuzzyCMeansFilter< ScalarType >::ComputeCentroids().
template<class T1 , class VectorType > ANIMASTATISTICS_EXPORT double anima::ComputeSymmetricCDF (const VectorType & direction, const T1 & kappa, const T1 & lambda, const T1 & nu, const T1 & bvalue, const VectorType & gradient)
Definition at line 208 of file animaDDIDistribution.hxx.
References ComputeScalarProduct(), ShOverId(), ShRatio(), and SinOverId().
Referenced by ComputeDDICdf(), and ComputeMixtureSymmetricCDF().
template<class T1 , class VectorType > double anima::ComputeSymmetricCDF (const VectorType & direction, const T1 & kappa, const T1 & lambda, const T1 & nu, const T1 & bvalue, const VectorType & gradient)
Definition at line 208 of file animaDDIDistribution.hxx.
References ComputeScalarProduct(), ShOverId(), ShRatio(), and SinOverId().
Referenced by ComputeDDICdf(), and ComputeMixtureSymmetricCDF().
template<class VectorType , class ScalarType > ANIMASTATISTICS_EXPORT double anima::ComputeSymmetricPDF (const VectorType & w, const VectorType & mu, const ScalarType & kappa, const ScalarType & d, const ScalarType & nu, const ScalarType & step, std::vector< ScalarType > & integrand)
Definition at line 87 of file animaDDIDistribution.hxx.
References ComputeNorm(), ComputeScalarProduct(), and log_bessel_i().
Referenced by ComputeDDIPdf(), and main().
template<class VectorType , class ScalarType > double anima::ComputeSymmetricPDF (const VectorType & w, const VectorType & mu, const ScalarType & kappa, const ScalarType & d, const ScalarType & nu, const ScalarType & step, std::vector< ScalarType > & integrand)
Definition at line 87 of file animaDDIDistribution.hxx.
References ComputeNorm(), ComputeScalarProduct(), and log_bessel_i().
Referenced by ComputeDDIPdf(), and main().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeTranslationLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 13 of file animaLinearTransformEstimationTools.hxx.
References pairingToQuaternion().
template<class VectorType , class ScalarType > double anima::ComputeVMFPdf (const VectorType & v, const VectorType & meanDirection, const ScalarType & kappa)
Definition at line 20 of file animaVMFDistribution.hxx.
References ComputeNorm(), and ComputeScalarProduct().
ANIMASHTOOLS_EXPORT void anima::EstimateLocalODFRotationMatrix (vnl_matrix< double > & resVal, unsigned int l, double alpha, double beta, double gamma)
Definition at line 165 of file animaODFFunctions.cxx.
References GetDValue().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateDawsonFunction (double x)
compute Dawson(x) = sqrt(pi)/2 * exp(-x^2) * erfi(x)
Definition at line 49 of file animaErrorFunctions.cxx.
References EvaluateWImFunction().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateDawsonFunctionNR (double x)
Numerical recipes implementation of Dawson integral.
Definition at line 12 of file animaErrorFunctions.cxx.
Referenced by EvaluateWatsonPDF().
template<class VectorType , class ScalarType > double anima::EvaluateWatsonPDF (const VectorType & v, const VectorType & meanAxis, const ScalarType & kappa)
Definition at line 19 of file animaWatsonDistribution.hxx.
References ComputeScalarProduct(), and EvaluateDawsonFunctionNR().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection().
template<class ScalarType > double anima::EvaluateWatsonPDF (const vnl_vector_fixed< ScalarType, 3 > & v, const vnl_vector_fixed< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 58 of file animaWatsonDistribution.hxx.
template<class ScalarType > double anima::EvaluateWatsonPDF (const itk::Point< ScalarType, 3 > & v, const itk::Point< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 67 of file animaWatsonDistribution.hxx.
template<class ScalarType > double anima::EvaluateWatsonPDF (const itk::Vector< ScalarType, 3 > & v, const itk::Vector< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 76 of file animaWatsonDistribution.hxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateWImFunction (double x)
Definition at line 55 of file animaErrorFunctions.cxx.
References EvaluateWImY100Function().
Referenced by EvaluateDawsonFunction().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateWImY100Function (double y100, double x)
Definition at line 88 of file animaErrorFunctions.cxx.
Referenced by EvaluateWImFunction().
template<class VectorType > VectorType anima::exp_map (VectorType & p, VectorType & x)
Definition at line 25 of file animaLogExpMapsUnitSphere.hxx.
Referenced by ComputeSphericalCentroid().
template<class VectorType > double anima::ExponentialSum (const VectorType & x, const unsigned int NDimension)
Definition at line 146 of file animaVectorOperations.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter::ComputeFiber(), and ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const itk::Vector< ScalarType, NDimension > & x)
Definition at line 167 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const itk::VariableLengthVector< ScalarType > & x)
Definition at line 172 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const itk::Point< ScalarType, NDimension > & x)
Definition at line 178 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const vnl_vector< ScalarType > & x)
Definition at line 183 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const vnl_vector_fixed< ScalarType, NDimension > & x)
Definition at line 189 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const std::vector< ScalarType > & x)
Definition at line 194 of file animaVectorOperations.hxx.
References ExponentialSum().
template<typename PixelRawType , unsigned int ImageDimension> void anima::ExtractRotationFromMatrixTransform (itk::MatrixOffsetTransformBase< PixelRawType, ImageDimension, ImageDimension > * trsf, vnl_matrix< double > & rotationMatrix, vnl_matrix< double > & tmpMat)
Definition at line 126 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ComputeLinearRotationMatrix(), anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
template<class ScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::filterInputs (itk::Image< ScalarType, NDimensions > * weights, typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::Pointer & output, std::vector< itk::Vector< ScalarType, NDegreesOfFreedom > > & curTrsfs, std::vector< typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::IndexType > & posIndexes, BalooSVFTransformAgregator< NDimensions > * filterPtr)
Definition at line 408 of file animaBalooSVFTransformAgregator.hxx.
References anima::BalooSVFTransformAgregator< NDimensions >::GetExtrapolationSigma(), anima::BaseTransformAgregator< NDimensions >::GetInputRegions(), anima::BalooSVFTransformAgregator< NDimensions >::GetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::GetOutlierRejectionSigma(), and zeroWeight.
void anima::find_max_index (int array[], int count, int & index)
Definition at line 64 of file animaNyulStandardization.cpp.
Referenced by nyul_standardization().
ANIMASPECIALFUNCTIONS_EXPORT double anima::gammaHalfMinusN (unsigned int n)
Definition at line 35 of file animaGammaFunctions.cxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::gammaHalfPlusN (unsigned int n)
Definition at line 25 of file animaGammaFunctions.cxx.
ANIMASHTOOLS_EXPORT double anima::GetDValue (unsigned int l, int m, int mp, double angle)
Definition at line 110 of file animaODFFunctions.cxx.
Referenced by EstimateLocalODFRotationMatrix().
ANIMASHTOOLS_EXPORT void anima::GetEulerAnglesFromJacobianMatrix (vnl_matrix< double > & J, std::vector< double > & resVal)
Definition at line 68 of file animaODFFunctions.cxx.
References RecomposeTensor().
template<class T > vnl_matrix< T > anima::GetExponential (const vnl_matrix< T > & m, const int numApprox = 1)
Computation of the matrix exponential. Algo: classical scaling and squaring, as in Matlab. See Higham, SIAM Matr. Anal., 2004.
Definition at line 199 of file animaMatrixLogExp.hxx.
Referenced by computeLogEuclideanAverage(), anima::LogRigid3DTransform< TScalarType >::ComputeMatrix(), main(), anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), anima::TensorKissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), and anima::SymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration().
template<class VectorType > ANIMASTATISTICS_EXPORT double anima::GetFascicleFA (const VectorType & modelValue, const unsigned int m)
Definition at line 342 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection().
template<class VectorType > double anima::GetFascicleFA (const VectorType & modelValue, const unsigned int m)
Definition at line 342 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection().
template<class T > vnl_matrix< T > anima::GetLogarithm (const vnl_matrix< T > & m, const double precision = 0.00000000001, const int numApprox = 1)
Computation of the matrix logarithm. Algo: inverse scaling and squaring, variant proposed by Cheng et al., SIAM Matrix Anal., 2001.
Definition at line 146 of file animaMatrixLogExp.hxx.
References GetPadeLogarithm(), and GetSquareRoot().
Referenced by anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::InternalLogger(), main(), anima::TensorKissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), anima::KissingSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), anima::TensorSymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration(), and anima::SymmetricBlockMatchingRegistrationMethod< TInputImage >::PerformOneIteration().
template<class T > vnl_matrix<T> anima::GetPadeLogarithm (const vnl_matrix< double > & m, const int numApprox)
Final part of the computation of the log. Estimates the log with a Pade approximation for a matrix m such that |m-Id| <= 0.5.
Referenced by GetLogarithm().
template<class T > vnl_matrix<T> anima::GetPadeLogarithm (const vnl_matrix< T > & m, const int numApprox)
Definition at line 66 of file animaMatrixLogExp.hxx.
template<class VectorType > MatrixType anima::GetRotationMatrixFromVectors (const VectorType & first_direction, const VectorType & second_direction, const unsigned int dimension)
Definition at line 10 of file animaMatrixOperations.hxx.
References pairingToQuaternion().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::DDIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), GetRotationMatrixFromVectors(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), and SampleFromWatsonDistribution().
template<class ScalarType > MatrixType anima::GetRotationMatrixFromVectors (const std::vector< ScalarType > & first_direction, const std::vector< ScalarType > & second_direction)
Definition at line 35 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class ScalarType > MatrixType anima::GetRotationMatrixFromVectors (const itk::Point< ScalarType > & first_direction, const itk::Point< ScalarType > & second_direction)
Definition at line 43 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class ScalarType , unsigned int NDimension> MatrixType anima::GetRotationMatrixFromVectors (const itk::Vector< ScalarType, NDimension > & first_direction, const itk::Vector< ScalarType, NDimension > & second_direction)
Definition at line 51 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class T > vnl_matrix< T > anima::GetSquareRoot (const vnl_matrix< T > & m, const double precision, vnl_matrix< T > & resultM)
Gets the square root of matrix m.
Definition at line 14 of file animaMatrixLogExp.hxx.
Referenced by GetLogarithm().
template<class ScalarType , unsigned int NDimensions> void anima::GetSVFExponential (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * baseTrsf, rpi::DisplacementFieldTransform< ScalarType, NDimensions > * resultTransform, bool invert)
Definition at line 41 of file animaVelocityUtils.hxx.
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::addSVFTransformation(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputDisplacementFieldTransform(), anima::TensorBlockMatchingBaseRegistrationMethod< TInputImage >::ResampleImages(), anima::BlockMatchingBaseRegistrationMethod< TInputImage >::ResampleImages(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update().
template<class T > void anima::GetTensorExponential (const vnl_matrix< T > & log_tensor, vnl_matrix< T > & tensor)
Definition at line 53 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
template<class T1 , class T2 > void anima::GetTensorFromVectorRepresentation (const itk::VariableLengthVector< T1 > & vector, vnl_matrix< T2 > & tensor, unsigned int tensDim = 0, bool scale = false)
Definition at line 96 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), main(), anima::FiniteStrainTensorResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RotateInterpolatedModel(), anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), and anima::DTIScalarMapsImageFilter< ImageDimension >::ThreadedGenerateData().
template<class T > void anima::GetTensorLogarithm (const vnl_matrix< T > & tensor, vnl_matrix< T > & log_tensor)
Definition at line 10 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
template<class T > void anima::GetTensorPower (const vnl_matrix< T > & tensor, vnl_matrix< T > & outputTensor, double powerValue)
Definition at line 34 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by main().
template<class T1 , class T2 > void anima::GetVectorRepresentation (const vnl_matrix< T1 > & tensor, itk::VariableLengthVector< T2 > & vector, unsigned int vecDim = 0, bool scale = false)
Definition at line 72 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), main(), anima::FiniteStrainTensorResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RotateInterpolatedModel(), anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), and anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
template<class VectorType > ANIMASTATISTICS_EXPORT double anima::GetVoxelFA (const VectorType & modelValue)
Definition at line 363 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData().
template<class VectorType > double anima::GetVoxelFA (const VectorType & modelValue)
Definition at line 363 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData().
template<class VectorType > ANIMASTATISTICS_EXPORT double anima::GetWhiteMatterFA (const VectorType & modelValue, unsigned int NDimension)
Definition at line 394 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by GetWhiteMatterFA().
template<class ScalarType > double anima::GetWhiteMatterFA (const itk::VariableLengthVector< ScalarType > & modelValue)
Definition at line 434 of file animaDDIDistribution.hxx.
References GetWhiteMatterFA().
template<class VectorType > double anima::GetWhiteMatterFA (const VectorType & modelValue, unsigned int NDimension)
Definition at line 394 of file animaDDIDistribution.hxx.
References AIndex, CompartmentSize, DIndex, KappaIndex, WIndex, and xi().
Referenced by GetWhiteMatterFA().
ANIMASHTOOLS_EXPORT std::vector< std::vector< double > > anima::InitializeSampleDirections (unsigned int nbTheta, unsigned int nbPhi, std::string sampleDirFileName)
Definition at line 18 of file animaODFFunctions.cxx.
References TransformCartesianToSphericalCoordinates().
Referenced by main().
template<class T > ANIMASPECIALFUNCTIONS_EXPORT double anima::jfour (const T & k)
Definition at line 53 of file animaHyperbolicFunctions.hxx.
Referenced by main().
template<class T > double anima::jfour (const T & k)
Definition at line 53 of file animaHyperbolicFunctions.hxx.
Referenced by main().
template<class T > ANIMASPECIALFUNCTIONS_EXPORT double anima::jtwo (const T & k)
Definition at line 41 of file animaHyperbolicFunctions.hxx.
Referenced by main().
template<class T > double anima::jtwo (const T & k)
Definition at line 41 of file animaHyperbolicFunctions.hxx.
Referenced by main().
ANIMASPECIALFUNCTIONS_EXPORT double anima::legendre_first_derivative (int L, int M, double value)
Definition at line 11 of file animaLegendreDerivatives.cxx.
Referenced by anima::SphericalHarmonic::getThetaFirstDerivative(), anima::SphericalHarmonic::getThetaPhiDerivative(), and anima::SphericalHarmonic::getThetaSecondDerivative().
ANIMASPECIALFUNCTIONS_EXPORT double anima::legendre_second_derivative (int L, int M, double value)
Definition at line 47 of file animaLegendreDerivatives.cxx.
Referenced by anima::SphericalHarmonic::getThetaSecondDerivative().
ANIMASPECIALFUNCTIONS_EXPORT double anima::log_bessel_i (unsigned int order, const double & x)
Computes the log of modified Bessel function of the first kind: I_{N} (N >= 0)
Definition at line 14 of file animaBesselFunctions.cxx.
References bessel_ratio_i().
Referenced by ComputeAsymmetricPDF(), ComputeSymmetricPDF(), and anima::DTINonCentralChiCostFunction::GetValue().
ANIMASPECIALFUNCTIONS_EXPORT double anima::log_bessel_orderDerivative_i (const double & x, unsigned int order, double emc, unsigned int approx_order)
Computes the derivative of the log of modified Bessel function of the first kind w.r.t. its order (emc is the Euler-Mascheroni constant)
Definition at line 78 of file animaBesselFunctions.cxx.
References psi_function().
template<class VectorType > VectorType anima::log_map (VectorType & p, VectorType & x)
Definition at line 4 of file animaLogExpMapsUnitSphere.hxx.
Referenced by ComputeSphericalCentroid().
template<class VectorType > void anima::Normalize (const VectorType & v, const unsigned int NDimension, VectorType & resVec)
Definition at line 333 of file animaVectorOperations.hxx.
References ComputeNorm().
Referenced by Normalize(), ProjectOnOrthogonalPlane(), TransformCartesianToSphericalCoordinates(), and anima::GradientFileReader< GradientType, BValueScalarType >::Update().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const itk::Vector< ScalarType, NDimension > & v, itk::Vector< ScalarType, NDimension > & resVec)
Definition at line 346 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const itk::VariableLengthVector< ScalarType > & v, itk::VariableLengthVector< ScalarType > & resVec)
Definition at line 351 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const itk::Point< ScalarType, NDimension > & v, itk::Point< ScalarType, NDimension > & resVec)
Definition at line 357 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const vnl_vector< ScalarType > & v, vnl_vector< ScalarType > & resVec)
Definition at line 362 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const vnl_vector_fixed< ScalarType, NDimension > & v, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 368 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const std::vector< ScalarType > & v, std::vector< ScalarType > & resVec)
Definition at line 373 of file animaVectorOperations.hxx.
References Normalize().
void anima::normalize_hist (itk::Image< unsigned short, 3 >::Pointer image, int cleaned_voxel_values[], itk::Image< unsigned short, 3 >::IndexType * coordinates, int dummy_counter, int mu_i_index, int mu_s_index)
Definition at line 120 of file animaNyulStandardization.cpp.
References p1i, p2i, s1, and s2.
Referenced by nyul_standardization().
int anima::nyul_standardization (std::string inputFilename_ref, std::string inputFilename)
Definition at line 138 of file animaNyulStandardization.cpp.
References build_histogram(), clean_data(), find_max_index(), MAX_BACKGROUND_VALUE, MAX_VALUE, MIN_NOISE_VALUE, and normalize_hist().
Referenced by main().
template<class T1 > double anima::ovlScore (vnl_diag_matrix< T1 > & eigsX, vnl_matrix< T1 > & eigVecsX, vnl_diag_matrix< T1 > & eigsY, vnl_matrix< T1 > & eigVecsY)
Definition at line 214 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
template<class TInput , class TOutput , unsigned int NDimensions> void anima::pairingToQuaternion (itk::Vector< TInput, NDimensions > inputPoint, itk::Vector< TInput, NDimensions > inputTransformedPoint, vnl_matrix< TOutput > & outputMatrix)
Definition at line 263 of file animaLinearTransformEstimationTools.hxx.
Referenced by computeRigidLSWFromTranslations(), computeTranslationLSWFromTranslations(), and GetRotationMatrixFromVectors().
template<class T1 , class T2 , class T3 > void anima::ProjectOnOrthogonalPlane (const std::vector< T1 > & v, const std::vector< T2 > & normalVec, std::vector< T3 > & resVec)
Definition at line 495 of file animaVectorOperations.hxx.
References ComputeScalarProduct(), and Normalize().
ANIMASPECIALFUNCTIONS_EXPORT double anima::psi_function (unsigned int n, double emc)
Definition at line 13 of file animaGammaFunctions.cxx.
Referenced by log_bessel_orderDerivative_i().
template<class ImageType > itk::SmartPointer<ImageType> anima::read (std::string filename)
Definition at line 11 of file animaReadWriteFunctions.h.
Referenced by tinyxml2::XMLDocument::LoadFile().
template<class T1 , class T2 > void anima::RecomposeTensor (vnl_diag_matrix< T1 > & eigs, vnl_matrix< T1 > & eigVecs, vnl_matrix< T2 > & resMatrix)
Recompose tensor from values extracted using SymmetricEigenAnalysis (vnl_symmetric_eigensystem transposes all this)
Definition at line 165 of file animaBaseTensorTools.hxx.
Referenced by anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ComputeLocalRotationMatrix(), ExtractRotationFromMatrixTransform(), GetEulerAnglesFromJacobianMatrix(), GetTensorExponential(), GetTensorLogarithm(), GetTensorPower(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues(), SampleFromMultivariateGaussianDistribution(), and anima::SampleImageFromDistributionImageFilter< TInputPixelType >::ThreadedGenerateData().
template<class VectorType > void anima::Revert (const VectorType & v, const unsigned int vSize, VectorType & resVec)
Definition at line 421 of file animaVectorOperations.hxx.
Referenced by anima::dtiTractographyImageFilter::ComputeFiber(), and Revert().
template<class ScalarType > void anima::Revert (const std::vector< ScalarType > & v, std::vector< ScalarType > & resVec)
Definition at line 427 of file animaVectorOperations.hxx.
References Revert().
template<class ScalarType > void anima::Revert (const itk::Point< ScalarType > & v, itk::Point< ScalarType > & resVec)
Definition at line 433 of file animaVectorOperations.hxx.
References Revert().
template<class ScalarType , unsigned int NDimension> void anima::Revert (const vnl_vector_fixed< ScalarType, NDimension > & v, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 440 of file animaVectorOperations.hxx.
References Revert().
template<class T1 , class T2 , class T3 , class T4 > void anima::RotateAroundAxis (const std::vector< T1 > & v, const T2 & phi, const std::vector< T3 > & normalVec, std::vector< T4 > & resVec)
Definition at line 512 of file animaVectorOperations.hxx.
template<class Vector3DType , class ScalarType > void anima::RotateAroundAxis (const Vector3DType & v, const ScalarType & phi, const Vector3DType & normalVec, Vector3DType & resVec)
Definition at line 548 of file animaVectorOperations.hxx.
template<class T1 , class T2 > void anima::RotateSymmetricMatrix (vnl_matrix< T1 > & tensor, vnl_matrix< T2 > & rotationMatrix, vnl_matrix< T2 > & rotated_tensor)
Definition at line 186 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::FiniteStrainTensorResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RotateInterpolatedModel().
template<class ScalarType > double anima::safe_log (const ScalarType x)
Definition at line 9 of file animaLogarithmFunctions.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter::ComputeFiber(), anima::DTIProbabilisticTractographyImageFilter::ComputeModelEstimation(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships(), and VMFDistance().
template<class T > unsigned int anima::SampleFromBernoulliDistribution (const T & p, boost::mt19937 & generator)
Definition at line 36 of file animaDistributionSampling.hxx.
template<class T > double anima::SampleFromGaussianDistribution (const T & mean, const T & std, boost::mt19937 & generator)
Definition at line 48 of file animaDistributionSampling.hxx.
Referenced by SampleFromMultivariateGaussianDistribution(), anima::GaussianNoiseGeneratorImageFilter< Dimension >::TreatRegionWithNoiseVariance(), and anima::NonCentralChiNoiseGeneratorImageFilter< Dimension >::TreatRegionWithNoiseVariance().
template<class VectorType , class ScalarType > void anima::SampleFromMultivariateGaussianDistribution (const VectorType & mean, const vnl_matrix< ScalarType > & mat, VectorType & resVec, boost::mt19937 & generator, bool isMatCovariance = true)
Definition at line 61 of file animaDistributionSampling.hxx.
References RecomposeTensor(), and SampleFromGaussianDistribution().
Referenced by anima::SampleImageFromDistributionImageFilter< TInputPixelType >::BeforeThreadedGenerateData().
template<class T > double anima::SampleFromUniformDistribution (const T & a, const T & b, boost::mt19937 & generator)
Definition at line 24 of file animaDistributionSampling.hxx.
Referenced by anima::DDICostFunction::RandomGeometryInitialization(), anima::DDICostFunction::RandomOrientationInitializationFromDTI(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), and SampleFromWatsonDistribution().
template<class VectorType , class ScalarType > void anima::SampleFromVMFDistribution (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, boost::mt19937 & generator)
Definition at line 95 of file animaDistributionSampling.hxx.
References GetRotationMatrixFromVectors(), safe_log(), SampleFromUniformDistribution(), and TransformCartesianToSphericalCoordinates().
template<class VectorType , class ScalarType > void anima::SampleFromVMFDistributionNumericallyStable (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, boost::mt19937 & generator)
Definition at line 145 of file animaDistributionSampling.hxx.
References GetRotationMatrixFromVectors(), safe_log(), SampleFromUniformDistribution(), TransformCartesianToSphericalCoordinates(), and xi().
template<class ScalarType , class VectorType > void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, unsigned int DataDimension, boost::mt19937 & generator)
   void
SampleFromWatsonDistribution(const ScalarType &kappa,
                const VectorType &meanDirection,
                VectorType &resVec,
                unsigned int DataDimension,
                boost::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author
Aymeric Stamm
Date
October 2013
Parameters
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
DataDimension Dimension of the sphere + 1.
generator Pseudo-random number generator.
Definition at line 179 of file animaDistributionSampling.hxx.
References GetRotationMatrixFromVectors(), SampleFromUniformDistribution(), and TransformCartesianToSphericalCoordinates().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DDIProbabilisticTractographyImageFilter::ProposeNewDirection(), and SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const vnl_vector_fixed< ScalarType, DataDimension > & meanDirection, vnl_vector_fixed< ScalarType, DataDimension > & resVec, boost::mt19937 & generator)
   void
SampleFromWatsonDistribution(const ScalarType &kappa,
                const vnl_vector_fixed < ScalarType, DataDimension > &meanDirection,
                vnl_vector_fixed < ScalarType, DataDimension > &resVec,
                boost::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author
Aymeric Stamm
Date
October 2013
Parameters
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 279 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const itk::Point< ScalarType, DataDimension > & meanDirection, itk::Point< ScalarType, DataDimension > & resVec, boost::mt19937 & generator)
   void
SampleFromWatsonDistribution(const ScalarType &kappa,
                const itk::Point < ScalarType, DataDimension > &meanDirection,
                itk::Point < ScalarType, DataDimension > &resVec,
                boost::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author
Aymeric Stamm
Date
October 2013
Parameters
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 307 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const itk::Vector< ScalarType, DataDimension > & meanDirection, itk::Vector< ScalarType, DataDimension > & resVec, boost::mt19937 & generator)
   void
SampleFromWatsonDistribution(const ScalarType &kappa,
                const itk::Vector < ScalarType, DataDimension > &meanDirection,
                itk::Vector < ScalarType, DataDimension > &resVec,
                boost::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author
Aymeric Stamm
Date
October 2013
Parameters
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 335 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class T > double anima::ShOverId (const T & x)
Definition at line 8 of file animaHyperbolicFunctions.hxx.
Referenced by ComputeSymmetricCDF().
template<class T > ANIMASPECIALFUNCTIONS_EXPORT double anima::ShOverId (const T & x)
Definition at line 8 of file animaHyperbolicFunctions.hxx.
Referenced by ComputeSymmetricCDF().
template<class T1 , class T2 , class T3 > ANIMASPECIALFUNCTIONS_EXPORT double anima::ShRatio (const T1 & k, const T2 & alpha, const T3 & beta)
Definition at line 20 of file animaHyperbolicFunctions.hxx.
Referenced by ComputeSymmetricCDF().
template<class T1 , class T2 , class T3 > double anima::ShRatio (const T1 & k, const T2 & alpha, const T3 & beta)
Definition at line 20 of file animaHyperbolicFunctions.hxx.
Referenced by ComputeSymmetricCDF().
template<class T > double anima::SinOverId (const T & x)
Definition at line 8 of file animaTrigonometricFunctions.hxx.
Referenced by ComputeMixtureSymmetricCDF(), and ComputeSymmetricCDF().
template<class T > ANIMASPECIALFUNCTIONS_EXPORT double anima::SinOverId (const T & x)
Definition at line 8 of file animaTrigonometricFunctions.hxx.
Referenced by ComputeMixtureSymmetricCDF(), and ComputeSymmetricCDF().
template<class VectorType > void anima::TransformCartesianToSphericalCoordinates (const VectorType & v, VectorType & resVec)
Definition at line 445 of file animaVectorOperations.hxx.
References ComputeNorm(), and Normalize().
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::AddGradientDirection(), anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData(), anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima(), InitializeSampleDirections(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DDICostFunction::RandomOrientationInitializationFromDTI(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), SampleFromWatsonDistribution(), anima::DDICostFunction::SetOrientationsFromSimplerMCM(), and anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Update().
template<class VectorType > void anima::TransformSphericalToCartesianCoordinates (const VectorType & v, VectorType & resVec)
Definition at line 474 of file animaVectorOperations.hxx.
Referenced by anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima(), anima::DDICostFunction::GetValue(), and anima::DDIModelEstimatorImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class T > double anima::VectorCovarianceTest (vnl_matrix< T > & logRefPatchCov, vnl_matrix< T > & movingPatchCov)
Test if covariance matrices are different (returns distance)
Definition at line 147 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class T > double anima::VectorMeansTest (itk::VariableLengthVector< T > & refPatchMean, itk::VariableLengthVector< T > & movingPatchMean, const unsigned int & refPatchNumElts, const unsigned int & movingPatchNumElts, vnl_matrix< T > & refPatchCov, vnl_matrix< T > & movingPatchCov)
Test if vector means are different (returns distance)
Definition at line 179 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class ScalarType , unsigned int Dimension> double anima::VMFDistance (const itk::Point< ScalarType, Dimension > & muFirst, const double & kappaFirst, const itk::Point< ScalarType, Dimension > & muSec, const double & kappaSec)
Definition at line 51 of file animaVMFDistribution.hxx.
References safe_log().
template<class OutputImageType > void anima::write (std::string filename, OutputImageType * img)
Definition at line 29 of file animaReadWriteFunctions.h.
template<class T > ANIMASPECIALFUNCTIONS_EXPORT double anima::xi (const T & k)
Definition at line 29 of file animaHyperbolicFunctions.hxx.
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex(), anima::DDICostFunction::FixedGeometryInitialization(), GetFascicleFA(), anima::DDICostFunction::GetValue(), getVectorImage(), GetVoxelFA(), GetWhiteMatterFA(), main(), anima::DDIModelEstimatorImageFilter< PixelScalarType >::KappaUpperBoundSolverCostFunction::operator()(), anima::DDICostFunction::RandomGeometryInitialization(), SampleFromVMFDistributionNumericallyStable(), and anima::DDIModelEstimatorImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class T > double anima::xi (const T & k)
Definition at line 29 of file animaHyperbolicFunctions.hxx.
Referenced by anima::DDIModelEstimatorImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), anima::DDILinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex(), anima::DDICostFunction::FixedGeometryInitialization(), GetFascicleFA(), anima::DDICostFunction::GetValue(), getVectorImage(), GetVoxelFA(), GetWhiteMatterFA(), main(), anima::DDIModelEstimatorImageFilter< PixelScalarType >::KappaUpperBoundSolverCostFunction::operator()(), anima::DDICostFunction::RandomGeometryInitialization(), SampleFromVMFDistributionNumericallyStable(), and anima::DDIModelEstimatorImageFilter< PixelScalarType >::ThreadedGenerateData().
Variable Documentation
const unsigned int anima::CompartmentSize = 7 static
A DDI compartment is composed of six components.
Definition at line 42 of file animaDDIDistribution.h.
Referenced by ComputeDDICdf(), ComputeDDIPdf(), anima::DDIModelEstimatorImageFilter< PixelScalarType >::DDIModelEstimatorImageFilter(), GetFascicleFA(), getImage(), getVectorImage(), GetVoxelFA(), GetWhiteMatterFA(), main(), anima::FiniteStrainDDIResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RotateInterpolatedModel(), and anima::DDICostFunction::SetOrientationsFromSimplerMCM().
const double anima::zeroWeight = 0
Definition at line 84 of file animaBalooSVFTransformAgregator.h.
Referenced by filterInputs().